### ISSUE TITLE
Timeline coloring

### ISSUE THREAD

**Issue by Mottie** [StylishThemes/GitHub-Dark#100]
Continuing the [discussion from the code](https://github.com/StylishThemes/Github-Dark/commit/9ad904d3f8ce71724b10209b773692f3dcafca0a#commitcomment-5217184)

I tried this bit of css... the length may not work with percentages well. For example, this css (with an 85% stop) works great for [this issue with 13 comments](https://github.com/StylishThemes/Github-Dark/issues/55)

``` css
.new-discussion-timeline .discussion-timeline:before {
  left: -79px !important; /* only added for testing so you can see where the line ends */
  background: -webkit-linear-gradient(top, 
    rgba(51,51,51,1) 0%,
    rgba(51,51,51,1) 85%,
    rgba(51,51,51,0) 85%,
    rgba(0,0,0,0) 100%
  ) !important;
  background: -moz-linear-gradient(top,
    rgba(51,51,51,1) 0%,
    rgba(51,51,51,1) 85%,
    rgba(51,51,51,0) 85%,
    rgba(0,0,0,0) 100%
  ) !important;
}
```

Issue 79 with 25 comments needs the stop set at around 90%, and issue 98 with one comment needs it set to about 50%.
