### ISSUE TITLE
Allow github contributions graph to be displayed in the original green color.

### ISSUE THREAD

**Issue by Tomaso2468** [StylishThemes/GitHub-Dark#1002]
**Describe the change you'd like**
The contributions grid should have the option to display in the original green for the people that just want a simple dark theme.
![examplegithub](https://user-images.githubusercontent.com/48136416/65709212-32904300-e088-11e9-9908-c42dd72177e2.png)

**Comment by the-j0k3r** [comment]
@silverwind @Mottie @xt0rted for feedback pls.

@Tomaso2468 This type request should be accompanied by a screenshot of how it is and how you would like it to be color wise as a before and after type scenario.
Personally, adjusting the colors would be better overall for all users rather than adding a setting for the edge minority of users, but whatever other decide would be OK with me.

**Comment by Tomaso2468** [comment]
@the-j0k3r I have added a (badly: the link colour is a little off) edited image of what I meant.

**Comment by the-j0k3r** [comment]
Ah, I see what you mean now, I thought it was https://github.com/StylishThemes/GitHub-Dark/graphs/contributors rather than then https://github.com/yourusername.

If we support the @preprocessor stylus, this can be added in 3 minutes flat. Else its playing with convoluted dropdown options which Im not keen on.

Problem is that this style will conk out with @preprocessor stylus. We would have to rethink how certain things are done.

It probably easier for you to build your own style and remove the styling for this.
remove this
```css
  /* contribution calendar */
  .calendar-graph rect[fill="#c6e48b"], .calendar-graph rect[fill="#7bc96f"],
  .calendar-graph rect[fill="#239a3b"], .calendar-graph rect[fill="#196127"],
  .contrib-legend li, .contribution-activity-listing .progress-bar {
    background-color: /*[[base-color]]*/ !important;
    fill: /*[[base-color]]*/ !important;
  }
```

Or wait until such time that implementing this is done.

**Comment by Tomaso2468** [comment]
Ah, OK i'll try using removing that code from the script

**Comment by Tomaso2468** [comment]
![image](https://user-images.githubusercontent.com/48136416/65722566-66796180-e0a4-11e9-952a-688c46721452.png)
This is the effect of removing the code. Looks OK but the brightness is a little bit off.

**Comment by the-j0k3r** [comment]
I'll do you one better; Hers a style to override the GitHub Dark Calendar portions. You can just keep the style as was without removing any CSS.

You can select a different green color and make it brighter within reason, by default the brightness is 100% which is OK.

```css
/* ==UserStyle==
@name        GitHub Calendar Graph
@namespace   StylishThemes
@version     1.0.0
@description Allow a custom 
@license     CC-BY-SA-4.0
@author      StylishThemes

@var color base-color "Base color" #7bc96f
@var text  brightness "Brightness" 100%

@preprocessor stylus
==/UserStyle== */
@-moz-document regexp("^https?://((gist|guides|help|lab|launch-editor|raw|resources|status|developer)\\.)?github\\.com/((?!generated_pages/preview).)*$") {
	/* contribution calendar */
	body .calendar-graph rect[fill="#c6e48b"],
	body .calendar-graph rect[fill="#7bc96f"],
	body .calendar-graph rect[fill="#239a3b"],
	body .calendar-graph rect[fill="#196127"],
	body .contrib-legend li,
	body .contribution-activity-listing .progress-bar {
		background-color: base-color !important;
		fill: base-color !important;
		filter: brightness(brightness) !important;
	}
}
```

Use that, its better than waiting or having to remove CSS,
