### ISSUE TITLE
Any plan for new Github Blog site? https://github.blog/

### ISSUE THREAD

**Issue by xPixv** [StylishThemes/GitHub-Dark#1003]
https://github.blog/

It has replaced the old sub-domain https://blog.github.com

Thank you for your consideration. :P

------

Oh, I found your team has explained it before. 
https://github.com/StylishThemes/GitHub-Dark/issues/590#issuecomment-459110589

Alright, it's fine. Thank you anyway.

**Comment by Mottie** [comment]
Here's a good start:

```css
/* ==UserStyle==
@name         github.blog
@version      1.0.0
@description  Dark style for GitHub's blog site
@namespace    StylishThemes
@author       StylishThemes
@license      CC-BY-SA-4.0
@advanced color main-color "Main color" #07c
@advanced dropdown bg-choice "Background" {
  crosshatch "Cross-Hatch" <<<EOT
  url(https://camo.githubusercontent.com/5b8e4cd1a5ce69b6affa17ebd8e4aee00c147618/68747470733a2f2f7374796c6973687468656d65732e6769746875622e696f2f4769744875622d4461726b2f696d616765732f6261636b67726f756e64732f62672d63726f737368617463682e706e67) EOT;
  uniform "Uniform Tile" <<<EOT
  url(https://camo.githubusercontent.com/f83a9a60a2c64be0c88833ccb436e32a458cd2ce/68747470733a2f2f7374796c6973687468656d65732e6769746875622e696f2f4769744875622d4461726b2f696d616765732f6261636b67726f756e64732f62672d74696c652d756e69666f726d2e706e67) EOT;
  random "Random Tile" <<<EOT
  url(https://camo.githubusercontent.com/3beb850d8069e424480199a09899030c9e58e85f/68747470733a2f2f7374796c6973687468656d65732e6769746875622e696f2f4769744875622d4461726b2f696d616765732f6261636b67726f756e64732f62672d74696c65312e706e67) EOT;
  custom "Custom" <<<EOT
  var(--bg-custom) EOT;
  none "None" <<<EOT
  none EOT;
}
@advanced text bg-custom "Custom Background" "url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEYAAABGCAAAAABURb1YAAAFnklEQVR4AWWXCY4cwXbE6h4JMhCvMPc/ov+3Ox9QsLCGpKlFHILd+UQ559AGDkBSFXWmomonqkL/XuUcIPUcONjHCJyE36KaqNiaRnVCG9TGpgIU9hIfohCBVGj24ammo04lU3Fy0NZDAyZi5AElHjgEGlRbG1WjraIt7TmADQkAaoEHsOXAAaeqat9RVTqjosyEH5W+DQCQt8BzIJMfXJI3e5tGRefSlRn3NrO3scnvNl26FN5RITGNfjm3GM/+FhQgnlQeImC+dEm8rzHVTNGL9EADVsTAIfGJBziRy7RlmcZU1IYpHIj+4JrWym8/XSwzompmFNVOFdTOAAfs61KZ6eXcp57fykQUOxNBmTesz2HpCnCg3UV/bA7VRpWGNqKtrYLTs0ilCjgxiZxjeLC5dDPBFn4Pn2ja6BRUL10DTgET4Focq8rn8casxV4E5tIlZvytqtfivCOKZrqc38G7egnkXecyPZdzubc57VtUnbfL+a0u3b1N3d9Mci7cKocHoh3xihLQ6fXUlgTOOfVkXSUFINoWHhqxE23RTmCqtoEJaITkIrUCkU9fnqpqm+40VSXS3CLaSzfGBb4rPuOSfN0ylLve6/jpcrbL2dTlnOdv5AamKjLvLN1XruMNS/cul/hx8twKpKYRaE2DOp8+c+lW7uVXVQ7Vx0x1G3HXjNocsHCac7NbWc6egwJVHu2kRTVNC2pqv2U4XNsv5/yWJlV9+NJ1C7xluInlcr7rK+Kg+qy7onQqgnbi7UHcS3qXjdw3bO5tumycYlVssMI5EXXpRnatPK362KodtVU60cm+eQT10sVLFwJYlVaf7UGSoi5dQF3DvnTX3UvXTPO8quKH7jsXhm/PxfKWZXqBM5sS33kmKtC31Q05fI095i5IPpyzRXqSy1Sr17p1F7NE8vMtnNbLpVVtk8c0OrfF0sKxHnIpYgHW4puMomTz8mgmrSjpvrxhX97l7LqLpl7bW9BH9/MNzF8XwRqL8/m7c30eFYV5VX3QTquK06XbLt16F4ks+8Z9m6gPtpcuk3OvibCekng4lzMHi9MoqZmKj9tdbQCbc7bcEA+oEJduRNNL1waf1tuI9MDBUK8t3k9uFz3rrqadO9Ln9TL/ezlwDvky3TW7ZmXfpc77TN0yhOXnP939LvVDV9s+tgLTm0TqYd1lea3PRFuVjLa562HdPbCfascGrvO3DMeIATVqVRO8vfHrbupdfo1dzlXUdkVLZsS1mLPG3rWcl+4B1l1537h0VXzU1tyLG7cCu+LSrSqo06hocy3WCcil65qHDbuEYzQN2HpT3jFt9LEFvHTP1nxbXOEkbhkKmd+6BTfVZ/I143z/Fyz6Za92o0I7I6gzfeYAHPwy/Rb43L9TLtMt8CtwW1xvQvbR1g9n7qJRNN1kdxcdH7cM58Szxq679MdLOhE72t6VNEpHHkzwRyjBcGth+dE99pIkVbWaEWmvnQ8Yl7Mp59zpRWXdNo6odrO754Zzvxf/010nP7onb1TR+bgbVPB9PcADJvH/043Kvk0UzLRxQ6UiaeTAcyxYl2lyrrvZv8v2wE7U1uVcST0821jJeIDKWuyxiqnuko7q3+zJYXJ46nV3D67EyL+lQ9F2qkr+3kUafQpwYE8T329p6y7OX1TF97fQv/c+l87zj7Hsgpig4qRLd9fMPs74rLGyCzRbhmVqpy7nqvPmTD1gvKe7b2U8u1QzmtuDuEtbgT3c8QBJveo6cueFkUwv59nVmfFw1jl4/unuOT9qERV76ers8n23z/c8/Xy7a4lwwLplmGusbRp33Up13+ZDN3KPxNVMhY62vUQyRTse6+cKHtZYjIfDh260Cjbb3Vy6R8H8SMBzqSwrsB1UTacoknlnOb8V4JD9Njfpwz/fHjpBUeevcAtcl65sqXPX9D87RUTLc/dfOgAAAABJRU5ErkJggg==)"
@advanced dropdown bg-options "Background image type" {
  Tiled "Tiled" <<<EOT
  background-repeat: repeat !important;
  background-size: auto !important;
  background-position: left top !important; EOT;
  Fit window size "Fit window size" <<<EOT
  background-repeat: no-repeat !important;
  background-size: cover !important;
  background-position: center top !important; EOT;
}
@advanced dropdown bg-attachment "Background image attachment" {
  Scroll "Scroll" <<<EOT
  scroll EOT;
  Fixed "Fixed" <<<EOT
  fixed EOT;
}
@preprocessor uso
==/UserStyle== */
@-moz-document domain("github.blog") {
  :root {
    --main-color: /*[[main-color]]*/;
    --bg-custom: /*[[bg-custom]]*/;
    --bg-img: /*[[bg-choice]]*/;
  }
  body {
    background-color: #181818 !important;
    background-image: var(--bg-img) !important;
    background-clip: border-box !important;
    background-origin: padding-box !important;
    background-attachment: /*[[bg-attachment]]*/
    !important;
    /*[[bg-options]]*/
  }
  a {
    color: var(--main-color) !important;
  }
  a:hover,
  a:visited,
  a:active,
  a.link-gray:hover,
  a.link-gray:active,
  .btn:not(.btn-outline):hover,
  .hover-grow img {
    filter: brightness(110%) !important;
  }
  svg {
    fill: currentColor !important;
  }
  input:focus,
  select:focus,
  button:focus {
    border-color: var(--main-color) !important;
    box-shadow: inset 0 1px 2px rgba(0, 0, 0, .075), 0 0 2px var(--main-color) !important;
    outline-color: var(--main-color) !important;
  }

  /* background colors */
  .category__list:after {
    background-color: transparent !important;
  }
  .all-posts,
  .all-posts__container {
    background-color: #181818 !important;
  }
  .bg-gray,
  .sub-menu,
  .header-search {
    background-color: #222 !important;
  }
  .bg-gray-light,
  .Box {
    background-color: #2228 !important;
  }
  .category__list a:before {
    background-color: #444 !important;
  }
  /* blue */
  .cta-global__primary-bg,
  div[style="background-color: #032f62;"] {
    background-color: #182030 !important;
  }

  /* border colors */
  .primary-nav .sub-menu:after,
  .primary-nav .sub-menu:before,
  .header-search:before {
    border-bottom-color: #222 !important;
  }
  .category__list {
    border-left-color: #444 !important;
  }


  .text-gray-light,
  .category-panel__prev:not([disabled]) .icon,
  .category-panel__next:not([disabled]) .icon {
    color: #ddd !important;
  }
  h1,
  h2,
  h3,
  h4,
  h5,
  h6,
  .post-item__excerpt {
    color: #ccc !important;
  }
  .text-gray,
  .link-gray,
  .markdown-body p,
  .markdown-body li {
    color: #bbb !important;
  }
  .category-panel__prev[disabled] .icon,
  .category-panel__next[disabled] .icon {
    color: #555 !important;
  }


  .btn-outline {
    background: transparent !important;
    border-color: var(--main-color) !important;
    color: var(--main-color) !important;
  }
  .btn,
  .btn-outline:hover {
    background: var(--main-color) !important;
    border-color: #333 !important;
    color: #eee !important;
  }
  input {
    background-color: #111 !important;
    color: #ddd !important;
    border-color: #333 !important;
  }

  .icon-logo-github,
  .site-footer__social-list .icon,
  .hover-grow:not(:hover) .icon-arrow-skinny-right {
    filter: invert(80%) !important;
  }
  .category-hero__bg img {
    filter: invert(90%) hue-rotate(180deg) brightness(80%) !important;
  }

  .header-search__toggle.btn-outline {
    background-color: transparent !important;
    color: var(--main-color) !important;
  }
}
```

If I don't get some time this weekend to create a new repo, maybe someone else can get it going? (*cough* @the-j0k3r  *cough*).
