### ISSUE TITLE
Remove borders from several UI elements

### ISSUE THREAD

**Issue by saschanaz** [StylishThemes/GitHub-Dark#1017]
* **Browser**: Firefox
* **Operating System**: Windows 10
* **Link to page with the issue**: https://github.com/servo/servo/pull/24475
* **Screenshot**:

![image](https://user-images.githubusercontent.com/3396686/67098848-ddaf9a80-f1f7-11e9-9779-8d017e7f1e44.png)

Currently several borderless elements e.g. `.markdown-body code`, `.merge-pr-more-commits`, `.commit-ref` etc. are bordered. This seems to be from older GitHub styling, maybe we should update them?

**Comment by the-j0k3r** [comment]
@saschanaz I believe those are intentional and not an opinionated intrusive change.
That said, if this is something you rather not see, feel free to use something like this.

```css
/* ==UserStyle==
@name           GitHub Border Elements
@namespace      StylishThemes
@version        1.0.0
@description    Remove borders added to opinionated borderless GitHub elements.
@author         StylishThemes

@var checkbox removeBorders "Enable borders" 1

@preprocessor stylus
==/UserStyle== */
@-moz-document regexp("^https?://((gist|guides|help|lab|launch-editor|raw|resources|status|developer)\\.)?github\\.com/((?!generated_pages/preview).)*$"), domain("githubusercontent.com"), domain("graphql-explorer.githubapp.com"), domain("www.githubstatus.com") {
  if ! removeBorders {
    html body .markdown-body code,
    html body .merge-pr-more-commits,
    html body .commit-ref,
    html body .commit-link tt {
			border: 0 !important;
		}
	}
}
```

If you find any more selectors please let me know so I can add them to the style.
