### ISSUE TITLE
Invite user dropdown is missing hover style

### ISSUE THREAD

**Issue by xt0rted** [StylishThemes/GitHub-Dark#1022]
* **Browser**: chrome 78
* **Operating System**: win10
* **Link to page with the issue**:  https://github.com/orgs/:org:/people
* **Screenshot**:

![image](https://user-images.githubusercontent.com/831974/67971924-154d1800-fbe4-11e9-8451-201dc0230576.png)

There is a hover style, but it's being overridden by this rule because of the `!important`. Is it safe to remove the `!important` or should the selector get added to another rule that also has an `!important` on it? I know we were trying to remove the use of this at one point, wasn't really sure where things stood with it though. Removing the `.typeahead-result` selector from this rule also fixes it but I'm not sure where else this might be used to check if it's broken or not.

```css
/* Navigation focus */
.list-browser-item.navigation-focus, .js-details-container.navigation-focus,
.js-details-container.navigation-focus:nth-child(2n), .team-grid .team-members,
.tree-browser tr.navigation-focus td,
.issues-listing .table-list-issues .selectable:hover,
.issues-listing .table-list-issues .navigation-focus, .setup-plans tr.selected,
.notifications .navigation-focus, .sidebar-module ul ul li a:hover,
.typeahead-result, .no-results, .link-overlay .link, #gollum-editor-help-list,
.owner-select-target, .divider .blob-code div.highlight,
.oauth-org-access-details .boxed-group-list > li.on:hover, pre div:hover,
.summary-stats li a:hover, .pinned-repos-selection-list-item.selected,
.Box-body-row--highlight.navigation-focus, .Box-body-row--highlight:hover,
.js-current .standalone a, .menu-item:hover,
.Box-row--focus-gray.navigation-focus, .team-listing .is-open.root-team,
.Box-row--hover-gray:hover, table.files tr[aria-selected="true"] td,
.select-menu-item[aria-checked="true"]:not(.selected):not([role="menuitemradio"]):hover,
.label-select-menu .select-menu-item.navigation-focus,
.label-select-menu .select-menu-item:focus,
.label-select-menu .select-menu-item:hover {
  background: #242424 !important;
}
```

**Comment by the-j0k3r** [comment]
What about putting the offending rule on a non `!important` rule with same properties?

**Comment by the-j0k3r** [comment]
Actually removing it is best as `.typeahead-result` doesnt have a bg color, it may very well break something but this was also added a very long time ago.

```css
.typeahead-result {
	position: relative;
	display: block;
	min-width: 100%;
	padding: 10px;
	margin-top: 0;
	color: #333;
	cursor: pointer;
}
```

I doubt it will break anything cause the other instances of this selector are autogenerated.
