### ISSUE TITLE
sponsors notice (inline html style) https://github.com/

### ISSUE THREAD

**Issue by the-j0k3r** [StylishThemes/GitHub-Dark#1024]
Theres a new sponsors notice and cant style border of it. not sure if at all possible given the inline style for border is !important` which seems not to take with CSS below.

* **Link to page with the issue**: https://github.com/
* **Screenshot**:
![generic](https://user-images.githubusercontent.com/31389848/68188862-6ecd9200-ffaa-11e9-8149-b00d01b11a1c.gif)

```css
	.application-main aside form[style*="background: #ffeef8; border: 1px solid #ec6cb9 !important;"] {
		background: #370422 !important;
		border: 1px solid #3e0627 !important;
	}
```

The CSS above works to style the bg, the `[style*="background: #ffeef8; border: 1px solid #ec6cb9 !important;"]` is enough but tried increasing specificity to try get at the border which didnt do it.

Do we want to bother with this these types inline styles are 1980 domain IDK what GH is doing with these more and more these days either.

feedback pls. @xt0rted @Mottie
