### ISSUE TITLE
Refined Github creates white background on my reaction icons

### ISSUE THREAD

**Issue by coreyfarrell** [StylishThemes/GitHub-Dark#1035]
Refined Github has a style:
```css
.reaction-summary-item.user-has-reacted {
	--background: #f2f8fa;
}
```

This results in an oddly out of place white background for the icon of my own reactions.  I've fixed this in my own browser by adding a custom userstyle to my browser:
```css
/* ==UserStyle==
@name           Refined-Github Dark fix
@namespace      github.com/cfware
@version        1.0.0
@description    Fix conflict refined-github dark conflict
@author         Me
==/UserStyle== */

@-moz-document domain("github.com") {
    .reaction-summary-item.user-has-reacted {
        --background: transparent!important;
    }
}
```

Would Github-Dark consider adding something to like this?

* **Browser**: Firefox 70
* **Operating System**: Fedora 30
* **Link to page with the issue**: https://github.com/facebook/jest/pull/9192#discussion_r348574868
* **Screenshot**:
![Screenshot from 2019-11-20 13-06-55](https://user-images.githubusercontent.com/903597/69265229-daad1e80-0b96-11ea-95df-98efc9b50067.png)

**Comment by silverwind** [comment]
What is this `--background` syntax exactly? I've never seen a variable in a propery name. I assume replacing with `background` works as expected?

**Comment by coreyfarrell** [comment]
`--background` is a [CSS Variable](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_variables) being set for that specific selector and its children.  Just setting background on this class would not work as the `--background` variable is actually being applied to an `img` within:

```css
.reaction-summary-item img {
	max-width: 100%;
	border-radius: inherit;
	background-color: var(--background);
}
```

Simply overwriting the background of this img does also work.
