### ISSUE TITLE
Linked diff lines should not be grey

### ISSUE THREAD

**Issue by silverwind** [StylishThemes/GitHub-Dark#1037]
https://github.com/go-gitea/gitea/pull/9114/files#diff-b67911656ef5d18c4ae36cb6741b7965R357-R361

Compare:

<img width="404" alt="Screen Shot 2019-11-22 at 13 36 12" src="https://user-images.githubusercontent.com/115237/69426232-111ca200-0d2d-11ea-8187-bbeffa9e0be8.png">
<img width="403" alt="Screen Shot 2019-11-22 at 13 35 55" src="https://user-images.githubusercontent.com/115237/69426233-11b53880-0d2d-11ea-8251-0f88ad4e785b.png">

We should attempt to get more close to the original style here. Slightly brigher then regular colors on the link highlight and add the border as well. Maybe try a yellow shade.

**Comment by the-j0k3r** [comment]
Ive noticed this before.

Though its not quite gray, that color though is coming from 

```
.selected-line::after {
	position: absolute;
	top: 0;
	left: 0;
	display: block;
	width: 100%;
	height: 100%;
	box-sizing: border-box;
	pointer-events: none;
	content: "";
	background: rgba(255,223,93,.2);
	mix-blend-mode: multiply;
}
```

That area has also these default styles

```css
.selected-line.selected-line-right::after, .selected-line:last-child::after {
	border-right: 1px solid #ffd33d;
}

.selected-line.selected-line-top::after {
	border-top: 1px solid #ffd33d;
}
```

Problem is we do style the blob selected lines and idk how to get around that. While this is in a important rule, just doest seem to be a factor.

How about this

```
   td.selected-line.blob-num-deletion, td.selected-line.blob-code-deletion {
    background: #481010 !important;
  }
   td.selected-line.blob-num-addition, td.selected-line.blob-code-addition {
    background: #103810 !important;
  }
```

**Comment by silverwind** [comment]
Nice investigation. I will have a detailed look later to resolve this, will probably rewrite this quite a bit.

**Comment by the-j0k3r** [comment]
> will probably rewrite this quite a bit.

Be gentle. these areas are a delicate balance from paste experience improving them.

Also dont forget you can link selected lines on plain blob additions/removals so to counter that I did this.

```css
.blob-num.selected-line::after {
	background-color: rgba(104, 84, 3, .1);
	filter: brightness(150%)
}
```
just adding filter makes these areas add more contrast. And we cant use opaque colors.

![generic](https://user-images.githubusercontent.com/31389848/69430649-601b0500-0d36-11ea-971e-4cb1e86e323c.gif)
