### ISSUE TITLE
New help.github.com side menu

### ISSUE THREAD

**Issue by xt0rted** [StylishThemes/GitHub-Dark#1038]
In the last few days a new side menu was added to https://help.github.com that uses blue for the background. This is being picked up by the generator but it looks a bit out of place. Anyone opposed to setting this to something like this?

```css
.sidebar {
  background-color: #1c1c1c;
  border-right: 1px solid #343434;
}
```

This is the same color & style of the left column of your dashboard at github.com
