### ISSUE TITLE
user status background shouldn't be patterns

### ISSUE THREAD

**Issue by su8ru** [StylishThemes/GitHub-Dark#1044]
* **Browser**: Google Chrome 79
* **Operating System**: Windows 10
* **Link to page with the issue**: ex.)https://github.com/su8ru (not only me but also everyone)
* **Screenshot**:
![image](https://user-images.githubusercontent.com/33474143/71765649-c51f6880-2f3a-11ea-99db-edce6663ee71.png)

Sorry for my bad English.

**Comment by the-j0k3r** [comment]
This portion has no actual styling even on default. its easily fixed with 

```css
.page-profile .user-status-container {
    background: #181818;
 }
```

Bare with me.
