### ISSUE TITLE
Colored file list items

### ISSUE THREAD

**Issue by SonOfDiablo** [StylishThemes/GitHub-Dark#1048]
**Describe the change you'd like**
Coloring the file names in the file list of a repo based on the extension.

**Additional context**
Some like this userscript [GitHub file list beautifier](https://greasyfork.org/en/scripts/5982-github-file-list-beautifier)

Here is a screenshot of how it looks like with the GitHub Dark theme and the Userscript (The icons are from [this browser extension](https://github.com/xxhomey19/github-file-icon) and not part of this feature request)
![ScreenShot](https://i.imgur.com/XXEkg3f.png)

**Comment by the-j0k3r** [comment]
Hello @SonOfDiablo 

I'm not sure this is possible with just CSS, given the selectors are pretty much the same.

Second opinion @Mottie @xt0rted.

**Comment by the-j0k3r** [comment]
Hello @SonOfDiablo 

I'm not sure this is possible with just CSS, given the selectors are pretty much the same. If it is possible, it would be a massive addition and great deal of work to color by file type and this would likely be a [Feature Override Style](https://github.com/StylishThemes/Feature-Override-Styles).

Also I have no interest in this personally, too much work for something that for better or worst already exists in script form for those who like yourself prefer this..

Second opinion @Mottie @xt0rted.

**Comment by xt0rted** [comment]
With github's current html setup this is possible in css, but it's not something that should ever be part of this theme. The html also makes no distinction between file and folder links so folders will be a little harder to style, but files should be nothing more than:

```css
.files a[title="authors" i] {
  color: lime;
}

.files a[title$=".js" i] {
  color: yellow;
}
```

**Comment by the-j0k3r** [comment]
Well easy is relative, all the file types alone is no easy ask.

**Comment by the-j0k3r** [comment]
Here is a list for reference of file types https://en.wikipedia.org/wiki/List_of_file_formats#Physical_recordable_media_archiving

The best way to go about this, would be to do it in groups of like files as link indicates and each group would be colored individually that way you dont run out of colors or use too similar colors, although the latter would be minimized by allowing group color customization.

To be of any use this feature style would need to be at least a the most common file types entries long and would have a dedicated developer to add more in order to get to completion.

Just looking at the Wikipedia page is a daunting list.

Hope this info is of help.

**Comment by SonOfDiablo** [comment]
I do agree that this would probably fit better as a Feature Override Style as @the-j0k3r said.
And yes there is a quite a lot of extensions, but, there is also no need to reinvent the wheel.

Other people has worked on with the same "issue" on different platforms and so far the most comprehensive work I have stumbled upon is the [LS_COLORS](https://github.com/trapd00r/LS_COLORS) project by trapd00r and a whole lot of contributors.

The main branch has about 590 extensions neatly sorted and already color coded with [256 Xterm](https://jonasjacek.github.io/colors/) colors.
And the [motherofgod](https://github.com/trapd00r/LS_COLORS/blob/motherofgod) branch has a what seems like (at a quick glance) a few thousands, not neatly sorted, but all color coded.

I would be happy to give a swing at converting from one of these lists to CSS in the format that @xt0rted suggested, however I probably wouldn't be able to keep the list up to date (personal issues currently prevents me from any long term commitments such as that)

**Comment by the-j0k3r** [comment]
If you look at [this style](https://github.com/StylishThemes/Google-reCAPTCHA-Dark/blob/master/google-recaptcha-dark.user.css) you would be able to do something like

```css
/* ==UserStyle==
@name        GitHub Colored File Types
@namespace   StylishThemes
@version     1.0.0
@description A GitHub style with customizable file type colors
@author      StylishThemes and contributors
@homepageURL https://github.com/StylishThemes/Feature-Override-Styles/
@supportURL  https://github.com/StylishThemes/Feature-Override-Styles/issues
@license     CC-BY-SA-4.0

@var color    color-1                     "Text file" blue
@var color    color-2         "Programming languages" yellow
@var color    color-3  "Markup languages and formats" lime

@preprocessor stylus
==/UserStyle== */

@-moz-document domain("github.com") {
  /* text based colors */
 .files a[title="authors" i], .files a[title*="LIC" i] {
    color: color-1;
  }
  /* Programming languages and scripts */
  .files a[title$=".js" i] {
    color: color-2;
  }
  /* Markup languages and other web standards-based formats */
  .files a[title$=".md" i] {
    color: color-3;
  }
}
```

That follows the https://en.wikipedia.org/wiki/List_of_file_formats grouping them as documented with specific assign and customizable colors. This could be default xterm or any other suitable, because its customizable doesn't matter beyond what the designer decides.
