### ISSUE TITLE
Fill white for math SVG renders

### ISSUE THREAD

**Issue by quantumsheep** [StylishThemes/GitHub-Dark#1060]
It would be cool to have an adapted SVG filling for `https://render.githubusercontent.com/render/math`.

**url:** https://render.githubusercontent.com/render/math?math=e%5E%7Bi%20/pi%7D%20=%20-1
**current:** ![e^{i /pi} = -1](https://render.githubusercontent.com/render/math?math=e%5E%7Bi%20/pi%7D%20=%20-1)

**Comment by the-j0k3r** [comment]
This seems to work

```css
@-moz-document regexp("^https://(render)\.githubusercontent\.com\/render\/math\?.*$") {
  svg #surface1 g[style*="fill:rgb(0%,0%,0%)"] {
    fill: #eee !important
  }
}
```
Perhaps overkill

**Comment by silverwind** [comment]
Where do they appear?

**Comment by quantumsheep** [comment]
¯\\\_(ツ)\_/¯

When people wants to have mathematical expressions they use LaTeX and it seems to be a not well known feature.

**Comment by quantumsheep** [comment]
@the-j0k3r this seems less overkill, what do you think?

```sass
@-moz-document url-prefix("https://render.githubusercontent.com/render/math") {
  svg #surface1 g[style*="fill:rgb(0%,0%,0%)"] {
    fill: #eee !important
  }
}
```

**Comment by the-j0k3r** [comment]
> Also, I don't think that `[style*="fill:rgb(0%,0%,0%)"]` is really that useful there.

I wouldnt know if there are other variations in any case and not sure if this breaks something else, what do you think @silverwind?

**Comment by silverwind** [comment]
If it's only about the embedded images, I'd:

```css
img[src*="render.githubusercontent.com/render/math"] {
  filter: invert(90%);
}

**Comment by quantumsheep** [comment]
If we set the background then the images will also have a background (which we don't want).

The solution with `filter` seems very nice.

**Comment by silverwind** [comment]
I meant page background, like on raw files like https://raw.githubusercontent.com/StylishThemes/GitHub-Dark/master/.npmrc.

**Comment by quantumsheep** [comment]
I'm not sure to understand, there is no background in this once.

**Comment by the-j0k3r** [comment]
> I meant page background, like on raw files like https://raw.githubusercontent.com/StylishThemes/GitHub-Dark/master/.npmrc.

For https://render.githubusercontent.com/render/math?math=e%5E%7Bi%20/pi%7D%20=%20-1

```css
@-moz-document regexp("^https://(render)\.githubusercontent\.com\/render\/math\?.*$") {
  svg {
    background: #222;
  }
  svg #surface1 g[style*="fill:rgb(0%,0%,0%)"] {
    fill: #eee !important;
  }
}
```
 and then for main site we can do as as above

> ```css
> img[src*="//render.githubusercontent.com/render/math"] {
>   filter: invert(90%);
> }
> ```
