### ISSUE TITLE
Breaks Refined GitHub's `code` style

### ISSUE THREAD

**Issue by fregante** [StylishThemes/GitHub-Dark#1065]
* **Browser**: Firefox 73
* **Operating System**: macOS 10.15
* **Link to page with the issue**: This page
* **Screenshot**: 

## Initial

<img width="622" alt="initial" src="https://user-images.githubusercontent.com/1402241/74778320-44dc7900-52d6-11ea-8e50-1f0a39a1d195.png">

## Current

<img width="652" alt="broken" src="https://user-images.githubusercontent.com/1402241/74778277-2f674f00-52d6-11ea-8f03-8cb200f189a2.png">

## Expected

It should match this live style:

# Breaks Refined GitHub's `code` style

**Comment by silverwind** [comment]
Probably need to remove one of our custom styles, will check later.

**Comment by fregante** [comment]
My bad, actually GitHub Dark doesn't seem to override it; Refined GitHub has custom styles on that element _and_ GitHub Dark doesn't have custom "dark `<code>`" styles for it

**Comment by the-j0k3r** [comment]
Do you know what classes and properties/values these all are?

**Comment by fregante** [comment]
At that time I just copied GitHub’s CSS instead of using their classes because they were like with `.markdown-body code`

I don’t know if GitHub has a custom `.code` class that we can all use

**Comment by the-j0k3r** [comment]
I meant refined githubs classes for this.

**Comment by fregante** [comment]
```css
.rgh-parse-backticks {
    background-color: 
    rgba(27, 31, 35, 0.05);
    border-radius: 3px;
    font-size: 85%;
    margin: 0;
    padding: 0.2em 0.4em;
}
```
