### ISSUE TITLE
Sticky header backgrounds

### ISSUE THREAD

**Issue by h1nk** [StylishThemes/GitHub-Dark#1068]
Sticky header backgrounds are transparent instead of opaque, such as in PRs.

* **Browser**: Firefox
* **Operating System**: Linux
* **Link to page with the issue**: https://github.com/StylishThemes/GitHub-Dark/pull/959
* **Screenshot**:
![image](https://user-images.githubusercontent.com/12993584/74974823-daceeb80-541d-11ea-9b77-3e82c4172c9a.png)

**Comment by silverwind** [comment]
Can not reproduce. Try to update/reinstall.

**Comment by h1nk** [comment]
The issue was actually caused by GitHub-FixedHeader being used with this style (see related StylishThemes/GitHub-FixedHeader#16). Should I close this issue and reopen on there?

**Comment by xt0rted** [comment]
I just noticed this myself when the sticky header disappeared behind the sticky notification banner. Looks like github pushed a change out earlier that broke this. I'm not using the fixed header style, but I do have a custom one that functions similarly.

Not sure how similar the issues are between the styles but my fix was to add:

```css
body:not(.min-width-lg) .notification-shelf + .application-main .gh-header-sticky.is-stuck,
body:not(.min-width-lg) .notification-shelf + .application-main .gh-header-sticky.is-stuck + .gh-header-shadow {
  margin-top: var(--offset) !important;
}
```
