### ISSUE TITLE
GitHub Discussions (beta) answered box

### ISSUE THREAD

**Issue by zmni** [StylishThemes/GitHub-Dark#1071]
* **Browser**: 
Microsoft Edge (Chromium)

* **Operating System**: 
Windows

* **Link to page with the issue**: 
https://github.com/zeit/next.js/discussions/10116#discussioncomment-397

* **Screenshot**:
![gh](https://user-images.githubusercontent.com/841523/75091691-df70dc80-55a2-11ea-804d-506bffbd23fc.JPG)

**Comment by the-j0k3r** [comment]
```css
.timeline-comment.current-user.timeline-chosen-answer .timeline-comment-header, .timeline-comment.timeline-chosen-answer .timeline-comment-header {
	background-color: #f0fff4;
	border-bottom-color: #a2cbac;
}
```
