### ISSUE TITLE
Theme not applied on the incident follow-up button

### ISSUE THREAD

**Issue by 06Games** [StylishThemes/GitHub-Dark#1076]
The button to subscribe to updates regarding an incident appears white instead of grey.

* **Browser**: Firefox
* **Operating System**: Windows 10
* **Link to page with the issue**: https://www.githubstatus.com/incidents/q07bfjh7jf1t
* **Screenshots**:
![image](https://user-images.githubusercontent.com/24252743/75459418-9e504200-597f-11ea-9c07-bfb6fd18c93e.png)
![image](https://user-images.githubusercontent.com/24252743/75459965-24b95380-5981-11ea-8a86-27bda9386d74.png)

**Comment by silverwind** [comment]
That's not a button, just a link that is styled to look like one:

````html
<a id="btn-subscribe-modal-q07bfjh7jf1t" class="flat-button subscribe-button" data-toggle="modal" href="#subscribe-modal-q07bfjh7jf1t">Subscribe to Updates</a>
````

````css
.flat-button, .history-header .show-filter {
    padding: 6px 12px !important;
    font-size: 14px !important;
    line-height: 20px !important;
    vertical-align: middle !important;
    cursor: pointer !important;
    text-transform: none !important;
    background-color: #eff3f6 !important;
    background-image: linear-gradient(-180deg, #fafbfc 0%, #eff3f6 90%) !important;
    background-repeat: repeat-x !important;
    background-position: -1px -1px !important;
    background-size: 110% 110% !important;
    border: 1px solid rgba(27, 31, 35, 0.2) !important;
    border-radius: 0.25em !important;
    letter-spacing: 0 !important;
    color: #24292e !important;
    text-shadow: none !important;
    box-shadow: rgba(0, 0, 0, 0.15) 0px 0px 0px inset !important;
}
````
Should try to cover it in generator.
