### ISSUE TITLE
Error on line 1472

### ISSUE THREAD

**Issue by freefreeno** [StylishThemes/GitHub-Dark#1084]
On line 1472 there is an error.

Chromium
Arch Linux
chrome-extension://apmmpaebfobifelkijhaljbmpcgbjbdo/edit.html?id=1#

![Screenshot_20200309_165040](https://user-images.githubusercontent.com/41884680/76260702-68844680-6226-11ea-8931-1a89526c0169.png)

**Comment by silverwind** [comment]
That's a bug in GitHub's stylesheet. Does it break the style?

```css
.code-navigation-banner {
  background: linear-gradient(180deg,rgba(242,248,254,0),rgba(242,248,254,.47));
}

**Comment by silverwind** [comment]
It's coming from this. Pretty sure the actual bug is in the ZenHub CSS. But it may be possible to workaround in the generator.

``` css
  /* remap-css rule for "background-color: linear-gradient(-180deg, #fafbfc 0%, #eff3f6 90%)" */
  body.zh_logged_in .zh-webapp.zh-epic-creator-page-visible .btn {
    background-color: linear-gradient(-180deg, #202020 0%, #181818 90%);
  }
```

**Comment by freefreeno** [comment]
I don't really know if anything is broken. Was just letting you know.

**Comment by the-j0k3r** [comment]
Its a linting warning nothing serious.
Linting in Stylus is pretty much using their default rules,wheer we use a completely different set of rules.

Now you can Adjust the Stylus CSSlint and Styleint rules but that would apply for all styles not just or own.

Also what linting warning says to me the linter has no idea how to handle this given what it expects in that block.

Having said that, the warning disappears if we define background instead of background-color

```css
  /* remap-css rule for "background-color: linear-gradient(-180deg, #fafbfc 0%, #eff3f6 90%)" */
  body.zh_logged_in .zh-webapp.zh-epic-creator-page-visible .btn {
    background: linear-gradient(-180deg, #202020 0%, #181818 90%);
  }
```
