### ISSUE TITLE
Use CSS Variables/Properties instead of magic values

### ISSUE THREAD

**Issue by fregante** [StylishThemes/GitHub-Dark#1096]
There are 23 instances of `#202020` in the [file](https://stylishthemes.github.io/GitHub-Dark/github-dark.user.css). If GHD used variables, changing/customizing these values would be easier.

I'm trying to make it even darker (`#000`) but customizing the value forces me to copy huge selectors.

This for example would also allow #910

**Comment by the-j0k3r** [comment]
>This for example would also allow #910

Syntax themes are being totally reworked to a simpler format which reduces duplication. See https://github.com/StylishThemes/GitHub-Dark/issues/910#issuecomment-601035542

The new design will automatically allow all themes [here](https://github.com/StylishThemes/GitHub-Dark#available-syntax-highlighting-themes-demo) to work currently the design needs each theme to be constructed separately, while redesign you do only one set of colors, Even then we are talking 35 colors as it stands now. if you want to add a custom theme, 35 colors is a huge taxation on the config menu. I fail to see how allowing custom gray colors ontop will resolve anything here.

I dont think allowing a multitude of colors to be customizable is a practical solution in addition to the existing options,  + considering adding another https://github.com/StylishThemes/GitHub-Dark/issues/1094, you end up with huge menus, besides syntax themes are a special feature of GHD that is quite complex with 3 different syntax themes for codemiirror, Github, jupyter.

>There are 23 instances of #202020 in the file. If GHD used variables, changing/customizing these values would be easier.

GHD is a complex theme, using generators for instance https://github.com/StylishThemes/GitHub-Dark/blob/ea8443d0e06294b5701bac1775e7e9bc97b4b5e6/tools/generate.js#L21-L23 will exactly chnage this https://github.com/StylishThemes/GitHub-Dark/blob/ea8443d0e06294b5701bac1775e7e9bc97b4b5e6/github-dark.css#L644-L884

So taking the syntax themes aside, what new config colors are you exactly proposing?

**Comment by fregante** [comment]
I never talked about options/UI. 

Currently I'm overriding the whole selectors in my extra userstyle for GitHub. If GHD used variables I could just set:

```css
:root {
	--level-0: #000;
	--level-1: #050505;
}
```

**Comment by fregante** [comment]
I mean, even the Code colors as they are configured now shouldn't be part of the stylesheet anyway, given the complexity they bring. They could just be additional stylesheets.

**Comment by the-j0k3r** [comment]
Yea we could use root values but separate stylesheets are used already as such we use different moz-doc sections.

The generator doesnt know about these diff moz-doc sections and doesnt egenerate CSS to these areas, and until it does, your design suggestion wont very well work.

I dont even know if the generator supports root values as is.

**Comment by fregante** [comment]
> separate style to override the current rules.

Or if if `var()` was used everywhere, just a _separate style to override the current **variables**_ rather than whole rules.

**Comment by the-j0k3r** [comment]
We cant have separate stylesheets, only @-moz-document sections.

And again IDK if the generator supports `var()`, for the sake of a darker style you can use this.


```css
/* ==UserStyle==
@name         GitHub Prefer Color Scheme
@namespace    StylishThemes
@version      0.0.2
@description  Supports 
@author       StylishThemes
@homepageURL  https://github.com/StylishThemes/Feature-Override-Styles/
@supportURL   https://github.com/StylishThemes/Feature-Override-Styles/issues/new/choose
@updateURL    https://raw.githubusercontent.com/StylishThemes/Feature-Override-Styles/master/dark-mode-for-github.user.css
@license      CC-BY-SA-4.0

@var select media-query "Require system appearance" [
	"None",
	"Dark",
	"Light"
]
@var color darkC  "Dark background color"  #111
@var color lightC "Light background color" #eee
@preprocessor stylus
==/UserStyle== */
@-moz-document regexp("^https?://((education|gist|guides|help|lab|raw|resources|status|developer|support)\\.)?github\\.com/((?!generated_pages/preview).)*$"), domain("githubusercontent.com"), domain("graphql-explorer.githubapp.com"), domain("www.githubstatus.com") {
	if media-query == "None" {
		@media (prefers-color-scheme: no-preference) {
			html body, html .bg-white,
			html body .selected.reponav-item {
				background-color: inherit !important;
			}
		}
	}
	else if media-query == "Dark" {
		@media (prefers-color-scheme: dark) {
			html body, html .bg-white,
			html body .selected.reponav-item {
				background-color: darkC !important
			}
		}
	}
	else if media-query == "Light" {
		@media (prefers-color-scheme: dark) {
			html body, html .bg-white,
			body.selected.reponav-item {
					background-color: lightC !important
			}
		}
	}
}
```

Thats some thing I wrote and testing for resolving https://github.com/StylishThemes/GitHub-Dark/issues/960

But at this time its not fully ready it seem to be slightly buggy, though it will darken this style to whatever colors you set.

Also a smaller style can be done to overwrite what you want, I dont have anyhing ready and cant promise Ill make one, but you get the idea, its faster than waiting for a change you want is probably more work than its worth imo at this time.
