### ISSUE TITLE
Clone Button Background

### ISSUE THREAD

**Issue by iamrameffort** [StylishThemes/GitHub-Dark#1099]
After today's update, the border and background colors of the buttons to clone the repository have become lighter.

* **Screenshot**:

![Screenshoot](https://user-images.githubusercontent.com/52138516/79795776-d2fecb00-832a-11ea-9105-a5cfad45e3ee.png)

**Comment by silverwind** [comment]
May be fixed in v2.0.51, please try a update.

**Comment by xt0rted** [comment]
@silverwind this was fixed, but there's still a minor style issue with the ssh option when it's not selected.

![image](https://user-images.githubusercontent.com/831974/80057669-1efd6b80-84f5-11ea-8af1-e218f7c62ea9.png)

The white line is coming from the rule:

```css
.clone-url-button+.clone-url-button>.clone-url-link {
  box-shadow: inset 1px 0 0 #fff;
}
```
