### ISSUE TITLE
GitHub Gist search input double border

### ISSUE THREAD

**Issue by zmni** [StylishThemes/GitHub-Dark#1121]
* **Browser**: `Edge`
* **Operating System**: `Windows 10`
* **Link to page with the issue**: `https://gist.github.com`
* **Screenshot**:
![gist github com](https://user-images.githubusercontent.com/841523/84346578-82914480-abda-11ea-919c-dae08a8ab082.png)

**Comment by silverwind** [comment]
Also present with the style disabled, so it's a GitHub bug.

**Comment by zmni** [comment]
Oh, I didn't check that. Should I close this?

**Comment by the-j0k3r** [comment]
Heres something Im currently using, not published per say.

Option on to address this, not sure if it will break something else, includes other fixes Im using.

```css
/* ==UserStyle==
@name           GitHub Dark Upstream Bug Fix
@namespace      github.com/openstyles/stylus
@version        1.0.0
@description    A new userstyle
@author         Me

@preprocessor stylus

@var checkbox fixrebasebtnborder  "PR rebase button border" 1
@var checkbox fixresetfilteralign "Reset filter align" 1
@var checkbox fixfiltericonalign  "Filter icon x align" 1
@var checkbox fixgistsearch       "Fix Gist Search border" 1
@var color greenC "Green color"   "#170"
@var color whiteC "White color"   "#fff"

@var color secondBackground "Custom second background" "#242730"
@var color hoverBackground "Custom hover background" "#4e5467"

==/UserStyle== */
@-moz-document regexp("^https?://((gist|guides|help|lab|launch-editor|raw|resources|status|developer|support)\.)?github\.com/((?!generated_pages/preview).)*$"), domain("githubusercontent.com"), domain("graphql-explorer.githubapp.com"), domain("www.githubstatus.com") {
	/*
	 * upstream bug: Fix pr rebase button border on hover.
	 * URL: https://github.com/StylishThemes/GitHub-Dark/issues/1070
  */
	if fixrebasebtnborder {
		.btn-group-rebase.border-right-0:hover {
			border-right: 1px solid currentcolor !important;
		}
		.btn.btn-group-rebase.border-right-0:hover {
			border-right: 1px solid #484848 !important;
		}
		.branch-action-state-dirty .btn.btn-group-rebase.border-right-0:hover {
			border-right: 1px solid #363636 !important;
		}
	}
	if fixresetfilteralign {
		/*
	 * upstream bug: Fix filter reset button in notificationsv2b vertical alignment within input.
	 * e.g. URL: https://github.com/notifications/beta?query=is%3Aunread
  */
		button .issues-reset-query-icon {
			vertical-align: top;
		}
	}
	/* https://github.com/marketplace?type=apps&verification=verified */
	if fixfiltericonalign {
		.filter-item.selected .octicon-x {
			margin-top: 2px;
		}
	}
	/* https://github.com/StylishThemes/GitHub-Dark/issues/1121 */
	if fixgistsearch {
		.header-search-wrapper .form-control, .header-search-wrapper .form-select {
			border: 0;
		}
	}
}
```
