### ISSUE TITLE
Feature preview: New design update - Issues

### ISSUE THREAD

**Issue by Anish-Shobith** [StylishThemes/GitHub-Dark#1123]
**Maintainer update:** We're unable to support the ui preview. It's recommended you either turn it off or see https://github.com/StylishThemes/GitHub-Dark/issues/1123#issuecomment-646759368 for a temporary style that fixes these issues.

---

* **Browser**: Brave Browser (v 1.9.72 Chromium: 81.0.4044.138 (Official Build) (64-bit))
* **Operating System**: Ubuntu 18.04.4 LTS x86_648	
![image](https://user-images.githubusercontent.com/38991749/84569670-1400e200-ada6-11ea-9c48-ea8aa3057ecd.png)
* **Link to page with the issue**: Settings tab of the repo. As you notice that the settings tab where the settings not visible at the left side of the page in the below screenshot.

* **Stylus settings**:
![image](https://user-images.githubusercontent.com/38991749/84569903-70183600-ada7-11ea-9f13-4ae609414b96.png)

* **Steps to reproduce the issue**:
 - Enable Design updates from the user settings feature previews tab.
![image](https://user-images.githubusercontent.com/38991749/84569840-f84a0b80-ada6-11ea-9f9c-39d0465382ce.png)
![image](https://user-images.githubusercontent.com/38991749/84569802-b91bba80-ada6-11ea-8098-939e4ed84b57.png)
- Now go to settings tab of the repo you should be able to see that the writing is in black which was not the case when **Design updates** is disabled. (Screenshot below)

* **Screenshots**:
 - **Design Updates enabled**:
![image](https://user-images.githubusercontent.com/38991749/84569699-37c42800-ada6-11ea-9b0f-88bfb9e45d61.png)
 - **Design Updates disabled**:
![image](https://user-images.githubusercontent.com/38991749/84569861-2b8c9a80-ada7-11ea-8ad0-19118b37e09a.png)

Note: This feature might not be available for everyone yet. 

Wish I have given enough information. If not please mention me.

**Comment by silverwind** [comment]
It's not offering me this feature preview unfortunately.

**Comment by Anish-Shobith** [comment]
Addition: This issue is also noticeable in while searching. 
![image](https://user-images.githubusercontent.com/38991749/84598886-8697bd80-ae8b-11ea-8747-8be2150c23dd.png)
![image](https://user-images.githubusercontent.com/38991749/84598889-90212580-ae8b-11ea-881d-0e9d258b462f.png)
 

> It's not offering me this feature preview unfortunately.

Yeah, its not yet available for everyone yet! I got is like a day back or something, few others who I know got it a week back before I did. I guess they are releasing it slowly :man_shrugging:

**Comment by silverwind** [comment]
If the CSS for this feature is on a static URL or a page that contains a `<link>` to that CSS, we can add it, otherwise not (would require way too much work).

**Comment by the-j0k3r** [comment]
> It's not offering me this feature preview unfortunately.

This is always an issue here as well, Ive mentioned this to @github their reply was that they would eventually roll out all preview to other users, however I found that this takes a very very long time for some of these.

How can we support preview features if none of the devs can access those features?

The answer would be some new contributor who has access to this can help out and submit a pull request =) We can help with that process.

**Comment by scote** [comment]
I also found that the upper border of black button are larger if we compare witht light design.
![image](https://user-images.githubusercontent.com/2046218/84647900-1c563b80-aed2-11ea-82d5-c937c951b3e0.png)

Without dark theme :
![image](https://user-images.githubusercontent.com/2046218/84647962-35f78300-aed2-11ea-8566-48591c028ffa.png)

**Comment by vednoc** [comment]
> If the CSS for this feature is on a static URL or a page with a static URL that contains a `<link>` to that CSS, we can add it, otherwise not (would require way too much work).

@silverwind @the-j0k3r I got this update just now; here are the links to stylesheets:
- [github-next][0]
- [frameworks-next][1]

> The answer would be some new contributor who has access to this can help out and submit a pull request =) We can help with that process.

LMK if/how I can help!


[0]: https://github.githubassets.com/assets/github-next-0b42239512c4549c82a8b0f38fbc5005.css
[1]: https://github.githubassets.com/assets/frameworks-next-9d63abce17fa4974fca97bb7835823b6.css

**Comment by Stanzilla** [comment]
Yeah preview has been unlocked for everyone today, see https://twitter.com/broccolini/status/1273374719249657857

**Comment by xt0rted** [comment]
Since they're using different stylesheets for the new UI I don't think we can support this without producing two different versions of GHD.

**Comment by heyitspuggo** [comment]
Hyped for the new stylesheet. For now, I've noticed they're using `box-shadow`s a lot... especially in the buttons. I think those shadows and the pure "white lines" appearing in certain areas of the UI are all that need to be fixed, here

**Comment by RomanKornev** [comment]
This seems to fix majority of the button shadow issues:
``` css
.social-count, .btn, .form-control, .form-select, .btn.selected, .btn:active, .btn[aria-selected=true] {
    box-shadow: none;
}
```
This fixes the white line at the top:
``` css
.UnderlineNav {
    box-shadow: none;
    border-bottom: solid 1px #343434;
}
```

**Comment by the-j0k3r** [comment]
> Since they're using different stylesheets for the new UI I don't think we can support this without producing two different versions of GHD.

Yea this is a problem

this are uses

```css
.menu-item {
	position: relative;
	display: block;
	padding: 8px 16px;
	color: #1b1f23;
	border-bottom: 1px solid #eaecef;
}
```

`color: #1b1f23` already exists on our generator at https://github.com/StylishThemes/GitHub-Dark/blob/8d55776aab794a1759129ef85b53bb2755dde158/tools/generate.js#L174

The location of the stylesheet is at https://github.githubassets.com/assets/frameworks-next-7bd6994d0775e97855e1b6f75967d9b3.css

**Comment by the-j0k3r** [comment]
I dislike 100% of the new design update, GitHub adopted the trend of rounded everything. Every design elements that made the UI great are gone.

Here come the revert styles.

**Comment by xt0rted** [comment]
- `frameworks.css` very high level styles such as `normalize.css` and the core rules from primer
- `github.css`: the rest of primer/octicons and all of the product styles
- `site.css`: marketing rules

All three of those have 'classic' and 'next' variants now (`gist.css` doesn't have a 'next' version yet). I don't think it's worth putting effort into trying to support the `next` versions. A separate style to fix some of these issues would work best since there's no way to include the rules in the main style and only have them apply if the preview is enabled. In the past we've littered the style with rules for previews and rarely go back and remove them. I'm in favor of a secondary style such as `github-dark-ui-preview.user.css` and then we pin an issue about it to help reduce the number of new issues created.

I'm using the following to fix the issues I've come across:

```css
.repohead.bg-gray-light,
.UnderlineNav {
  /* this is #202020 but overridden to #000 by my github black style */
  background-color: var(--ghb-bg-color) !important;
}

.UnderlineNav {
  box-shadow: inset 0 -1px 0 #343434 !important;
}

.menu-item, /* the left menu on the settings pages */
.flash .octicon /* icon in the marketplace alert: https://github.com/actions/checkout */ {
  color: unset !important;
}

.btn {
  box-shadow: 0 1px 0 rgba(200, 200, 200, .04), inset 0 1px 0 hsla(0, 0%, 100%, .25);
}

.form-control, .form-select {
  /* not really visible with our colors, probably needs further adjustment */
  box-shadow: inset 0 1px 0 rgba(64, 64, 64, .2);
}
```
