### ISSUE TITLE
Contributions graph legend isn't styled

### ISSUE THREAD

**Issue by xt0rted** [StylishThemes/GitHub-Dark#1141]
* **Browser**: chrome 83
* **Operating System**: win10
* **Link to page with the issue**: https://github.com/xt0rted
* **Screenshot**:

![image](https://user-images.githubusercontent.com/831974/85437647-ef9cc680-b558-11ea-93c3-74d09c39afd7.png)

**Comment by silverwind** [comment]
Need to put those colors in the generator and remove manual rules.

**Comment by the-j0k3r** [comment]
fixed by adding .legend to our manual styles,

```css
  /* contribution calendar */
  .calendar-graph rect[fill="#c6e48b"], .calendar-graph rect[fill="#7bc96f"],
  .calendar-graph rect[fill="#239a3b"], .calendar-graph rect[fill="#196127"],
  .contrib-legend .legend li[style],
  .contribution-activity-listing .progress-bar[style*="background-color"] {
    background-color: /*[[base-color]]*/ !important;
    fill: /*[[base-color]]*/ !important;
  }
  .calendar-graph .days-selected rect.day.active {
    stroke: #ddd !important;
  }
  .calendar-graph rect.day:hover {
    stroke: #fff !important;
  }
  /* contribution progress bars on user page */
  .contribution-activity-listing .progress-bar[style*="7bc96f"],
  .facebox-close:hover {
    opacity: 1 !important;
  }
  .contribution-activity-listing .progress-bar[style*="c6e48b"], .facebox-close {
    opacity: .75 !important;
  }
  .notifications .read .avatar img {
    opacity: .7;
  }
  /* contribution calendar/legend - regular colors */
  .calendar-graph rect[fill="#ebedf0"], .contrib-legend .legend li[style*="#ebedf0"],
  .js-activity-overview-graph-container [fill="white"] {
    background-color: #222 !important;
    fill: #222 !important;
  }
  .calendar-graph rect[fill="#196127"], .contrib-legend .legend li[style*="#196127"] {
    opacity: 1 !important;
  }
  .calendar-graph rect[fill="#239a3b"], .contrib-legend .legend li[style*="#239a3b"] {
    opacity: .75 !important;
  }
  .calendar-graph rect[fill="#7bc96f"], .contrib-legend .legend li[style*="#7bc96f"] {
    opacity: .5 !important;
  }
  .calendar-graph rect[fill="#c6e48b"], .contrib-legend .legend li[style*="#c6e48b"] {
    opacity: .25 !important;
  }
```

I dont see how this custom stuff can be simply inserted into generator, most is inline HTML which parts concerns us here as well as others.

![generic](https://user-images.githubusercontent.com/31389848/85570692-dae13100-b633-11ea-9f73-3cc93637e3d3.gif)
