### ISSUE TITLE
Header nav on profile pages has partial background

### ISSUE THREAD

**Issue by xt0rted** [StylishThemes/GitHub-Dark#1142]
* **Browser**: chrome 83
* **Operating System**: win10
* **Link to page with the issue**: https://github.com/xt0rted
* **Screenshot**:

![image](https://user-images.githubusercontent.com/831974/85438654-2e7f4c00-b55a-11ea-8092-bf47062debd5.png)

This nav style is also used on the explore pages but it uses slightly different classes so it doesn't have the top margin that causes the page bg to show through. I tried to fix this by setting the background to `transparent` but that doesn't work because the header is sticky and the page shows through as you scroll.

The way I was working around this is with the following hack:

```css
.application-main > main > .bg-white.position-sticky.mt-4::after {
  content: "";
  background-color: #181818;
  position: absolute;
  top: -24px; /* Need to account for the .mt-4 class */
  right: 0;
  bottom: 0;
  left: 0;
  z-index: -1;
}
```
