### ISSUE TITLE
.notification-indicator .mail-status no longer styled

### ISSUE THREAD

**Issue by the-j0k3r** [StylishThemes/GitHub-Dark#1149]
* **Browser**:  77.0.1 (64-bit)
* **Operating System** Win 10 1903: 
* **Link to page with the issue**:  Any with notification unread
* **Screenshot**:

![Capture](https://user-images.githubusercontent.com/31389848/85829187-5e149b00-b78a-11ea-9e8c-c2594b74a5ac.PNG)

default css
```css
.notification-indicator .mail-status {
	position: absolute;
	top: -6px;
	left: 6px;
	z-index: 2;
	display: none;
	width: 14px;
	height: 14px;
	color: #fff;
	background-image: linear-gradient(#54a3ff,#006eed);
	background-clip: padding-box;
	border: 2px solid #24292e;
	border-radius: 50%;
}
```
This `background-image: linear-gradient(#54a3ff,#006eed);` is part of generator:

https://github.com/StylishThemes/GitHub-Dark/blob/0ce10179e593f7a11be8212f299e91fb2442a195/tools/generate.js#L294

probably remap-css related
