### ISSUE TITLE
button primary green/gray color + disabled + selected states

### ISSUE THREAD

**Issue by the-j0k3r** [StylishThemes/GitHub-Dark#1154]
* **Browser**: FF 77.0.1 (64-bit)
* **Operating System**:  Windows 10 pro
* **Link to page with the issue**:  ANy with green /gray buttons
* **Screenshot**:

# Issue 1 green buttons color

The green buttons are now too bright way off the balance between green/red yellow
The OPEN state color is aberrantly off the right bg color.

```css
State--green {
    background-color: #595;
```

this use to be set at same color as green buttons its now WAY OFF as well as being excessively bright.

![Screenshot_2020-06-28-Focus-outline-isn't-fully-styled-·-Issue-#1129-·-StylishThemes-GitHub-Dark](https://user-images.githubusercontent.com/31389848/85941826-9dc3ba00-b925-11ea-9750-39c3f1692356.png)

# Issue 2 disabled green button colors

The button doesnt look disabled AT ALL.

![Capture](https://user-images.githubusercontent.com/31389848/85941447-605e2d00-b923-11ea-9e09-bc5de582e12a.PNG)

It use to be fine before moving to `$color`

# Issue 3 - Some gray buttons selected is too bright 

Ever since buttons were moved to generator these are now a unsightly `#404040` this breaks some buttons right box shadow (which is makeshift border) like the all button in notifications.

![generic](https://user-images.githubusercontent.com/31389848/85941706-a9fb4780-b924-11ea-8143-9746a13364b6.gif)

Overall buttons are in a very unfortunate state since being moved to generator

TBH personally I will just do my own buttons style, so I can choose colors that suit my taste and screen quality.

**Comment by silverwind** [comment]
Thing with these greens are is that the issue icons use the same color

![image](https://user-images.githubusercontent.com/115237/85941862-d5cafd00-b925-11ea-8f6b-12a2574320ea.png)

They need to be bright for sufficient contrast there but on the other hand we're used to them being darker on the "open" labels.

**Comment by the-j0k3r** [comment]
When redid the green buttons I fixed all of this, they were all balanced and OK, now not even close.

**Comment by the-j0k3r** [comment]
Another broken button this time blue

https://help.github.com/en/github/administering-a-repository/managing-releases-in-a-repository

![generic](https://user-images.githubusercontent.com/31389848/85942127-ad440280-b927-11ea-8869-f492a8819b98.gif)

**Comment by the-j0k3r** [comment]
@silverwind this https://github.com/StylishThemes/GitHub-Dark/commit/c7be5d9318e8c85986102e90e5816d3f1b0fd703

so using $color and background for same areas is causing some issues, I managed to get the button fixed but thik the generator is overly compkicating these things that should be straight forward and simple.

**Comment by silverwind** [comment]
There's a lot such cases where it's not clear whether base-color or blue is needed. I think I will just drop the color option at some point, it's more trouble than it's worth having.

**Comment by the-j0k3r** [comment]
You want to remove color customization and I think we need to add at least one more.

removing user customization options is not any kind of solution to me.

In your scenario any user wanting to customize would would have to spend time instead of just clicking something.

**Comment by LunarTwilight** [comment]
hope I'm not interrupting anything, but I've found that using `grey` works pretty well as a disabled button background color
![image](https://user-images.githubusercontent.com/13520392/86434772-c55ead80-bcaa-11ea-8ae7-79e479d20431.png)

**Comment by the-j0k3r** [comment]
@LunarTwilight I dislike such overly bright colors personally, but Im working on a style for buttons only that you will be able to use whatever colors you like better within a restricted set of colors/shades/brightness

**Comment by the-j0k3r** [comment]
@silverwind 

I can track issue 2 to $color also.

FYI Im never going to fix this in this style until $color is fixed, Ive made my own button style for prsonal use for time being.

RIP

**Comment by the-j0k3r** [comment]
ISSUE 4

![Capture](https://user-images.githubusercontent.com/31389848/86571550-e3a9ff00-bf71-11ea-89b2-5b7142fc53f9.PNG)

green colors no longer match in several sections https://github.com/StylishThemes/GitHub-Dark/issues/1154#issuecomment-650714048 for one

![Capture](https://user-images.githubusercontent.com/31389848/86571724-2e2b7b80-bf72-11ea-879a-126a836bd5ae.PNG)

the open button is 

```css
.State--green {
	background-color: #484;
}
```
the new issue button is 

```css
.btn-primary {
	background-color: #373;
	border-color: rgba(220, 220, 220, .15);
	box-shadow: none;
}
```

These USE to match before they were moved to generator and before `$color` Everything was green enough, matched and worked, now, yea mess.

**Comment by the-j0k3r** [comment]
> There's a lot such cases where it's not clear whether base-color or blue is needed. I think I will just drop the color option at some point, it's more trouble than it's worth having and we have more freedom in styling if we can assume blue base color.

@silverwind feel free to drop background and color customization. I have an addon style nearly ready that will add it back.

**Comment by silverwind** [comment]
I plan to move everything to CSS vars so it'd be quite trivial to override those in additional styles.

Do we need to keep this issue open? I think green button issues are all resolved except maybe some minor color adjustments.

**Comment by the-j0k3r** [comment]
The gray buttons selected and others need to be less bright as reported, however lately the whole style looks completely alien gray/dark gray colors wise, its seems to be your preference, in that case close or do what you feel.


> I plan to move everything to CSS vars so it'd be quite trivial to override those in additional styles.

this would be ideal, but the massive color palette is way too much to handle in any override style, especially if you want to customize colors.

But it would work for preset colors.

Either way css vars are much wanted for allowing customization externally without using any rules. So said style would be trivial

**Comment by silverwind** [comment]
Probably not going to do everything but shades of grey and base color are good candidates for variables.

**Comment by the-j0k3r** [comment]
Anything thats not covered by body bg color would also be nice :)

**Comment by xt0rted** [comment]
If all of the colors were moved to variables we could set defaults for them and then use a secondary style like `GitHub Dark Settings` or something to let users set them to whatever they want, that way this style's config isn't crowded with them all.

![image](https://user-images.githubusercontent.com/831974/88469409-6f52e380-cebf-11ea-9dbb-9d35a5814778.png)

```css
/* ==UserStyle==
@name           GitHub Dark Settings
@namespace      github.com/openstyles/stylus
@version        1.0.0
@description    A new userstyle
@author         Me
@preprocessor default
@advanced color ghd-bg-color "Background Color" #202020
==/UserStyle== */

@-moz-document domain("github.com") {
  body {
    /* Required for Stylus to load the style */
  }
}
```

**Comment by the-j0k3r** [comment]
> If all of the colors were moved to variables we could set defaults for them and then use a secondary style like `GitHub Dark Settings` or something to let users set them to whatever they want, that way this style's config isn't crowded with them all.

Im working on something a great deal more advanced than this, Stay tuned to this channel

**Comment by silverwind** [comment]
@xt0rted I was thinking more of something like this:

```css
/* ==UserStyle==
@name         Example UserCSS style
@namespace    github.com/openstyles/stylus
@version      1.0.2
@license      unlicense
@preprocessor uso
@var color ghd-bg-color "Background Color" #f1a
==/UserStyle== */
@-moz-document domain("github.com") {
  :root {
    --ghd-bg-color: /*[[ghd-bg-color]]*/ !important;
  }
}

**Comment by the-j0k3r** [comment]
ugh

**Comment by xt0rted** [comment]
@silverwind does the style name dictate ordering? In my testing I needed to prefix override styles with `GitHub Dark` to avoid `!important` and to get the right cascading.

**Comment by the-j0k3r** [comment]
IDk what you guys are trying to do here.

```css
/* ==UserStyle==
@name         Example UserCSS style
@namespace    github.com/openstyles/stylus
@version      1.0.0
@license      unlicense
@preprocessor uso
@var color ghd-bg-color "Background Color" #f1a
@preprocessor stylus
==/UserStyle== */
@-moz-document @-moz-document domain("github.com") {

  /* hack to show style in popup no matter what */
  stylus-fix { content: 'true' }

  i = !important

  :root {
    --ghd-bg-color: ghd-bg-color;
    }
  }
}
```

**Comment by silverwind** [comment]
According to [this](https://github.com/openstyles/stylus/issues/205#issuecomment-334901891) installation order is used.

**Comment by the-j0k3r** [comment]
Why dont you guys have a look at an old POC version of what Im currently working on?

See https://github.com/StylishThemes/GitHub-Dark/issues/1113#issuecomment-658075241

If youre creating an override style, then I guess my work is nullified by that, though I will publish it then elsewhere.

**Comment by silverwind** [comment]
I guess all preprocessors besides `default` should work because they give you control over `!important`.

**Comment by the-j0k3r** [comment]
Theres no point more than one person working on overrides styles for this. But if you hack with important it will cause my style issues with overrides. We break all CSS cascades with misusing important

**Comment by silverwind** [comment]
If I understand correctly, your example should be affected too by that loading order issue if it sets the same css var without important. You could also workaround by using a strong selector, e.g. `:root:root`.

**Comment by xt0rted** [comment]
I'm not working on anything. I was only suggesting a way to offer color selection if GHD was updated with css variables without filling the settlings list with ones that most people wouldn't use. In fact, I haven't even been using this style lately so it doesn't really matter to me how this gets done.

**Comment by silverwind** [comment]
I'm also not intending to create any more override styles. I just want to faciliate customization from GHD's side.

**Comment by the-j0k3r** [comment]
CSS vars are the only help a override style needs

**Comment by the-j0k3r** [comment]
```css
/* ==UserStyle==
@name         Example UserCSS style
@namespace    github.com/openstyles/stylus
@version      1.0.0
@license      unlicense
@preprocessor stylus

@var color ghdbgColor "Background Color" #f1a
@var color mainColor  "Main color"    #5e8acc

@preprocessor stylus
==/UserStyle== */
@-moz-document regexp("^https?://((education|gist|graphql|guides|docs|raw|resources|status|developer|support|vscode-auth)\\.)?github\\.com/((?!generated_pages/preview).)*$"), domain("githubusercontent.com"), domain("www.githubstatus.com"), domain("stylishthemes.github.io") {

  :root {
    --ghd-bg-color: ghdbgColor;
    --custom-thumb-color: mainColor;
    --webkit-scrollbar-thumb-hover: rgba(mainColor, .8);
    --base-color: mainColor;
  }
}
```

this works just fine for e.g as a POC you not only control base color but you control bg and so story goes
