### ISSUE TITLE
box-shadow-extra-large way too bright.

### ISSUE THREAD

**Issue by the-j0k3r** [StylishThemes/GitHub-Dark#1155]
* **Browser**:  FF  77.0.1 (64-bit)
* **Operating System**: Win 10 pro
* **Link to page with the issue**:  https://github.com/marketplace at least
* **Screenshot**:

![Capture](https://user-images.githubusercontent.com/31389848/85942312-b8e3f900-b928-11ea-8448-2191431535d6.PNG)

![Capture](https://user-images.githubusercontent.com/31389848/85942260-820de300-b928-11ea-8019-0dfb154c76e2.PNG)

think this is the default css

```css
.box-shadow-extra-large {
    box-shadow: 0 12px 48px rgba(149,157,165,.3) !important;
}
```
