### ISSUE TITLE
Orange background for one element in the code view

### ISSUE THREAD

**Issue by LingMan** [StylishThemes/GitHub-Dark#1156]
The word `proc` has an orange background when themed.

* **Browser**: Firefox 77.0.1
* **Operating System**: Manjaro Linux
* **Link to page with the issue**: https://github.com/gfx-rs/naga/blob/713fcaaa119d2e538c539e9ccf06698e03f067a6/tests/convert.rs#L20
* **Screenshot**:
![Screenshot from 2020-06-28 18-33-45](https://user-images.githubusercontent.com/18645382/85953182-d1770200-b96e-11ea-8d1a-937786877872.png)

**Comment by the-j0k3r** [comment]
this is the `.pl-bu`

```css
.pl-bu, .pl-ii, .pl-ii .pl-cce {
	background-color: #df5000 !important;
	color: #fff !important;
}
```

So what exactly is the problem?
