### ISSUE TITLE
Readme box header is missing left/right borders

### ISSUE THREAD

**Issue by xt0rted** [StylishThemes/GitHub-Dark#1157]
* **Browser**: chrome 83
* **Operating System**: win10
* **Link to page with the issue**: https://github.com/StylishThemes/GitHub-Dark
* **Screenshot**:

![image](https://user-images.githubusercontent.com/831974/85967957-a94cca80-b991-11ea-9930-9458ff30cc8e.png)

From what I can tell this is coming from the following rule:

```css
/* github.com: "0", "0" */
.Box--responsive .Box-header {
  border-left-width: 0;
  border-right-width: 0;
}
```
