### ISSUE TITLE
doc pages (almost) invisible radio checked

### ISSUE THREAD

**Issue by the-j0k3r** [StylishThemes/GitHub-Dark#1163]
* **Browser**:  FF 78.0.1 (64-bit)
* **Operating System**: win 10 pro
* **Link to page with the issue**: any doc page with content e.g. https://docs.github.com/en/packages
* **Screenshot**:

![generic](https://user-images.githubusercontent.com/31389848/86509453-5c7d4f80-bde8-11ea-9b43-006d0d9ffbd9.gif)

As you can see when zoomed in there is something in background.

We already have a radio checkbox styling in style  but to reach this are it needs changing, but any changes will break working radio checkboxes elsewhere.

https://github.com/StylishThemes/GitHub-Dark/blob/161d652e8feed789bb557e45968d343ce66d4d0b/github-dark.css#L24127-L24130

I managed to fix this locally by adding a specific fix for `@-moz-document domain("docs.github.com")`

```css
  .helpfulness input[type="radio"]:checked {
    background: #ddd url('data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><rect width="512" height="512" fill="%23000"/><circle cx="256" cy="256" r="96" fill="%23ddd"/></svg>') !important;
		border: 4px solid #444 !important;
  }
```

However this is no where near the correct thing and looks slightly off
