### ISSUE TITLE
demo page missing styles

### ISSUE THREAD

**Issue by olets** [StylishThemes/GitHub-Dark#1180]
Removing the individual minified stylesheets (looks like 03e86bf0d4a1227bd13a6931deb7ffd1240f9f88 — haven't dug to see if there was more to it) means they aren't available on the demo page.

* **Browser**: n/a
* **Operating System**:  n/a
* **Link to page with the issue**: https://stylishthemes.github.io/GitHub-Dark/
* **Screenshot**:
![image](https://user-images.githubusercontent.com/3282350/87553477-f6fb4f80-c680-11ea-808b-d682a1680364.png)

**Comment by the-j0k3r** [comment]
I dont think that commit is related, the index.html has this
```css
.cm-s-github.CodeMirror{font-family:Consolas, "Liberation Mono", Menlo, Courier, monospace;font-size:12px;line-height:18px;background:#fff}
```
