### ISSUE TITLE
border color issues caused by $color generated properties that conflict in some rules.

### ISSUE THREAD

**Issue by the-j0k3r** [StylishThemes/GitHub-Dark#1185]
* **Browser**: 
* **Operating System**: 
* **Link to page with the issue**:  https://github.com/settings/admin change nick or any issue and cloick lock conversation.
* **Screenshot**:

![Capture](https://user-images.githubusercontent.com/31389848/87860076-bc244080-c93a-11ea-9a9c-89f33eae4b61.PNG)

https://github.com/StylishThemes/GitHub-Dark/blob/050753c82078826d560f347d18fdf7827eb31000/src/gen/mappings.js#L33 is the guilty rule

its generating a bright border for  .Box--overlay this bright VALUE is OK for some other rules but NOT this ones border.

```css
  /* github-mobile: "#fff", "#444d56", "rgba(0,0,0,.4)" */
  body[class="page-responsive"] .Box--overlay {
    background-color: #151515;
    border-color: #afafaf;
    box-shadow: 0 0 18px #000;
  }
```

@silverwind Im out of ideas, $color is more trouble than its worth IMO. Unless its A LOT smarter
