### ISSUE TITLE
Contributions calendar do not need svg selector

### ISSUE THREAD

**Issue by s890081tonyhsu** [StylishThemes/GitHub-Dark#119]
![bug](https://f.cloud.github.com/assets/3825000/2257270/5cdb0a10-9e16-11e3-8809-ecc3748716af.png)
I don't know that the bug is just for me.
So I change the code to the following and fix this.
(I deleted "svg|" before "rect". )
```css
#contributions-calendar rect[style="fill: rgb(238, 238, 238);"],
#contributions-calendar rect[style="fill: #eeeeee;"] { fill: #282828 !important }
#contributions-calendar rect[style="fill: rgb(214, 230, 133);"],
#contributions-calendar rect[style="fill: #d6e685;"] { fill: #246 !important }
#contributions-calendar rect[style="fill: rgb(140, 198, 101);"],
#contributions-calendar rect[style="fill: #8cc665;"] { fill: #369 !important }
#contributions-calendar rect[style="fill: rgb(68, 163, 64);"],
#contributions-calendar rect[style="fill: #44a340;"] { fill: #48c !important }
#contributions-calendar rect[style="fill: rgb(30, 104, 35);"],
#contributions-calendar rect[style="fill: #1e6823;"] { fill: #5af !important}
```
