### ISSUE TITLE
Inverted :shit:

### ISSUE THREAD

**Issue by Kir-Antipov** [StylishThemes/GitHub-Dark#1192]
* **Browser**: Firefox 78.0.2
* **Operating System**: Any
* **Link to page with the issue**: https://github.com/Kir-Antipov/GitHub-Defreshed
* **Screenshot**:

![Inverted](https://user-images.githubusercontent.com/40232067/88441604-3ca2df80-ce1a-11ea-9501-e942957fb678.png)

I'm sorry for the title, but it is as it is: :shit: emoji (`:shit:`) is inverted and looks kinda creepy and ghostly. The problem is this rule:

```css
g-emoji[fallback-src$="2795.png"],
g-emoji[fallback-src$="2796.png"],
g-emoji[fallback-src$="2797.png"],
g-emoji[fallback-src$="27b0.png"],
g-emoji[fallback-src$="2b1b.png"],
g-emoji[fallback-src$="25fe.png"],
g-emoji[fallback-src$="1f3b6.png"],
g-emoji[fallback-src$="1f3bc.png"],
g-emoji[fallback-src$="1f4b1.png"],
g-emoji[fallback-src$="1f4b2.png"],
g-emoji[fallback-src$="1f519.png"],
g-emoji[fallback-src$="1f51a.png"],
g-emoji[fallback-src$="1f51b.png"],
g-emoji[fallback-src$="1f51c.png"],
g-emoji[fallback-src$="1f51d.png"],
g-emoji[fallback-src$="1f3b5.png"],
g-emoji[fallback-src$="27bf.png"],
g-emoji[fallback-src$="1f43e.png"],
g-emoji[fallback-src$="1f43e.png"],
g-emoji[fallback-src$="a9.png"],
g-emoji[fallback-src$="fe0f.png"],
g-emoji[fallback-src$="ae.png"],
g-emoji[fallback-src$="fe0f.png"],
img[src*="resources-logo"],
svg.IconNav-img, .container-xl[id] svg, body.logged-out .col-md-7 svg {
    filter: invert(83%) !important;
}
```
I went through some of these URLs and found that some of them don't even exist, so maybe this rule is a little outdated and it's necessary to check if it applies correctly only to the necessary images and applies to all the necessary ones.
