### ISSUE TITLE
Redeem coupon-form-body is not colored

### ISSUE THREAD

**Issue by skmedix** [StylishThemes/GitHub-Dark#1199]
* **Browser**: Chrome 84.0.4147.89
* **Operating System**: Windows 10 Pro (2004 19041.388)
* **Link to page with the issue**: https://github.com/redeem
* **Screenshot**:
![image](https://user-images.githubusercontent.com/3246162/88853993-e99da380-d1f0-11ea-9540-722a1304d3c3.png)

**Comment by the-j0k3r** [comment]
Thanks for reporting the issue; indeed looks like we missed something.

We already auto generate overrides for this

![Capture](https://user-images.githubusercontent.com/31389848/88885907-a7e51b00-d239-11ea-84fd-a676cc2c217c.PNG)

default stylesheet says
```css
.coupons .coupon-form-body {
	width: 270px;
	padding: 20px;
	margin: 100px auto 60px;
	font-size: 14px;
	text-align: center;
	background-color: #fff;
	background-image: linear-gradient(#fefefe,#fafafa);
	border: 1px solid #ccc;
	border-radius: 6px;
	box-shadow: 0 1px 3px rgba(0,0,0,.075),inset 1px 0 #fff;
}
```

So we have to silence the `background-image: linear-gradient(#fefefe,#fafafa);`

incoming.
