### ISSUE TITLE
Add support for the scrollbar-color property

### ISSUE THREAD

**Issue by Kir-Antipov** [StylishThemes/GitHub-Dark#1214]
Firefox doesn't really support webkit, so `::-webkit-scrollbar-track` and `::-webkit-scrollbar-thumb` selectors have no effect on the scrollbars there.

However, Firefox does support the `scrollbar-color` and `scrollbar-width` properties, whose definition can be seen in [this draft](https://drafts.csswg.org/css-scrollbars-1/#scrollbar-color). So it would be great if you recolor the scrollbars for Firefox users too :)

I found these rules in your CSS:
```css
body.zh_logged_in .horizontal-scrollbar::-webkit-scrollbar-track {
  background-color: #242424;
}

body.zh_logged_in .horizontal-scrollbar::-webkit-scrollbar-thumb {
  background-color: #343434;
}
```
So I can suggest the following rule to recolor all scrollbars in Firefox:
```css
html {
  scrollbar-color: #343434 #242424;
}
```

**Comment by silverwind** [comment]
We have a [dedicated style](https://github.com/StylishThemes/Overlay-Scrollbars) for scrollbars already, don't really want to have it in this style.

**Comment by Kir-Antipov** [comment]
@silverwind, that was fast xD Didn't notice it, thanks!

But why not make scrollbar support here? All the same, they're part of the site, and light scrollbars are kinda out of the general tone

**Comment by the-j0k3r** [comment]
Standalone style allows customization by user, options that would crowd the GHD style and work for all Stylus supported browsers.

>But why not make scrollbar support here? 

Its better to have additional styles, GHD cant possibly accommodate all personal preferences for all users and additional styles can be give you more control that you wouldnt otherwise have if it was internal to GHD.

**Comment by silverwind** [comment]
It's possible a user already has another scrollbar style installed and we don't want to have to fight for priority with such a scrollbar style. Separate style cleanly solves such issues.

**Comment by Kir-Antipov** [comment]
Oh, I see. I just thought the style does recolor scrollbars, but only for the webkit-compatible browsers

**Comment by silverwind** [comment]
It should work in Firefox too.

````css
scrollbar-color: var(--custom-thumb-color) var(--custom-track-color) !important;

**Comment by the-j0k3r** [comment]
Both the GitHub scrollbars and global scrollbars themes support both Chromium and Firefox,There would be no point to the undertaking otherwise.

Firefox though is less configurable even though we support all the scrollbars options available.

**Comment by Kir-Antipov** [comment]
> I just thought the style does recolor scrollbars, but only for the webkit-compatible browsers

P.S. - it was about `GHD`, not about `Overlay-Scrollbars` (which works perfectly fine) :) 
I thought so based on these rules, which role I apparently misunderstood:

```css
body.zh_logged_in .horizontal-scrollbar::-webkit-scrollbar-track {
  background-color: #242424;
}

body.zh_logged_in .horizontal-scrollbar::-webkit-scrollbar-thumb {
  background-color: #343434;
}
```
