### ISSUE TITLE
buggy dispay with github isometric extension.

### ISSUE THREAD

**Issue by FatTonyy** [StylishThemes/GitHub-Dark#1217]
looks really good but I have some visibility issues with this extension I'm using called GitHub isometric extension, I've included a **screenshot** so you can take a look by yourself.

* **Browser**: Chrome
* **Operating System**: windows
* **Link to page with the issue**: 
* Screenshot ![**Screenshot**:](https://res.cloudinary.com/dcbx7o2dn/image/upload/v1598795291/fat-tonyy/Screenshot_l83the.png)

**Comment by the-j0k3r** [comment]
I dont think we support that extension and none uses it iirc, Is there a link to the extension?

**Comment by FatTonyy** [comment]
[link](https://chrome.google.com/webstore/detail/github-isometric-contribu/mjoedlfflcchnleknnceiplgaeoegien)

**Comment by the-j0k3r** [comment]
So the main portion of this (the isomentic day contribs is rendered inside a canvas which we can only apply filters to to chnage its appearance, the other elements seem to be inline HTML for the backgrounds, it also seems to use some primer classes for text like green colors we already generate.

It would be nicer if the developer would replace the inline HTML with more primer classes for Github so then it would make it 100% compatible OOB with Github Dark.

Until then **manual** harcoded overrides to this are the only way to go.

```css
  canvas#isometric-contributions {
    filter: invert(1) hue-rotate(180deg);
  }
  div[style*="background-color:rgba(255, 255, 255, 0.8)"] {
    background-color: var(--ghd-bg-color) !important;
  }
```

![Capture](https://user-images.githubusercontent.com/31389848/91663484-63bf9180-eae9-11ea-916d-0a681fad660e.PNG)


Caveat, you will not be able to select the color or the individual contribution activity blocks.

personally having tried the extension, I think it lacks granular per day info which interests me sometimes.
