### ISSUE TITLE
Not ideal render for the Jupyter Notebook displayed  in GitHub or Gist

### ISSUE THREAD

**Issue by NatureGeorge** [StylishThemes/GitHub-Dark#1221]
* **Browser**:  Microsoft Edge
* **Operating System**: Windows 10
* **Link to page with the issue**: <https://gist.github.com/NatureGeorge/9f62877f695528dc1ce284a67587e639>
* **Screenshot**: ![fig1](https://user-images.githubusercontent.com/43134199/93911428-f2b07a00-fd34-11ea-81d0-293dc9335204.png)

There are three main bugs:

1. LaTex Symbol rendered too large
2. Figure too big
3. Black output font makes it hard to recognize the characters

More details are mentioned in the [link.](https://gist.github.com/NatureGeorge/9f62877f695528dc1ce284a67587e639)

**Comment by NatureGeorge** [comment]
Bug No.3 (_Black output font makes it hard to recognize the characters_) was fixed by `v4.0.78`.

**Comment by NatureGeorge** [comment]
## SVG BackGround Issue

![eab496521cb7ae84378344bd09664dc3](https://user-images.githubusercontent.com/43134199/94677606-c6f24d00-034f-11eb-94f9-24c7dac40320.gif)

**Comment by silverwind** [comment]
That hover effect is intentional. It's for cases where a transparent image is made assuming a bright background so dark text can become unreadable.

**Comment by NatureGeorge** [comment]
> That hover effect is intentional. It's for cases where a transparent image is made assuming a bright background where dark text can become unreadable.

I see. It does help in some cases. Thank you.

😂I encounter a new issue here:

![9809bf873de667efb9bc087003128f01](https://user-images.githubusercontent.com/43134199/94690993-5b19df80-0363-11eb-857b-e4e90b26ad69.gif)

1. the 'broken' GitHub icon
2. ghosting close-icon 

Maybe I should open a new issue?

**Comment by silverwind** [comment]
Yeah please make new issues with links to reproduce. Close icon is kind of a known GitHub bug but we can probably attempt to workaround.

**Comment by the-j0k3r** [comment]
> SVG BackGround Issue

@NatureGeorge, Feel free to use https://raw.githubusercontent.com/StylishThemes/Feature-Override-Styles/master/github-dark-img-bg-clr.user.css

**Comment by the-j0k3r** [comment]
The issue is the overly broad rules with !important

to fix these we have to mod

```css
  /* https://github.com/StylishThemes/GitHub-Dark/issues/1209 */
  .render-shell img:not([src$=".svg" i]):not(.leaflet-tile):not(.leaflet-marker-icon) {
    width: 100% !important;
    height: 100% !important;
  }
```
 to

```css
  .render-shell img:not([src$=".svg" i]):not(.leaflet-tile):not(.leaflet-marker-icon):not(.math-inline):not([width*="300"]):not(:not([width*="%"])) {
    width: 100% !important;
    height: 100% !important;
  }
```

the problem here is that fixes are bug specific, most of these exclusions will break in other docs, so its a snowball can of worms, Ill let the author fix.

Introduced originally in https://github.com/StylishThemes/GitHub-Dark/commit/731ee227ad8e18eda0afae676c221f494348729f
and since then its causes more issues than it fixes.

Sorry, no time or patience to fix such issues.
