### ISSUE TITLE
Issue Encountered in Versioned GitHub Comment

### ISSUE THREAD

**Issue by NatureGeorge** [StylishThemes/GitHub-Dark#1225]
* **Browser**:  MicroSoft Edge
* **Operating System**: Win10
* **Link to page with the issue**: <https://gist.github.com/NatureGeorge/9f62877f695528dc1ce284a67587e639#gistcomment-3472562>
* **Screenshot**: 
![6b62995c9eb6e1139d7a7ec5cd438eba](https://user-images.githubusercontent.com/43134199/94697129-67556b00-036a-11eb-9f72-d9e95c306d61.gif)

When looking into the older edited version of a comment in GitHub, there exist two bugs:

1. Loading spinner hasn't been changed to `GitHub-Dark` 's SVG
2. ghosting close-icon

This seems to occur in any versioned comments.

**Comment by the-j0k3r** [comment]
For nr 2:

```css
  .Box-btn-octicon.m-0.btn-octicon.position-absolute.right-0.top-0 {
    display: none;
  }
```

Seems to fix issue, without breaking other instances.
