### ISSUE TITLE
Inverting rendered GitHub equations

### ISSUE THREAD

**Issue by Alex-Muirhead** [StylishThemes/GitHub-Dark#1228]
When rendering equations on a GitHub `README.md` where the equations are source from `render.githubusercontent.com/render/math`, the equations are not inverted correctly, and appear with white text AND background. 

I believe this can be fixed by replacing 
```css
img[src*="//render.githubusercontent.com/render/math"] {  /* Line: 29616 */
  filter: invert(90%);
}
```
with 
```css
img[src*="//render.githubusercontent.com/render/math"] {  /* Line: 29616 */
  filter: invert(90%);
  background-color: rgb(255, 255, 255);
}
```
to override the GitHub css, which attempts to set the background to `rgb(24, 24, 24)`. 

I'm unsure if I can just make a pull request to fix this, as I want to make sure it's not a breaking change that I'm not seeing.

* **Browser**: Firefox 81.0
* **Operating System**: Windows 10
* **Link to page with the issue**: Any valid GitHub page with images with source `render.githubusercontent.com/render/math`
* **Screenshot**: 
![image](https://user-images.githubusercontent.com/15205931/95004026-5b4b0100-0629-11eb-9919-81b81d0d338e.png)
