### ISSUE TITLE
GitHub Dark + Refined GitHub's moved "recently pushed" box

### ISSUE THREAD

**Issue by dgw** [StylishThemes/GitHub-Dark#1242]
* **Browser**: Chrome 86
* **Operating System**: Windows 10
* **Link to page with the issue**: not easily provided, unfortunately
* **Screenshot**: See comparison below.

This issue is a combination of updated styles from GitHub (started maybe a few days before #1236, but I wasn't sure until now if the fix for that had also fixed this) and a feature from Refined GitHub.

Without RGH:
![image](https://user-images.githubusercontent.com/164140/96671170-dbaa7b00-1326-11eb-971d-5cd9e3cd54c9.png)

With RGH (and the `recently-pushed-branches-enhancements` feature enabled):
![image](https://user-images.githubusercontent.com/164140/96671242-f7ae1c80-1326-11eb-9b59-bfd63323bc78.png)

I'm honestly not sure "who" was responsible for correctly styling the box when it gets moved the header, so definitely feel free to ask me (as kindly, or not, as you like) to piss off if this style wasn't doing anything special. I've also reported the problem to Refined GitHub's tracker: sindresorhus/refined-github#3674

**Comment by pjlong** [comment]
As a temp workaround, I was able to restore a similar style by adding:

```css
html.refined-github .rgh-recently-pushed-branches .Header .RecentBranches, 
html.refined-github .rgh-recently-pushed-branches [data-url$="recently_touched_branches_list"] .Box {
    border-color: var(--color-alert-warn-border) !important;
    background-color: var(--color-alert-warn-bg);
    color: var(--color-alert-warn-text);
}
```
