### ISSUE TITLE
Bright white background in empty cells of diffs

### ISSUE THREAD

**Issue by NetzwergX** [StylishThemes/GitHub-Dark#1255]
In diffs (e.g. when inspecting a commit), empty cells are bright white. This is due to GitHubs css including the following:

````css
.file-diff-split .empty-cell {
    background-color: var(--color-diff-blob-empty-block-bg);
}
````

Which is a bright white color.

* **Browser**: Version 86.0.4240.111 (Offizieller Build) (64-Bit) [current version as of writing this]
* **Operating System**: Win 10
* **Link to page with the issue**:  `https://github.com/WoltLab/WCF/pull/3666/commits/8ef61d386961656dc03cc0598bf6f662b0bd1127` 
* **Screenshot**:  ![github-dark-bug](https://user-images.githubusercontent.com/917322/97603671-f65aaf00-1a0c-11eb-9dc7-013e6e3a4ede.png)
