### ISSUE TITLE
Markers are not displayed on GeoJSON preview

### ISSUE THREAD

**Issue by ycrack** [StylishThemes/GitHub-Dark#1257]
Related: #1253 

* **Browser**: Google Chrome 86.0.4240.111 (Official Build)
* **Operating System**: Windows 10 version 20H2 (Build 19042.572)
* **Link to page with the issue**: https://github.com/colemanm/hurricanes/blob/master/fl_2004_hurricanes.geojson
* **Screenshot**: ![image](https://user-images.githubusercontent.com/26833834/97660261-5b1d1480-1ab4-11eb-9b86-0bd3d8b08508.png)

**Comment by the-j0k3r** [comment]
Also when you click one of those markers the popups aren't styled

![generic](https://user-images.githubusercontent.com/31389848/97676399-e2589100-1a90-11eb-8d6e-820f505a0826.gif)

**Comment by the-j0k3r** [comment]
Solution issue 1 exclude `.leaflet-marker-icon` from two rules. also fix the hover.

```css
  .render-shell img:not([src$=".svg" i]):not(.leaflet-tile):not(.leaflet-marker-icon) {
    width: 100% !important;
    height: 100% !important;
  }
  img.leaflet-marker-icon, img.leaflet-marker-icon:hover {
    background: none !important;
  }
  .render-shell img:not(.leaflet-tile):not(.leaflet-marker-icon):hover, .render-shell canvas:hover {
    background-image: url("data:image/gif;base64,R0lGODlhCgAKAIAAAOXl5f///yH5BAAAAAAALAAAAAAKAAoAAAIRhB2ZhxoM3GMSykqd1VltzxQAOw==") !important;
  }
```
