### ISSUE TITLE
Support `show-whitespace` from refined-github

### ISSUE THREAD

**Issue by Shinigami92** [StylishThemes/GitHub-Dark#1271]
**Describe the change you'd like**

Add following snippet to support [refined-github](https://github.com/sindresorhus/refined-github)'s `show-whitespace`

```css
[data-rgh-whitespace] {
    filter: brightness(4);
}
```

**Additional context**

https://github.com/sindresorhus/refined-github/issues/3772
