### ISSUE TITLE
[Safari+Cascadea] Your own comments have almost white border color

### ISSUE THREAD

**Issue by jimeh** [StylishThemes/GitHub-Dark#1331]
* **Browser**: Safari 15.0, with Cascadea 2.1.2
* **Operating System**: macOS 11.6
* **Link to page with the issue**: https://github.com/jimeh/emacs-builds/issues/13 (any issue/pull request where your own comments show)
* **Screenshot**:
  ![Screen-Shot-2021-10-21-11-49-39 58](https://user-images.githubusercontent.com/39563/138263232-6ce739c2-5776-4138-825d-7d20eeed55b8.png)

It seems that `base-color-rgb` usercss variable does not exist when using Safari and Cascadea, causing the `--color-accent-muted` CSS variable (and others) to be defined as `rgba(, 0.5)`.

Here's a screenshot inspecting CSS properties of the root `<html>` element with GitHub Dark active:

![Screen-Shot-2021-10-21-11-58-22 93](https://user-images.githubusercontent.com/39563/138264719-0ee89d6f-00da-4a48-bdf3-2503b70a1cb1.png)

**Comment by the-j0k3r** [comment]
Have you tested chrome/firefox + stylus? Are you using the latest version of this style?

**Comment by jimeh** [comment]
@the-j0k3r Yep, it works fine in Chrome and Firefox using Stylus. Everything is fully updated; browsers, Stylus, Cascadea, and the GitHub Dark userstyle CSS.

Hence I suspect maybe it's Cascadea that lacks support for the `-rgb` thing on color options?

**Comment by jimeh** [comment]
For now I have made a quick hack userstyle to work around the issue. It simply overrides the specific CCS variables affected. I use the default Base Color in GitHub Dark (`#4f8cc9`), which is `79, 140, 201` in RGB values.

```css
@-moz-document domain("githubusercontent.com"), domain("githubstatus.com"), domain("github.com")
{
	:root:root:root {
		--color-accent-muted: rgba(79, 140, 201, .3);
		--color-auto-blue-2: rgba(79, 140, 201, .25);
		--color-auto-blue-3: rgba(79, 140, 201, .5);
		--color-calendar-graph-day-L1-bg: rgba(79, 140, 201, .25);
		--color-calendar-graph-day-L2-bg: rgba(79, 140, 201, .5);
		--color-calendar-graph-day-L3-bg: rgba(79, 140, 201, .75);
		--color-primer-shadow-focus: 0 0 0 2.25px rgba(79, 140, 201, .3);
		--color-state-focus-shadow: 0 0 0 2.25px rgba(79, 140, 201, .3);
	}
}
```
