### ISSUE TITLE
All focused anchor elements all have a solid outline

### ISSUE THREAD

**Issue by bastimeyer** [StylishThemes/GitHub-Dark#1342]
* **Browser**:
  Chromium Version 100.0.4896.127 (Official Build) Arch Linux (64-bit)
* **Operating System**:
  Arch Linux
* **Link to page with the issue**:
  any
* **Screenshot**:
  ![image](https://user-images.githubusercontent.com/467294/163696347-72b2f9db-99ac-42a6-acc5-1120831c0179.png)

* **Reproduction**:
  Set `:focus` property on any anchor element via the dev tools

* **CSS**:
  The `outline` property gets set via these selectors:

  ```css
  .global-focus-styles a:focus:not(:focus-visible), .global-focus-styles button:focus:not(:focus-visible), .global-focus-styles [role=button]:focus:not(:focus-visible), .global-focus-styles input[type=radio]:focus:not(:focus-visible), .global-focus-styles input[type=checkbox]:focus:not(:focus-visible) {
      outline: solid 1px transparent;
  }
  ```
  ```css
  .UnderlineNav-item.selected, .UnderlineNav-item[role=tab][aria-selected=true], .UnderlineNav-item[aria-current]:not([aria-current=false]) {
      font-weight: 600;
      color: var(--color-fg-default);
      border-bottom-color: var(--color-primer-border-active);
      outline: 1px dotted transparent;
      outline-offset: -1px;
  }
  ```

  The second selector is probably responsible for #1341, which sets a dotted outline.

* **Issue**:
  The `outline-color` is part of Github-Dark, and it gets set to `!important`, overriding the `transparent` definitions from the `outline` properties above:
  https://github.com/StylishThemes/GitHub-Dark/blob/8d061f7ca821a61760af8a3c33a0f550b901b149/src/main.css#L179-L182
  ```css
  a:focus, button:focus, [tabindex] {
      outline-color: #4f8cc9 !important;
  }
  ```
