### ISSUE TITLE
Default tab size = 4

### ISSUE THREAD

**Issue by silverwind** [StylishThemes/GitHub-Dark#159]
GitHub's default sheet uses a tab-size of 8, which results in some misalignment on code which uses tabs ands expects a size of 4 (which is pretty common). We could fix this with:

``` css
    .highlight pre {
        -webkit-tab-size: 4 !important;
           -moz-tab-size: 4 !important;
                tab-size: 4 !important;
    }
```

Should I go for it? Any opinions?
