### ISSUE TITLE
Network tree images

### ISSUE THREAD

**Issue by Mottie** [StylishThemes/GitHub-Dark#162]
I just noticed that the images in the [network tree](https://github.com/StylishThemes/GitHub-Dark/network/members) don't contain an `alt` attribute anymore.

![2014-08-15 13_20_21-network members stylishthemes_github-dark](https://cloud.githubusercontent.com/assets/136959/3937049/e53f9d76-24a8-11e4-8a95-0fbcfd8d1774.png)

so [this css](https://github.com/StylishThemes/GitHub-Dark/blob/master/github-dark.css#L1148-L1162) isn't even being applied:

``` css
/* === Repository Network Tree === */
#network .repo img[alt="T"], #network .repo img[alt="I"], #network .repo img[alt="L"] {
  width: 26px !important;
  height: 0 !important;
  padding-top: 22px !important;
}
#network .repo img[alt="T"] {
  background: url('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAaAQMAAACNTe4+AAAABlBMVEUAAABPT09PI3z5AAAAAnRSTlMAslP8H5gAAAATSURBVAjXYwADBwbS6NAAUvUBALZSA6Z3hy6MAAAAAElFTkSuQmCC') no-repeat !important;
}
#network .repo img[alt="I"] {
  background: url('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAaAQMAAACNTe4+AAAABlBMVEUAAABPT09PI3z5AAAAAnRSTlMAslP8H5gAAAAOSURBVAjXYwADBwZa0wCi6ANBB33CVwAAAABJRU5ErkJggg==') no-repeat !important;
}
#network .repo img[alt="L"] {
  background: url('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAaAQMAAACNTe4+AAAABlBMVEUAAABPT09PI3z5AAAAAnRSTlMAslP8H5gAAAATSURBVAjXYwADBwbS6NAABhIBAJVSAiYmyPmYAAAAAElFTkSuQmCC') no-repeat !important;
}
```

The images are being inverted using the image filter, but have a black background. So my question is do we update these definitions so that they work with the image url. For example:

``` css
#network .repo img[src="https://assets-cdn.github.com/images/modules/network/t.png"] {
  background: url('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAaAQMAAACNTe4+AAAABlBMVEUAAABPT09PI3z5AAAAAnRSTlMAslP8H5gAAAATSURBVAjXYwADBwbS6NAAUvUBALZSA6Z3hy6MAAAAAElFTkSuQmCC') no-repeat !important;
}
```

or just completely remove them and free up some more space in the file?

My OCD doesn't like the black background of the inverted images, but I so rarely visit that page that it probably doesn't matter, so I would vote to remove it all. What do you guys think?
