### ISSUE TITLE
Add min-height for html

### ISSUE THREAD

**Issue by Mottie** [StylishThemes/GitHub-Dark#182]
I found [this organizational page](https://github.com/dubhacks) which does not fill the height of the browser, in Chrome. I was just wondering what your thoughts are on adding:

```css
html { min-height: 100% !important; } /* !important may not be needed */
```
I find it odd that an [organization with no repositories](https://github.com/tablesorter), doesn't have this same issue.
