### ISSUE TITLE
Change yellow to brown

### ISSUE THREAD

**Issue by Mottie** [StylishThemes/GitHub-Dark#184]
I really don't like the yellow panel color... I thought I changed it to look more brown in the past, but it looks like it's yellow again.

For example, if you look at the ProTip on [this page](https://github.com/trending) you'll see this:

![2014-10-03 11_35_14-trending repositories on github today](https://cloud.githubusercontent.com/assets/136959/4509060/83f32396-4b1b-11e4-8770-341d726de5ab.png)

I'd like to change it to brown, or some other color, not puke yellow:

![2014-10-03 11_34_22-trending repositories on github today](https://cloud.githubusercontent.com/assets/136959/4509067/935440b8-4b1b-11e4-9202-a11846d39823.png)

``` css
  /* === Yellow panel === */
  #feedHeaderContainer, .feedBackground, .infotip, .form-actions .tip, .mini-callout, .snippet em, #message .sent, .notification,
  .callout, .contributing, .ejector, #issues_search .results em, .bootcamp-help ul li, .btn-download, .feature-tabs .tab-button,
  .plan.free, #message.minor, .chzn-results li em, #missing-readme, .warning, .page-notice, a.button.classy, .signed-out-comment,
  .facebox-alert, .branch-status.status-pending .discussion-item-icon, .discussion-event-status-renamed .discussion-item-icon,
  .state-indicator.renamed, .discussion-topic .branch-status.status-pending, .form-checkbox label em.highlight,
  .recently-touched-branches, .secret .repo-label span, .protip-callout, .compare-pr-placeholder {
    background: #321 !important;
    border-color: #542 !important;
    color: #b74;
  }
  /* Travis build in progress, merge status unknown */
  .branch-action-state-unknown .branch-action-body, .branch-action-state-unknown .branch-status,
  .branch-action-state-unstable .branch-action-body, .branch-action-state-unstable .branch-status {
    border-color: #b74 !important;
  }
  .recently-pushed-branch-details, #toc .octicon-diff-modified, .secret .repo-label span {
    color: #b74 !important;
  }
  .recently-pushed-branch-details a, .protip-callout a, .compare-pr-placeholder p, .compare-pr-placeholder .help-link,
  a.status-pending {
    color: #da6 !important;
  }
```

What do you guys think?
