### ISSUE TITLE
Searchbox-Result Hover

### ISSUE THREAD

**Issue by mihawk90** [StylishThemes/GitHub-Dark#20]
The Hover on searchbox results is a bright background which makes it quite hard to read the text on it.

I suggest using a black background for the hover effect:

``` CSS
.commandbar .choice:hover,
.commandbar .loading:hover {
  background-color: #000000;
}
```

Makes the text perfectly readable and still distinct from the normal background.
