### ISSUE TITLE
Zenhub

### ISSUE THREAD

**Issue by Mottie** [StylishThemes/GitHub-Dark#203]
I noticed [this userstyle](https://userstyles.org/styles/103434/dark-zenhub) today, and installed the [ZenHub browser extension](https://www.zenhub.io/).

Basically it adds a new tab that allows organizing issues. The above userstyle does add basic styling, but misses some. I was thinking we could add an option on userstyles to include ZenHub styling, so users can select the additional styling if they so choose. Or should we just integrate it into the existing css like we did with Octotree?

**Comment by silverwind** [comment]
That style has like 7 rules in it, I'd do a seperate section in our style for it, if this ZenHub thing is worth it. I won't be available for testing/updating this thought, unless they provide a Firefox/Greasemonkey version of it.

**Comment by Mottie** [comment]
This is what I've come up with for ZenHub styling so far... it's more than I thought

```css
/* ZenHub styling */
.zh-button {
  background-color: /*[[base-color]]*/ #008080 !important;
  border-color: /*[[base-color]]*/ #008080 !important;
  color: #fff !important;
}
.zh-pipeline-issue-toggler:hover {
  color: /*[[base-color]]*/ #008080 !important;
}
/* background */
.zh-overlay {
  background-color: rgba(0,0,0,0.9) !important;
}
li.zh-pipeline, li.new-pipeline-column, .zh-schema-pipelines {
  background-color: #181818 !important;
  border-color: #555 !important;
}
li.zh-pipeline-issue, .zh-pipeline-issue-content, .zh-issue-meta, .zh-pipeline-issue-action,
.zh-pipeline-heading-container, .zh-button-grey, .zh-board-menu, .zh-schema-title {
  background-color: #222 !important;
  border-color: #555 !important;
}
.zh-uploader-drop, .zh-button-grey.selected, .zh-button-grey:hover {
  background: #333 !important;
}
/* border */
.zh-paw-btn-inner, .zh-schema, .zh-schema-pipeline-name, .popover {
  border-color: #555 !important;
}
.popover.right .arrow {
  border-right-color: #555 !important;
}
/* text */
.zh-uploader-container *, .zh-overlay-body, .zh-pipeline-issue-action {
  color: #fff !important;
}
.zh-paw-btn-count, .zh-schema-pipeline-name {
  color: #888 !important;
}
/* tooltip */
.popover {
  box-shadow: rgb(85,85,85) 0px 1px 1px !important;
}
/* webkit scrollbars */
.zh-pipeline-issues-wrapper::-webkit-scrollbar-track {
  background: #181818 !important;
}
.zh-board-wrapper.horizontal-scrollbar::-webkit-scrollbar-track {
  background: #181818 !important;
}
.zh-board-wrapper.horizontal-scrollbar::-webkit-scrollbar-thumb {
  background: #444 !important;
}
.zh-pipeline-issues-wrapper::-webkit-scrollbar-thumb {
  background: #444 !important;
}
```

I'm still leaning towards making is an optional code block.
