### ISSUE TITLE
Labels

### ISSUE THREAD

**Issue by Mottie** [StylishThemes/GitHub-Dark#208]
Using `a:not([href*="label"])` ([line 17](https://github.com/StylishThemes/GitHub-Dark/blob/master/github-dark.css#L17)) to style links with the base-color is still causing some unwanted issues. I know we need to avoid styling issue labels, but I think we should avoid using the `href` attribute.

For example, look at all the unstyled links in this repository: https://github.com/bradfrost/labelmask

So, I modified the selector:

```css
/* don't style text color on labels, selected tabs and all header links/logo */
/* line 17 */
a:not(.button):not(.color-label):not(.label):not(.selected):not([class*="header-"]),
...
/* line 45 */
.comment-body a:not(.button):not(.color-label):not(.label):not(.selected),
...
{
    color: /*[[base-color]]*/ #4183C4 !important;
}
```

I know it's not pretty, but can you help me test these changes to see if it solves the link color issues?

**Comment by Mottie** [comment]
*sigh* The above selectors barely scratch the surface... mostly because of all those class names inside the `:not()` selectors give that definition a lot higher specificity.

Maybe just this change would be better:

```css
a:not([class*="label"])
```

**Comment by Mottie** [comment]
Ok, now I'm using:

```css
a:not([style]), ... .comment-body a:not([style])
```

and somewhere in the style, I added this definition:

```css
a.label:not([style]) {
  color: #fff !important;
  text-shadow: 2px 2px 0 #444, -1px -1px 0 #444, 1px -1px 0 #444, -1px 1px 0 #444, 1px 1px 0 #444 !important;
}
```

It seems to be the best solution so far.

**Comment by silverwind** [comment]
There's three different markups for labels:

#### Issue changelog
````html
<span class="label-color" title="by Mottie at 2015-01-22 06:43:10" style="background-color: #0052cc;">
    <a style="color: #fff" href="/StylishThemes/GitHub-Dark/labels/Extensions"></a>
</span>
````
#### Issue Sidebar:
```
<a class="label css-truncate-target linked-labelstyle-ff11aa" title="userstyles.org" href="/StylishThemes/GitHub-Dark/labels/userstyles.org"></a>
```
#### Label editor:
```html
<a class="label label-link" style="background-color: #009800; color: #fff; " href="/StylishThemes/GitHub-Dark/labels/Chrome">
    <span class="octicon octicon-tag"></span>
    <span class="label-name"></span>
</a>
```

We just need to find a selector to match these all.

**Comment by silverwind** [comment]
What about 

````
a[href*=/labels/]
````

That would match all three a's too, and improve our error rate on that selector.

**Comment by Mottie** [comment]
I was thinking that just including the forward slashes would work

```css
a:not([href*="\/labels\/"])
```

Until I encountered a fourth markup style on the [issue page](https://github.com/StylishThemes/GitHub-Dark/issues):

#### Issue listing 

```css
<span class="labels">
    <a href="/StylishThemes/GitHub-Dark/issues?q=is%3Aopen+label%3AGitHub" aria-label="View all GitHub issues" class="label labelstyle-e11d21 linked-labelstyle-e11d21 lightertooltipped" style="background-color: #e11d21; color: #fff;">GitHub</a>
</span>
```

But in this case, I think it might work if we include the forward slashes in the selector, and then target the `lightertooltipped` and `darkertooltipped` classes to style the label text color.

```css
a:not([href*="\/labels\/"])
...
.comment-body a:not([href*=\/labels\/]) /* is this selector even necessary? */
{
  color: /*[[base-color]]*/ #4183C4 !important;
}

a.lightertooltipped { color: #eee !important; }
a.darkertooltipped { color: #111 !important; }
```

**Comment by Mottie** [comment]
LOL great minds think alike... and ours too! ;)

**Comment by silverwind** [comment]
not sure about that commet body thing. In doubt, kill it.

**Comment by Mottie** [comment]
Let's try it!

**Comment by silverwind** [comment]
Looking good. GitHub must've changed some things, as it wasn't as easy last time I touched that selector.

**Comment by Mottie** [comment]
LOL I know what you mean

**Comment by Mottie** [comment]
Ugh, this is broken again....

The [labels from the issues page](https://github.com/StylishThemes/GitHub-Dark/issues) now look like this:

```html
<a href="/StylishThemes/GitHub-Dark/issues?q=is%3Aopen+label%3AFirefox" aria-label="View all Firefox issues" class="label labelstyle-eb6420 linked-labelstyle-eb6420 tooltipped tooltipped-n" style="background-color: #eb6420; color: #fff;">
  Firefox
</a>
```

I guess they got rid of `lightertooltipped` and `darkertooltipped`... I guess we could just pretend it never happened, and leave things as they are LOL.

**Comment by silverwind** [comment]
Damn them, why can't they just use a single style for these. This is just infuriating...

Anyways, the quest is to find a common denominator between these:
````css
<a style="color: #fff" href="/StylishThemes/GitHub-Dark/labels/GitHub">
    GitHub
</a>
````
````css
<a class="label css-truncate-target linked-labelstyle-e11d21" title="GitHub"
href="/StylishThemes/GitHub-Dark/labels/GitHub"></a>
````
````css
<a class="label labelstyle-e11d21 linked-labelstyle-e11d21 tooltipped tooltipped-n"
style="background-color: #e11d21; color: #fff;" aria-label="View all GitHub issues"
href="/StylishThemes/GitHub-Dark/issues?q=is%3Aopen+label%3AGitHub"></a>
````
````css
<a class="label label-link" style="background-color: #e11d21; color: #fff; "
href="/StylishThemes/GitHub-Dark/labels/GitHub"></a>
````

**Comment by silverwind** [comment]
hrefs:

````
/StylishThemes/GitHub-Dark/labels/GitHub
/StylishThemes/GitHub-Dark/labels/GitHub
/StylishThemes/GitHub-Dark/issues?q=is%3Aopen+label%3AGitHub
/StylishThemes/GitHub-Dark/labels/GitHub
````

**Comment by silverwind** [comment]
I guess `href*='label'` is the only way to go, with all the false positives it brings.

**Comment by silverwind** [comment]
Or we do

````css
a { color: [base-color] }
````

Note: no `!important`

**Comment by silverwind** [comment]
If only there were a way to add specificity to a single `a` selector without using !important. There is a very dirty hack, which still works in Firefox:

http://codepen.io/chriscoyier/pen/lzjqh

But for some reason, I can't even get links colored with thousands of `:not(#anything)` chained together.

**Comment by silverwind** [comment]
````css
  a.label[style*="color: #fff"] { color: #fff !important }
  a.label[style*="color: #332900"] { color: #332900 !important }
````

![misson](https://cloud.githubusercontent.com/assets/115237/6233945/ebf1adba-b6d6-11e4-9c95-8367a3ae1105.jpg)
