### ISSUE TITLE
Custom monospace font option

### ISSUE THREAD

**Issue by silverwind** [StylishThemes/GitHub-Dark#210]
Github uses Menlo pretty much everywhere, and it'd be nice to have an option on userstyles.org to input a custom font, defined by name.

Here's what I currently use in an separate stylesheet:
```css
pre, code, tt, kbd, pre, samp, .blob-code, .file-data pre, .line-data,
#gist-form .file .input textarea, .ace_editor.ace-github-light, .ace_editor {
    font-family: Monaco !important;
}
```

@Mottie could you look into adding this to userstyles? I'll commit an empty selector group for now.

**Comment by Mottie** [comment]
I can add a select dropdown with alternatives no problem. But I'm not so good with fonts and font stacks. What should I include?

I found this "sort-of" [list of font alternatives here](http://www.slant.co/topics/67/viewpoints/23/~what-are-the-best-programming-fonts~menlo) 

And here are a few font stacks I found:

```css
/* Consolas */
font-family: Consolas,monaco,monospace; 

/* Courier New */
font-family: 'Courier New', Courier, 'Lucida Sans Typewriter', 'Lucida Typewriter', monospace;

/* Lucida Console */
font-family: 'Lucida Console', 'Lucida Sans Typewriter', monaco, 'Bitstream Vera Sans Mono', monospace;

/* Lucida Sans Typewriter */
font-family: 'Lucida Sans Typewriter', 'Lucida Console', monaco, 'Bitstream Vera Sans Mono', monospace;

/* Monaco */
font-family: monaco, Consolas, 'Lucida Console', monospace;

/* Andale Mono */
font-family: 'Andale Mono', AndaleMono, monospace;

/* Monospace (Smashing Magazine: http://www.smashingmagazine.com/2009/09/22/complete-guide-to-css-font-stacks/) */
font-family: Consolas, ‘Andale Mono WT’, ‘Andale Mono’, ‘Lucida Console’, ‘Lucida Sans Typewriter’, ‘DejaVu Sans Mono’, ‘Bitstream Vera Sans Mono’, ‘Liberation Mono’, ‘Nimbus Mono L’, Monaco, ‘Courier New’, Courier, monospace;
```

**Comment by silverwind** [comment]
A simple text field where the user names his font would probably be best, as we can't really know what he has installed.

Another alternative would be to add `@import` statements for a few popular WebFonts, but that `+` in the URL could pose a problem, Also I think WebFonts is missing a few good monospace fonts. Here's two examples:

````css
@import url(http://fonts.googleapis.com/css?family=Ubuntu+Mono);
pre, code, tt, kbd, pre, samp, .blob-code, .file-data pre, .line-data,
#gist-form .file .input textarea, .ace_editor.ace-github-light, .ace_editor {
    font-family: Ubunto Mono !important;
}
````

````css
@import url(http://fonts.googleapis.com/css?family=Inconsolata);
pre, code, tt, kbd, pre, samp, .blob-code, .file-data pre, .line-data,
#gist-form .file .input textarea, .ace_editor.ace-github-light, .ace_editor {
    font-family: Inconsolata !important;
}
````

**Comment by Mottie** [comment]
Sadly, you can't use `@import` with Stylish, see:

* [discussion](https://forum.userstyles.org/discussion/28579/suggestion-allow-import-from-google-web-fonts-in-styles-hosted-on-userstyles-org)
* [bug report](https://bugzilla.mozilla.org/show_bug.cgi?id=356503)

I had to double check to figure out that it is possible to add an input on userstyles to enter plain text, such as a font stack, but the user could just as easily enter an invalid font name. I was able to install a style with this setting:

```css
.my-font {
  font-family: 234234
 }
```

So really, I think a select dropdown with predefined options would be the best.
