### ISSUE TITLE
Atom feed page

### ISSUE THREAD

**Issue by silverwind** [StylishThemes/GitHub-Dark#214]
https://github.com/silverwind.atom

Firefox has some styles of it's own on feed pages, we shouldn't style them. Also, Chrome just displays the xml. Does it really not support feeds?

**Comment by silverwind** [comment]
Also related: SSH public keys:

https://github.com/silverwind.keys

I think we had the discussion about styling plaintext sites, and I still think we should to these :)

**Comment by Mottie** [comment]
It looks like most of the Firefox feed is already styled; just an icon and button are missing some stye. And yeah, Chrome doesn't style feeds at all :disappointed: 

Honestly, I don't look at raw urls that often, so go ahead and do what you want ;)

**Comment by silverwind** [comment]
The feed pages crosses a bit too much into browser theme territory for me, also my Firefox theme does some changes to it.

I'll handle the raw URLs thought, can't stand the white flash personally.

**Comment by silverwind** [comment]
Eh, can't seem to get that regexp right to not match URLs ending in `.atom`.

**Comment by Mottie** [comment]
I sort of got this to work (added to the bottom, outside of the main definition)

```css
@-moz-document regexp("^https?://github\.com\/.*\.atom$") {
  #feedSubscribeLine * { filter: invert(100%) !important; color: #000 !important; }
}
```

The "Subscribe to..." with select & "Subscribe Now" button are inside of a `<xul:vbox>` element, so there isn't any way to style it directly.
