### ISSUE TITLE
Wider Wiki

### ISSUE THREAD

**Issue by Mottie** [StylishThemes/GitHub-Dark#216]
I would really like to make the wiki page wider; but not make it full width. So I messed around with the page a little and came up with this css:

```css
.has-rightbar {
  position: relative;
}
#wiki-rightbar {
  position: absolute !important;
  top: -58px !important;
  right: 0px !important;
  z-index: 1 !important;
  background: rgba(17,17,17,0.9) !important;
  padding: 0 5px !important;
}
.has-rightbar #wiki-body, .has-rightbar #wiki-footer {
  margin-right: 20px !important;
}
.wiki-pages-box.collapsed {
  margin-bottom: 0 !important;
}
.wiki-pages-box.collapsed ~ div {
  display: none !important;
}
```

Try it out and tell me what you think... click to toggle the pages box to toggle the entire side bar view:

![sidebar](https://cloud.githubusercontent.com/assets/136959/6555147/449d5f36-c631-11e4-9881-d575a8eabb13.gif)
