### ISSUE TITLE
inline-block

### ISSUE THREAD

**Issue by Mottie** [StylishThemes/GitHub-Dark#223]
For some silly reason, I can't seem to log into GitHub in Firefox so I can't test to see why [this hack for Firefox](https://github.com/StylishThemes/GitHub-Dark/blob/master/github-dark.css#L194-L198) is necessary.

```css
  /* HACK: Fix annoying text selection bug in Firefox */
  .markdown-body code, .markdown-body tt {
    padding: 0 .2em !important;
    display: inline-block !important;
    border: 1px solid #383838 !important;
  }
```
Anyway, the `display: inline-block` is causing this problem in my feed:

![2015-04-04 08_49_10-github](https://cloud.githubusercontent.com/assets/136959/6992909/e38ee396-daa7-11e4-9d92-80f41fe88ea2.png)

If I turn off just that setting, everything looks good again:

![2015-04-04 08_52_31-github](https://cloud.githubusercontent.com/assets/136959/6992912/02bffb88-daa8-11e4-8b97-f02d30006a92.png)
