### ISSUE TITLE
Chaos Syntax highlighting theme is broken at code-sections

### ISSUE THREAD

**Issue by RoestVrijStaal** [StylishThemes/GitHub-Dark#229]
Please take a look at this screenshot using Chaos: 
![github dark - chaos style is broken at code section](https://cloud.githubusercontent.com/assets/6899548/7337164/58472fbc-ec1f-11e4-9aea-4c9f8783ac55.png)

As you could see, the bg colour of the code sections is white. Unfortunately I can't fix it by my own because the styling-section is obfuscated.

The code section reads fine in other themes, but I want to stick on Chaos because better colours. So it would be nice if you could fix it.

**Comment by Mottie** [comment]
Hi @RoestVrijStaal!

I am not seeing the white background in the code blocks of the [contributing.md](https://github.com/StylishThemes/GitHub-Dark/blob/master/CONTRIBUTING.md) page as shown in the screenshot. Is the most up-to-date version of the style being used? 

https://userstyles.org/styles/37035/github-dark

**Comment by RoestVrijStaal** [comment]
True, I use the latest version 2015-04-23.

**Comment by Mottie** [comment]
So, the problem is fixed? Or not fixed? Can I close this issue?

**Comment by RoestVrijStaal** [comment]
Unfortunately no, I used the latest version in the beginning of posting this issue. 

In the mean time I made a workaround stylesheet for myself, feel free to use it: http://ideone.com/EEVMxs

**Comment by silverwind** [comment]
This is the offending style in GH's stylesheet:

```css
.markdown-body .highlight pre, .markdown-body pre {
    background-color: #F7F7F7;
}
```

**Comment by silverwind** [comment]
I think the chaos theme (and possibly others are just missing `!important`):

```css
/*! Chaos */
.highlight, .ace_editor {
  background-color: #161616;
  color: #E6E1DC;
}
```
