### ISSUE TITLE
GeoJSON maps

### ISSUE THREAD

**Issue by silverwind** [StylishThemes/GitHub-Dark#242]
Might be worth looking into getting these darker:

https://github.com/benbalter/dc-maps/blob/master/embassies.geojson

Here's a simple invert on the map pane, obviously needs a few more fixes and possibly a hue rotation. I'll look into it.

![screen shot 2015-07-23 at 6 12 43 pm](https://cloud.githubusercontent.com/assets/115237/8855639/8bd6c504-3166-11e5-9fe3-a561156770d4.png)

**Comment by Mottie** [comment]
What about trying these settings?

```css
.leaflet-tile-container img {
     -webkit-filter: invert(100%) hue-rotate(180deg) brightness(1.4) !important;
	         filter: invert(100%) hue-rotate(180deg) brightness(1.4) !important;
}
```

![2015-07-23 11_50_28-dc-maps_embassies geojson at master benbalter_dc-maps](https://cloud.githubusercontent.com/assets/136959/8856545/139c594e-3131-11e5-97e5-1a35af30fa11.png)

**Comment by silverwind** [comment]
Not bad, maybe reduce contrast slightly? Also, UI elements should also be styled :)

**Comment by silverwind** [comment]
Also, maybe you could tweak the hue rotate slightly so the result is less green.

**Comment by Mottie** [comment]
Yeah, I noticed the +/- button in the upper left and the ⓘ button popout in the upper right need styling.

**Comment by Mottie** [comment]
Go for it, I think you have a better eye for color :P

**Comment by silverwind** [comment]
```css
invert(100%) hue-rotate(200deg) brightness(1.2) !important
```
![screen shot 2015-07-23 at 6 58 51 pm](https://cloud.githubusercontent.com/assets/115237/8856744/ef4dd46e-316c-11e5-9d4e-7984d3ec5333.png)

Did you remove the pin shadows in your screenshot?

**Comment by Mottie** [comment]
That looks a little too dark. No, I didn't remove the pin shadows. Odd that your pin shadows are inverted - did you use a different selector than I did above?

**Comment by silverwind** [comment]
Well it looks fine contrast-wise on my display. Maybe yours is set too dark? :stuck_out_tongue: 
And yeah, I was using another selector. Might play with this more later.

**Comment by silverwind** [comment]
Might bump brightness to 1.3 or 1.4 max, but anything above that is too bright, at least for me :wink:

**Comment by Mottie** [comment]
What do you think about these settings?

```css
.leaflet-control-zoom a,
.leaflet-control-attribution.leaflet-compact-attribution:after {
    -webkit-filter: invert(100%);
            filter: invert(100%);
}
.leaflet-tile-container img {
    -webkit-filter: invert(100%) hue-rotate(180deg) brightness(1.8) !important;
            filter: invert(100%) hue-rotate(180deg) brightness(1.8) !important;
}
.leaflet-marker-pane img {
    -webkit-filter: brightness(.8) !important;
            filter: brightness(.8) !important;
}
.leaflet-control-zoom, .leaflet-container .leaflet-control-attribution.leaflet-compact-attribution {
    background-color: #222 !important;
}
```

![2015-07-24 18_05_20-dc-maps_embassies geojson at master benbalter_dc-maps](https://cloud.githubusercontent.com/assets/136959/8886364/a12d3dde-322e-11e5-802a-73ff97b4b02b.png)

I see why you thought I removed the marker drop shadow, it's because I didn't invert it before. The selector I shared was the only selector I used. With the above settings, the drop shadows on the marker is so dark, you can't see it - I copied the marker image below so you can see.

![pin-m 438fd3 2x](https://cloud.githubusercontent.com/assets/136959/8886384/e3ad1b02-322e-11e5-8c72-0fedf9bb6c10.png)

**Comment by silverwind** [comment]
Not bad at all. Just missing the popup when you click a marker. Let's compromise on 1.5 brightness?

**Comment by silverwind** [comment]
Also, maybe something can be done to make the drop shadow a bit more apparent, but black on dark is always hard.

**Comment by Mottie** [comment]
We could always replace the image with an svg :wink: 

Oh, ok I can commit.. I figured since you assigned it to yourself :grin:

**Comment by Mottie** [comment]
Ok, so I tried replacing the marker with a png just to make sure it was possible. And it does not appear that it is, since the script resizes the image depending on the map scale. So I guess we either find an alternative filter method or just live without seeing the shadow.

I set the hue-rotate to `200deg` and the water looks a little too purple to me... but then again I think it might be that my monitors need to be color tuned since it looks slightly different on each one.

**Comment by silverwind** [comment]
No need to worry about those pins, it's really a minor issue. For the hue, I too have to check another monitor.

**Comment by silverwind** [comment]
Looks like map diffs aren't working for some reason:

https://github.com/benbalter/congressional-districts/commit/2233c76ca5bb059582d796f053775d8859198ec5?short_path=85d2c1b#diff-85d2c1b78193e963475250414e57940b

**Comment by Mottie** [comment]
Hmm, it appears that [this definition](https://github.com/StylishThemes/GitHub-Dark/blob/master/github-dark.css#L160) is interfering. If I disable it, it works:

```css
  #dashboard, div.highlight, svg {
    width: 100% !important;
  }
```
