### ISSUE TITLE
Line wrapping of long code lines

### ISSUE THREAD

**Issue by silverwind** [StylishThemes/GitHub-Dark#253]
I just pushed a [change](https://github.com/StylishThemes/GitHub-Dark/commit/c1596b3d5df35d40998713fc455af65f93fe392e) that enables wrapping of long lines like [this one](https://github.com/nodejs/node/blob/42a8a0a53e86376c63c46125896e3086cc6764d4/vcbuild.bat#L200).

So far It seems to work, but there may be side effects and we also need to take care of Gist and other code boxes. We could do an option for it, but I see no downside, so it may be unnecessary.

**Comment by Mottie** [comment]
I like it... I'm using it now and I'll report back if I run into any issues.

**Comment by Mottie** [comment]
The change does not work on [encoded images](https://github.com/StylishThemes/GitHub-Dark/blob/master/github-dark.css#L10).

You can include a `break-all` definition, but I don't know if it's a good idea since it will break up words in the middle:

```css
.blob-code-inner {
  white-space: pre-wrap !important;
  word-break: break-all !important;
}
```

**Comment by silverwind** [comment]
Hmm, I guess most editors break like `break-all`, so breaking in the middle of a word is probably acceptable in code, I'll do it.

**Comment by silverwind** [comment]
Looking good so far. The `blob-code-inner` class i used pretty much everywhere, even in Gist.

**Comment by silverwind** [comment]
There's a bit of overflow on diffs it seems: https://github.com/silverwind/uppie/commit/00ca3577c036999b39ef0435dc5a465c50c2626a (view the suppressed diff). Not sure what's exactly causing the overflow here.

**Comment by silverwind** [comment]
Added `display: block` in an attempt to fix that overflow. Watch out for issues :)

**Comment by Mottie** [comment]
It's because some `td`'s have the `blob-code-inner` class. You can add this to fix it:

```css
td.blob-code-inner {
  display: table-cell !important;
}
```

**Comment by silverwind** [comment]
Awesome, thanks :+1:

**Comment by silverwind** [comment]
So far I noticed no issues, I think it's good to go.

**Comment by simov** [comment]
Can we not use it in issue comments https://github.com/request/request/issues/1932#issuecomment-159589150 at least ? That it looks kind of funny and it's definitely not easy to read.

The code block placed inside an issue is much narrower than the one in the source code view, plus line wrapping makes sense only for certain text types.

**Comment by silverwind** [comment]
With my current font, the inline block fits 89 characters, which isn't too bad as many people still adhere to 80 character lines. We should at least add an option on userstyles.org for people who prefer no wrapping and I think I'll explore a userscript addon to toggle wrapping.

**Comment by simov** [comment]
> 80 character lines

That's kind of true but people tend to paste completely random stuff in the comment box. I can still change the style for myself only, but I though that's an actual issue.

**Comment by Mottie** [comment]
Hey @silverwind, the second line targets code in comments. What is the `.markdown-body` in the first line targeting?

```css
  /* GitHub Bug: Enable wrapping of long code lines */
  .blob-code-inner, .markdown-body > pre > code,
  .markdown-body > .highlight > pre {
    white-space: pre-wrap !important;
    word-break: break-all !important;
    display: block !important;
  }
```
