### ISSUE TITLE
Code tags inside comments

### ISSUE THREAD

**Issue by Mottie** [StylishThemes/GitHub-Dark#255]
```js
/**
 * this function does stuff
 * @memberof plugin
 * @private
 * @param {elementObject} a
 * @param {elementObject} b
 * @returns {number}
 */
```

I plan to add `.pl-c span` to all theme definitions. Hopefully this covers other issues with comments that might pop up; e.g.

```css
/* twilight */
.pl-c, .pl-c span {
  color: #5F5A60 !important;
  font-style: italic !important;
}
```
