### ISSUE TITLE
suggestion: monospace input fields

### ISSUE THREAD

**Issue by boneskull** [StylishThemes/GitHub-Dark#285]
Typically when I create issues, I'm writing code.  If I'm writing code, I'm using a monospace font.  GitHub's input fields do not use a monospace font.  Hence, it's a pain in the ass to get indents correct.

Attached is a screenshot of me writing this issue with the following modification to the style:

```css
textarea {
  font-family: Menlo, Inconsolata, "Droid Mono", monospace !important;
  font-size: 1em !important;
}                       
```

Granted, a better solution would be to use GreaseMonkey and inject an Ace or CodeMirror editor here.

This would be an "opinionated" change and would probably bother some people.  If you aren't amenable to the idea, I can publish a style which simply does the above, and use both of them (assuming that works).

![image](https://cloud.githubusercontent.com/assets/924465/12822853/c7ec97b0-cb1e-11e5-9eb6-0cb476048454.png)
