### ISSUE TITLE
Reactions Widget in the Comment Header

### ISSUE THREAD

**Issue by simov** [StylishThemes/GitHub-Dark#292]
Not an actual issue, just putting it here in case anyone else thinks that the new reactions widget take too much space:

![reactions](https://cloud.githubusercontent.com/assets/1694112/13700486/c6c613d4-e789-11e5-8889-bde8d94fb3d7.png)

```css
.timeline-comment { position: relative; }
.comment-reactions { position: absolute; top: 0; left: 45%; border: 0 !important; }
.comment-reactions:hover .reaction-popover-container { display: none; }
.comment-reactions .reaction-popover-container { display: none; }
.comment-reactions .reaction-summary-item { background: none !important; border: 0; padding: 10px 0 8px 0; }
```

As you can see the first comment is from a user with a fairly long username, so with this positioning the reactions widget won't overlap with that text in most of the cases. I also disabled the reactions button while hovering over the reactions widget, because that's redundant with the one found in the header.

**Comment by silverwind** [comment]
Wait, where are these header icons coming from? Is that another script/addon? Github normally has them in the footer and we don't move them.

**Comment by simov** [comment]
:laughing: Yep, I moved the reactions widget using the above CSS code snippet. I just have my own Chrome extension for adding styles, so I'm appending my own fixes after the GitHub-Dark styles. I'm just sharing this fixes in case anyone else need it, feel free to close the issue :)

**Comment by silverwind** [comment]
Ah I see. The way you did it seems a bit to much of a hack to me :wink:. I think a better way would be to re-parent `.comment-reactions` to the header through JS.

**Comment by Mottie** [comment]
It needs a little adjusting... 

* The background needs to be transparent
* As you can see it covers up the "StylishThemes member" label, and moving it too far to the right covers up the time stamp

    ![2016-03-11 07_37_30-reactions widget in the comment header issue 292 stylishthemes_github-dark](https://cloud.githubusercontent.com/assets/136959/13703547/864b30d2-e75c-11e5-80cf-aec0b75cb715.png)

* A smaller font-size might fix some of these issues.

**Comment by simov** [comment]
@silverwind  Sure using JS would produce more stable results, but I want a CSS only solution. You just need to float the widget after re-appending it.

@Mottie yep, not perfect, that was just a 5min fix on my end, I want to give it some time and see if I like it. My main problem was that having a bunch of icons after comments is too much.

**Comment by Mottie** [comment]
That's cool. I don't mind it so much since it only appears on a few posts, and it is easier to see while scrolling down through a bunch of comments.

If others like this change, maybe we can make another Stylish script for it.

**Comment by silverwind** [comment]
The issue with that method is you never know how wide the labels will be. Another idea would be to move the icons outside the comment container, below the avatar looks to be a good place. Maybe even add IOS-style counters (the red boxes) to the emoji.

Oh, and image emoji would be preferred over unicode for Windows users, but I alread ranted on Hacker News about that. :D

**Comment by Mottie** [comment]
LOL... I was just looking yesterday if it was possible to add an EmojiOne font to Windows; but I think it'll be monochromatic, so <img title=":_cry:" src="https://cloud.githubusercontent.com/assets/136959/13512303/638c0a7e-e15f-11e5-83ab-bb898da7d97d.gif">.

**Comment by simov** [comment]
Now that's just better!

![memes](https://cloud.githubusercontent.com/assets/1694112/13705934/adf753c8-e7ab-11e5-9958-9e287a384a13.png)

https://gist.github.com/simov/ade465a044e2f684903a .. or it's just my twisted mind :laughing: 

BTW having the reactions under the avatar won't work for single line comments, I think. Also didn't know that GitHub supports animated emoticons.

**Comment by silverwind** [comment]
Pushed https://github.com/StylishThemes/GitHub-Dark/commit/27c92b6b596178a88db5c4b8c1a9ccc943550688 to remove some of that excessive padding on reactions and center both the icon and the counter vertically:

![](https://cloud.githubusercontent.com/assets/115237/13706693/70fb8d90-e7a6-11e5-8c00-bd940d622ca6.png)

**Comment by Mottie** [comment]
What do you guys think of this?

![reactions](https://cloud.githubusercontent.com/assets/136959/13711417/089eb546-e784-11e5-8489-020b7dc22a29.gif)

```css
.timeline-comment {
  position: relative !important;
}
.comment-reactions {
  position: absolute !important;
  right: 102% !important;
  top: 50px !important;
  border: 0 !important;
}
.comment-reactions-options {
  border: 0 !important;
  background: transparent !important;
  min-width: 70px !important;
  max-width: 95px !important;
  font-size: 0.8em !important;
}
.comment-reactions-options button.btn-link {
  display: block !important;
  border: 0 !important;
  padding: 0 2px !important;
  float: right !important;
}
.dropdown.left.reaction-popover-container {
  position: absolute !important;
  top: -45px !important;
  left: -40px !important;
}
```

**Comment by Mottie** [comment]
Actually, that breaks when there are more than 10 reactions...

This version looks funny because  of the spacing between reactions when there are only a few

![2016-03-11 12_36_51-reactions widget in the comment header issue 292 stylishthemes_github-dark](https://cloud.githubusercontent.com/assets/136959/13711799/14fec194-e786-11e5-97f4-5713d759c22f.png)

```css
.timeline-comment {
  position: relative !important;
}
.comment-reactions {
  position: absolute !important;
  right: 102% !important;
  top: 50px !important;
  border: 0 !important;
  width: 100px !important;
}
.comment-reactions-options {
  border: 0 !important;
  background: transparent !important;
  font-size: 0.8em !important;
}
.comment-reactions-options button.btn-link {
  display: block !important;
  border: 0 !important;
  padding: 0 2px !important;
  float: right !important;
}
.comment-reactions-options button.btn-link:nth-child(even) {
  float:none !important;
}
.dropdown.left.reaction-popover-container {
  position: absolute !important;
  top: -45px !important;
  left: -10px !important;
}
```

**Comment by simov** [comment]
Looks like e good alternative to have the reactions under the avatar. My only suggestion would be to remove the hover state for showing the reaction button, because you already have that button inside the comment's header. And this button is used only for adding new type of reaction anyway - you can click on already used reaction type for that comment and your vote will be added there.

Another possible problem would be when you have a really long comment, blog post like, in this case you'll want to have the reaction buttons at the bottom, although such long comments are rare.

**Comment by simov** [comment]
Yet another approach would be to make the reactions widget smaller and move it inside the comment at the bottom:

![reactions-bottom](https://cloud.githubusercontent.com/assets/1694112/13722471/cbf9c9c4-e84f-11e5-9e6f-d69bf3cc13b0.png)

```css
.timeline-comment { position: relative; }

.comment-reactions {
  position: absolute; bottom: 0; right: 0;
  border-left: 1px solid #e5e5e5; border-top-left-radius: 5px;
}
.comment-reactions .js-pick-reaction { float: left; }
.comment-reactions .reaction-summary-item {
  font-size: 10px; line-height: 1rem !important;
}
.comment-reactions .reaction-summary-item g-emoji { font-size: 15px; }
.comment-reactions .add-reaction-btn { opacity: 1 !important; }
```

**Comment by simov** [comment]
Yet another approach to handle icons inside the comment's header:

![memes2](https://cloud.githubusercontent.com/assets/1694112/13722610/5735e7b2-e854-11e5-862b-94ae59b75e39.png)

```css
.comment-reactions {
  position: absolute; top: 0; left: 40%;
  border: 0 !important; margin-top: 5px;
}
.comment-reactions .reaction-summary-item {
  width: 25px;
  background: none !important; border: 0; padding: 8px 0 0 0 !important;
}
.comment-reactions .reaction-summary-item g-emoji { display: none; }
.comment-reactions .add-reaction-btn { display: none; }
```

**Comment by simov** [comment]
With this fix:

```css
.timeline-comment { position: relative; }

.comment-reactions {
  width: 170px; text-align: center;
  position: absolute; top: 0; left: 37%;
  border: 0 !important; margin-top: 5px;
}
.comment-reactions .reaction-summary-item {
  width: 25px; display: inline-block; float: none;
  background: none !important; border: 0; padding: 8px 0 0 0 !important;
}
.comment-reactions .reaction-summary-item g-emoji { display: none; }
.comment-reactions .add-reaction-btn { display: none; }
```

The icons are being centered based on their count:

![1](https://cloud.githubusercontent.com/assets/1694112/13722918/8d117d70-e85d-11e5-8162-9ffaec4a3ab6.png)

![2](https://cloud.githubusercontent.com/assets/1694112/13722919/957f7912-e85d-11e5-8186-5632bdd072a8.png)

The only problem is that they are with fixed size :)
