### ISSUE TITLE
Custom fonts

### ISSUE THREAD

**Issue by Mottie** [StylishThemes/GitHub-Dark#294]
I saw this Stylish theme: https://userstyles.org/styles/106779/github-mod that is loading in custom fonts on GitHub, I wonder if that works...

I didn't think it would because of the CSP; and the stylesheet, at least on Chrome, is being injected into the page so it doesn't get loaded by the addon.

Something to check when I have more time.

**Comment by silverwind** [comment]
Current CSP is `font-src assets-cdn.github.com; form-action 'self' github.com gist.github.com`

**Comment by Mottie** [comment]
It works!... but only with the Stylish addon.

I added this font to the Stylish Editor for GitHub Dark, and it does change the headers:

```css
@font-face {
  font-family: 'Indie Flower';
  font-style: normal;
  font-weight: 400;
  src: local('Indie Flower'), local('IndieFlower'), url(https://fonts.gstatic.com/s/indieflower/v8/10JVD_humAd5zP2yrFqw6ugdm0LZdjqr5-oayXSOefg.woff2) format('woff2');
  unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2212, U+2215, U+E0FF, U+EFFD, U+F000;
}
h1 {
  font-family: 'Indie Flower' !important;
}
```

The `@font-face` css is obtained from going to the url provided by [google fonts](https://www.google.com/fonts):

    https://fonts.googleapis.com/css?family=Indie+Flower

**Comment by Mottie** [comment]
It looks like GitHub changed their base font around. I've notice this change in the markdown definition:

```css
.markdown-body {
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol";
}
```

About 2 months ago, it was:

```css
.markdown-body{
  font-family:"Helvetica Neue", Helvetica, "Segoe UI", Arial, freesans, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol";
}
```

Someone in the [userscripts forum](https://forum.userstyles.org/discussion/50531/x) thought we made the change. Should we include an option to change the regular font as well?
