### ISSUE TITLE
hue-rotate .output_area img

### ISSUE THREAD

**Issue by sharethewisdom** [StylishThemes/GitHub-Dark#297]
I usually like graphs and images to retain their original color palette, particulary:
```css
  .output_area img, .top-domains-icon[alt*="."] {
    -webkit-filter: invert(100%) hue-rotate(180deg)!important;
  }
```
Is it really important to `match white to #181818`, as stated in the comment?

**Comment by silverwind** [comment]
Example?

**Comment by sharethewisdom** [comment]
I accidentally closed this, but it's not important anyway, do let me know if you agree...

**Comment by Mottie** [comment]
Hmm, what do you think of these settings?

```css
.output_area img, .top-domains-icon[alt*="."] {
    -webkit-filter: invert(90%) hue-rotate(180deg) brightness(85%) !important;
}
```

It makes the blue and red a little darker.
