### ISSUE TITLE
Support for addon Github Awesome Autocomplete

### ISSUE THREAD

**Issue by charlesmilette** [StylishThemes/GitHub-Dark#298]
### Feature Request
Add support of the addon [Github Awesome Autocomplete](https://github.com/algolia/github-awesome-autocomplete).

Doesn't look great currently:
![picture](https://cloud.githubusercontent.com/assets/6440374/13990137/a00da374-f0e9-11e5-9f7d-21b930aad646.PNG)

Cross-post from [here](https://github.com/algolia/github-awesome-autocomplete/issues/34)

**Comment by redox** [comment]
I'll submit a PR :+1:

**Comment by silverwind** [comment]
Make sure it follows the general color scheme. e.g. `#181818` background, `#343434 border`, `#c0c0c0` bright text, `#808080` faded text. Also, make it it's own section in the style, like we do for ZenHub, for example.

**Comment by Mottie** [comment]
Actually, if there is a way to use the same, or similar, class names that GitHub uses, you won't have to do much.

For example, we have a definitions already targeting GitHub's navigation menus; these are their settings:

```css
.select-menu-modal {
  background: #1b1b1b;
  color: #a0a0a0;
  border: #343434;
}
.select-menu-item {
  border-color: #484848;
}
.select-menu-item.selected, .select-menu-item.navigation-focus {
  background: $user_selected_color;
  color: #e0e0e0;
}
```
