### ISSUE TITLE
ZenHub switch repo icon

### ISSUE THREAD

**Issue by rayrutjes** [StylishThemes/GitHub-Dark#303]
The picture speaks for itself:
![image](https://cloud.githubusercontent.com/assets/5570853/14029174/f2b81768-f200-11e5-872e-bcece0972dd0.png)

Tested on chrome

**Comment by Mottie** [comment]
LOL, it's kinda fugly to begin with... all we did was make it dark.

**Comment by rayrutjes** [comment]
Ok, nevermind then, let's close it for now!

**Comment by Mottie** [comment]
I guess we could remove the margin/padding and make things line up a bit.

**Comment by silverwind** [comment]
Better report it to ZenHub itself if it shows without the theme too.

**Comment by rayrutjes** [comment]
![image](https://cloud.githubusercontent.com/assets/5570853/14029631/8124c760-f203-11e5-9f15-f9b9620dd2bc.png)
It does, and my eyes suffered again from that native white :weary:

**Comment by Mottie** [comment]
There, try those changes... just some minor tweaks that can be removed if ZenHub ever changes it.

**Comment by rayrutjes** [comment]
On chrome it is perfect with:
```css
.zh-repo-switcher .select-menu-button {
    padding: 5px 4px 0px 4px !important;
}
```
Actual:
```css
.zh-repo-switcher .select-menu-button {
    padding: 2px 4px 0px 4px !important;
}
```

What about Firefox?
