### ISSUE TITLE
Make the colour of the selected tab less opaque.

### ISSUE THREAD

**Issue by PJB3005** [StylishThemes/GitHub-Dark#314]
### Feature Request
I'm talking about this: ![](http://i.imgur.com/3vKIGHn.png)

If it were less opaque the background image would be visible through it, which (IMO) would look nicer.

**Comment by silverwind** [comment]
I fear that's not possible to do, because once you add transparency, the (ugly) line below, which creates the tab effect will show. I've yet to find a solution to this problem.

**Comment by PJB3005** [comment]
Ah, that's a shame.

**Comment by Mottie** [comment]
Well, if we set the selected tab background to transparent. You can see the bottom border of the `pagehead`:

![transparent](https://cloud.githubusercontent.com/assets/136959/15458032/a665eb3c-205a-11e6-95db-254d23ce24bb.png)

maybe we could remove the bottom border of the `pagehead` and selected tab, then add a bottom border to non-selected tabs:

```css
.pagehead, .reponav-item.selected {
  border-bottom-width: 0 !important;
}
.reponav-item.selected {
  background-color: transparent !important;
}
a.reponav-item:not(.selected) {
  border-bottom: #222 1px solid;
}
```

The border bottom isn't so obvious with the default background

![default background](https://cloud.githubusercontent.com/assets/136959/15458225/cac7e078-205c-11e6-8363-be688804fec6.png)

But it much more obvious with other background images

![alt background](https://cloud.githubusercontent.com/assets/136959/15458219/bb2f3300-205c-11e6-888f-65a6c1d0420e.png)

What do you think @silverwind?

**Comment by silverwind** [comment]
@Mottie that won't really work, because the left and right sides of the tab bar then have no border, which doesn't look that great. Also the borders aren't really exact that way:

![](https://cloud.githubusercontent.com/assets/115237/15629578/a004e452-251c-11e6-95d6-c07b5d199942.png)

Unfortunately, I think this issue is not solveable. Here's the CSS from above screenshot:

```css
.pagehead, .reponav-item.selected {
    border-bottom-width: 0 !important;
  }
  .reponav-item.selected {
    background-color: transparent !important;
  }
  a.reponav-item:not(.selected) {
    border-bottom: 1px solid #343434 !important;
  }
```
