### ISSUE TITLE
Feature Request: Make it Responsive (add media query break points)

### ISSUE THREAD

**Issue by jakejohns** [StylishThemes/GitHub-Dark#334]
### Feature Request: Make Github Responsive
GH Minimum width is something like `980px`,
which is annoying for those times I have multiple windows tiled horizontally.

#### Example:
![gh-should-be-responsive](https://cloud.githubusercontent.com/assets/174708/16246992/bb7d1b2a-37d5-11e6-93aa-8fcffd023ca5.png)

#### Solution: [Media query break points](http://www.w3schools.com/css/css_rwd_mediaqueries.asp)
I would think we could just add some media query break points for the `.container` element, eg:
```css
.container {width:240px!important;}
@media only screen and (min-width: 340px) { .container {width:320px!important;} }
@media only screen and (min-width: 500px) { .container {width:490px!important;} }
@media only screen and (min-width: 600px) { .container {width:590px!important;} }
@media only screen and (min-width: 700px) { .container {width:680px!important;} }
@media only screen and (min-width: 790px) { .container {width:780px!important;} }
@media only screen and (min-width: 850px) { .container {width:840px!important;} }
@media only screen and (min-width: 980px) { .container {width:980px!important;} }
```

However, I was unsuccessful in my initial attempt.
It seems that something within a container somewhere really wants to be wide.

Does anyone else share my desires?
Has anyone attempted this?
