### ISSUE TITLE
Too dark code selection

### ISSUE THREAD

**Issue by un1versal** [StylishThemes/GitHub-Dark#339]
### Unstyled Content

- [x] No other existing issue and/or pull request.
- [x] URL of unstyled content.
- [ ] If unable to provide a URL, please report the class name of unstyled content.
- [x] Provide steps to reproduce (opening a dialog, etc).

URL for test https://github.com/StylishThemes/GitHub-Dark/blob/master/.stylelintrc

So this is pretty simple I provide animated examples of styles vs unstyled
Essentially the selection color when styled is too dim and blick or have less than 20/20 eye sight and you may miss it.

![githubtoodarkcodeselection](https://cloud.githubusercontent.com/assets/3521959/16789301/5ee6db6e-48a4-11e6-8d75-5cb195b0d95d.gif)

![githubtoodarkcodeselectionstyled](https://cloud.githubusercontent.com/assets/3521959/16789302/5eeb3cea-48a4-11e6-9e62-fd44105d8779.gif)

I would suggest making the selection and even the scroll lighter are (idk what its called) more obvious
and please consider changing the tone of the yellows used or allowing configuration as its just slightly bleh.

But other than that looks pretty good, I was surprised to see this was so well conceived.

**Comment by silverwind** [comment]
Agree, we need a better shade of yellow there. The issue is that dark yellows usually look pretty meh, but I'll try find something better.

**Comment by un1versal** [comment]
Thanks, the yellows in general used (in other parts as well) are generally meh, and visibility depends in part on the code highlighting type used.

What I suggest is a different approach perhaps like doing a yellow more like the unstyled portion with black letters, since black and yellow have great contrast together this could work better perhaps all around. (maybe?)

If I knew where to look I may have a go with different variations, css however is really something I really dont understand.

**Comment by Mottie** [comment]
Yeah, maybe we should just stick with grey since it depends on the syntax theme.

If you look at these lines for the definition:

[197273](https://github.com/StylishThemes/GitHub-Dark/blob/master/github-dark.css#L1972-L1973) (highlight)

```css
  /* code and diff line selection */
  pre div[style^="background-color: rgb(248, 238, 199)"],
  .highlight td[style^="background-color: rgb(248, 238, 199)"],
  td.selected-line.blob-num, td.selected-line.blob-code {
    background: #262600 !important;
    border-color: #662 !important;
  }
```

[2374](https://github.com/StylishThemes/GitHub-Dark/blob/master/github-dark.css#L2374) (hovered highlight)

```css
  .highlight:not(.lines) tr:not(.inline-comments):hover td.selected-line.blob-num:not(.line-age),
  .highlight:not(.lines) tr:not(.inline-comments):hover td.selected-line.blob-code:not(.line-age),
  .highlight tr:not(.inline-comments):hover td[style^="background-color: rgb(248, 238, 199)"] {
    background: #363610 !important;
  }
```
