### ISSUE TITLE
Unstyled content on Pull discussion pages: discussion-item-deployed

### ISSUE THREAD

**Issue by engelju** [StylishThemes/GitHub-Dark#342]
### Unstyled Content

- [x] No other existing issue and/or pull request.
- [x] URL of unstyled content: https://github.com/unicodeveloper/laravel-hackathon-starter/pull/14
- [x] If unable to provide a URL, please report the class name of unstyled content:
```css
.discussion-item-deployed {
    padding-top: 15px;
    border-top: 1px solid #f5f5f5;
}
```

should be:

```css
.discussion-item-deployed {
    padding-top: 15px;
    border-top: 1px solid #444;
}
```
