### ISSUE TITLE
Scrollbar styling

### ISSUE THREAD

**Issue by un1versal** [StylishThemes/GitHub-Dark#354]
### Unstyled Content
- [x] No other existing issue and/or pull request.
### Feature Request

If its possible to style the Horizontal / vertical scrollbars please consider it.

**Comment by Mottie** [comment]
Hi @un1versal!

This is [already in place for webkit browsers](https://github.com/StylishThemes/GitHub-Dark/blob/master/github-dark.css#L2412-L2427). Sadly Firefox [does not currently provide a way to style the scrollbars](https://bugzilla.mozilla.org/show_bug.cgi?id=77790).

I found this [interesting codepen](https://codepen.io/solipsistacp/pen/cyglb) that does style the scrollbars in Firefox, but it uses `mix-blend-mode: difference;` on the entire element which isn't a feasible solution in this situation.

**Comment by un1versal** [comment]
I thought it was a little premature closing this when firefox is left out at this time.

**Comment by Mottie** [comment]
True, sorry about that.

**Comment by silverwind** [comment]
Userstyles with `AGENT_SHEET` can style scrollbars just fine in Firefox, it's just that the stylable elements are not exposed to content stylesheets.

Still I'd question if we really want to do this at all. Styling scrollbars is very opinionated and in Chrome, it break CTRL-F highlight on the scrollbar. I'd rather remove any such styling and let the user decide for themselves.

Example Firefox style (I'm using it for all sites): https://github.com/silverwind/overlay-scrollbars/blob/master/overlay-scrollbars.css

**Comment by Mottie** [comment]
The <kbd>Ctrl</kbd>+<kbd>F</kbd> highlights can be fixed by making the thumb semi-transparent. That's how it is set in the [scrollbar style for Chrome](https://github.com/StylishThemes/GitHub-Dark/blob/master/github-dark.css#L2421-L2427).

```css
  ::-webkit-scrollbar-thumb {
    border-radius: 5px !important;
    background: rgba(80,80,80,.6) !important;
  }
  ::-webkit-scrollbar-thumb:hover {
    background: rgba(96,96,96,.6) !important;
  }
```
