### ISSUE TITLE
Too dark placeholder text

### ISSUE THREAD

**Issue by un1versal** [StylishThemes/GitHub-Dark#359]
### Unstyled Content

- [x] No other existing issue and/or pull request.
- [ ] URL of unstyled content.
- [ ] If unable to provide a URL, please report the class name of unstyled content.
- [ ] Provide steps to reproduce (opening a dialog, etc).

Any placeholder text, in any input fields (except issue filter) is far too dark, dont ask for class names, I tried finding them to no success,

here is a couple of examples but many many more around

![capture](https://cloud.githubusercontent.com/assets/3521959/17092288/727798d2-5239-11e6-9f24-712f64291a34.PNG)
![capture1](https://cloud.githubusercontent.com/assets/3521959/17092287/7277931e-5239-11e6-9d30-9784018b2e0f.PNG)

**Comment by silverwind** [comment]
Relevant styles from GitHub's sheet:
```css
::-webkit-input-placeholder {
  color:inherit;
  opacity:0.54
}

::-webkit-input-placeholder {
  color:#999
}
::-moz-placeholder {
  color:#999
}
:-ms-input-placeholder {
  color:#999
}
::placeholder {
  color:#999
}

.select-menu-text-filter input::-webkit-input-placeholder {
  color:#aaa
}
.select-menu-text-filter input::-moz-placeholder {
  color:#aaa
}
.select-menu-text-filter input:-ms-input-placeholder {
  color:#aaa
}
.select-menu-text-filter input::placeholder {
  color:#aaa
}
````
The first rule is pointless there is it gets overridden by the second one. I wouldn't call our colors (`#444`) "far too dark", but we can bump them up a notch.
