### ISSUE TITLE
Word highlight selection for ace editor find/se has great lack of contrast.

### ISSUE THREAD

**Issue by un1versal** [StylishThemes/GitHub-Dark#401]
**To reproduce**
1. Edit any file via in a GitHub repo via Web Browser 
2. Click inside the Ace Editor window to assign focus
3. Press Ctrl+F to bring up the Ace editor Search/Find and use it to highlight a word.

![store](https://cloud.githubusercontent.com/assets/3521959/18301811/16ee889e-74cc-11e6-95e2-981ffb1dcc52.gif)

the unstyled counterpart has significant more contrast vs styled.

**Comment by Mottie** [comment]
Hi @un1versal!

We don't modify existing Ace Editor themes.

If you want to modify that specific selected word within the line highlight, then target this css selector in a custom style... I'm guessing you're still using Merbivore?

```css
.ace_editor .ace_marker-layer .ace_selection {
    background: #454545 !important;
}
```

The current line selector is set to 

```css
.ace_editor .ace_marker-layer .ace_active-line {
    background: #333435 !important;
}
```

I guess we do have one ace editor style definition (besides the font family setting) which highlights the found words that *are not* on the current line:

```css
  /* ace find highlight */
  .ace_editor .ace_marker-layer .ace_selected-word {
    background: transparent !important;
    border: 1px solid /*[[base-color]]*/ #4183C4 !important;
  }
```

Mostly because some styles add a white background.

Really, if you're having this much trouble with the Merbivore theme, try something else. I'm am quite content with the Twilight theme.
