### ISSUE TITLE
"First repository" text misses margin-top 

### ISSUE THREAD

**Issue by Spidersouris** [StylishThemes/GitHub-Dark#450]
- [x] I am using the most up-to-date GitHub Dark style!

- [x] No other existing issue and/or pull request.

https://github.com/Spidersouris?tab=overview&from=2016-04-08

**Comment by Mottie** [comment]
Hi @Spidersouris!

Thanks for letting us know, I'll have it fixed shortly.

**Comment by silverwind** [comment]
@Mottie:

````css
contribution-first-repository { opacity: .999 !important }
````
