### ISSUE TITLE
New `topic-tags` are unstyled

### ISSUE THREAD

**Issue by OvermindDL1** [StylishThemes/GitHub-Dark#459]
### Unstyled Content

- [X] I am using the most up-to-date GitHub Dark style!  (Tampermonkey/Chrome reports no update)

> if using the GitHub Dark script, use the "Force Update Style" button.

Done, no change

- [X] No other existing issue and/or pull request:  None found via search
- [X] Provide the URL of the unstyled content:  https://github.com/BubuAnabelas/awesome-markdown/
- [X] If unable to provide a URL, please report the class name of unstyled content:  N/A

On the page starting today I've found Github showing tags for various repositories, both when I am logged in and logged out.  It is below the title of a repo:
![image](https://cloud.githubusercontent.com/assets/401605/22489442/ce1a9096-e7d4-11e6-9816-9da42bb620cf.png)

The Inspector information is:
![image](https://cloud.githubusercontent.com/assets/401605/22489485/f91425c8-e7d4-11e6-93d4-b5ba0c9e00b4.png)
However that is huge and unreadable, so here is just the useful parts as text:
```css
.topic-tag {
    display: inline-block;
    padding: 0.2em 0.9em;
    margin: 0 0.5em 0.5em 0;
    white-space: nowrap;
    background-color: #f2f8fa;
    border-radius: 3px;
}
```

- [X] Provide steps to reproduce (opening a dialog, etc).

Go to:  https://github.com/BubuAnabelas/awesome-markdown/
Or any of the other dozen Repo's I've seen with these tags.
