### ISSUE TITLE
Can the transparent image background be made configurable?

### ISSUE THREAD

**Issue by xt0rted** [StylishThemes/GitHub-Dark#463]
### Unstyled Content

- [x] I am using the most up-to-date GitHub Dark style!

  

- [x] No other existing issue and/or pull request.
- [ ] Provide the URL of the unstyled content.
- [x] If unable to provide a URL, please report the class name of unstyled content.

  

- [x] Provide steps to reproduce (opening a dialog, etc).

### Feature Request
One of my repos has svg icons & logos in it which by default are black. As a result viewing them in diffs is really difficult because we're setting the background image on these to one that's dark so the icons blend in. You can see an example of this in GitHub's own [octicons repo](https://github.com/primer/octicons/tree/master/lib/svg).

This background image is used when viewing images and in diffs. What I'd like to see is this being made configurable so you could use the dark style as we have now, or turn it off to use GitHub's default.

![image](https://cloud.githubusercontent.com/assets/831974/22997007/c6a3a106-f39e-11e6-94df-2c9ed7c4ab86.png)

**Comment by silverwind** [comment]
I guess we could also go with a middle ground grey, given that images like those usually are either white or black.

**Comment by Mottie** [comment]
I was thinking was could do the same was with the wikipedia images... invert (or remove in this case) the background image on click when they are `:active`.

**Comment by xt0rted** [comment]
For now I've added a custom rule to set it back to the light background.
```css
.render-shell .img-view img, .file .image img, .file .image canvas,
img.asset, .render-shell img:not(.math) {
  background-image: url(data:image/gif;base64,R0lGODlhCgAKAIAAAOXl5f///yH5BAAAAAAALAAAAAAKAAoAAAIRhB2ZhxoM3GMSykqd1VltzxQAOw==) !important;
}
```

**Comment by Mottie** [comment]
What do you think of this color combo for a grid background? It's using `#808080` and `#4d4d4d`.

```css
  .render-shell .img-view img, .file .image img, .file .image canvas, img.asset,
  .render-shell img:not(.math) {
    background-image: url("data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMCIgaGVpZ2h0PSIxMCIgdmlld0JveD0iMCAwIDIgMiI+PHBhdGggZmlsbD0iZ3JheSIgZD0iTTAgMGgydjJIMHoiLz48cGF0aCBmaWxsPSIjNGQ0ZDRkIiBkPSJNMCAwaDF2MUgwem0xIDFoMXYxSDF6Ii8+PC9zdmc+") !important;
  }
```

Screenshot page: https://github.com/StylishThemes/logos/blob/master/github.dark/githubdark.svg

Before:

![2017-03-16 14_22_55-logos_githubdark svg at master stylishthemes_logos](https://cloud.githubusercontent.com/assets/136959/24014794/35e0a3f4-0a54-11e7-80c3-09f3dc7e1f8c.png)

After:

![2017-03-16 14_20_58-logos_githubdark svg at master stylishthemes_logos](https://cloud.githubusercontent.com/assets/136959/24014675/d2ed1a02-0a53-11e7-8e43-83055b145594.png)

Or, maybe we could just remove the grid pattern altogether and make the background color something like `#7f7f7f`?

![2017-03-16 14_27_14-logos_githubdark svg at master stylishthemes_logos](https://cloud.githubusercontent.com/assets/136959/24014926/c3454678-0a54-11e7-83ee-4d68c6dffa70.png)
