### ISSUE TITLE
How to disable highlight when mouse point the code?

### ISSUE THREAD

**Issue by Too-Naive** [StylishThemes/GitHub-Dark#469]
In daily use, I found that if mouse keep moving and point code line, CPU usage will raise.
So I want to Close this feature.

Can you help me to solve this? Or add a switch etc. 😄 
Thank you!

**Comment by silverwind** [comment]
You could create a second style for github.com with this content:

```css
body .highlight tr:hover .blob-num:not(.non-expandable),
body .highlight tr:hover .blob-num:not(.non-expandable):before {
  color: #7b7b7b !important; 
}

body .diff-table tr:hover > pre,
body .highlight:not(.lines) tr:not(.inline-comments):hover td:not(.line-age):not([style^="background-color: rgb(248, 238, 199)"]) {
  background: none !important;
}
```

But maybe we'll add an option. 😉
