### ISSUE TITLE
Support new color boxes

### ISSUE THREAD

**Issue by silverwind** [StylishThemes/GitHub-Dark#487]
Some CSS color code blocks now include a color preview, we should handle them. Examples:

- `#f1a`
- `#ff11aa`
- `#ff11aaff`
- `rgba(255, 17, 170)`
- `rgba(255 ,17, 170, 255)`
- `hsl(321, 100%, 53%)`
- `hsla(321, 100%, 53%, 255)`

**Comment by Mottie** [comment]
Interesting... they must have added this today... the colors do not appear to effect code blocks though:

```css
.style {
  background: #123456;
  color: rgb( 255,128,64);
  border-left: 1px hsla(65, 100%, 50%, 1) solid;
  border-right-color: maroon;
  box-shadow: 3px 3px hsl( 128, 30%, 50% );
  text-shadow: 2px 5px rgba(255, 0,  183,0.5);
}
```
