### ISSUE TITLE
Black Label

### ISSUE THREAD

**Issue by Mottie** [StylishThemes/GitHub-Dark#491]
A black issue label highlights differently in the label dropdown... opening an issue as a reminder.

```css
.label-select-menu .labelstyle-000000.selected {
    background: rgba(247, 247, 247, 1.0) !important;
    color: #666666 !important;
}
```
