### ISSUE TITLE
Unreadable highlights

### ISSUE THREAD

**Issue by casz** [StylishThemes/GitHub-Dark#511]
Noticed that highlights recently got unreadable without hovering over the text. Using the Monokai theme but is seems to be the same with a few other themes.

Using the Github-Dark script and tried Force Update Style

* **Browser**: Chrome 59.0.3071.115

* **Operating System**: Windows 10 1607
* **Screenshot**:

![image](https://user-images.githubusercontent.com/1661688/28159028-e3247c24-67bb-11e7-8347-b4531bcb548f.png)

* **HTML of the section where the issue occurs**:

````html
<tr>
        <td id="L95" class="blob-num js-line-number" data-line-number="95"></td>
        <td id="LC95" class="blob-code blob-code-inner js-file-line highlighted">            <span class="pl-k">if</span> (scmSource<span class="pl-k">.</span>buildBitbucketClient() <span class="pl-k">instanceof</span> <span class="pl-smi">BitbucketCloudApiClient</span>) {</td>
</tr>
````

**Comment by Mottie** [comment]
Hi @casz!

I'm not seeing this problem, but it looks like GitHub added a new "highlighted" class instead of directly adding a background color. Actually, I'm not seeing any highlight at all because we are using selectors that target the style ([ref](https://github.com/StylishThemes/GitHub-Dark/blob/master/github-dark.css#L2559-L2566)):

```css
  pre div[style^="background-color: rgb(248, 238, 199)"],
  .highlight td.blob-code-inner[style^="background-color: rgb(255, 251, 221)"],
  .highlight td.blob-code-inner[style^="background-color: rgb(248, 238, 199)"],
  .line[style^="background-color: rgb(255, 255, 204)"],
  td.selected-line.blob-num, td.selected-line.blob-code {
    background: rgba(85, 85, 85, .4) !important;
    border-color: rgba(85, 85, 85, .4) !important;
  }
```

and I also noticed that a `selected-line` is added (for diffs?) by the auto-generator script in [line 3024](https://github.com/StylishThemes/GitHub-Dark/blob/master/github-dark.css#L3024).

```css
  /* auto-generated rule for "background-color: #fff5b1" */
  .bg-yellow-light, .selected-line.blob-num, .network .current-repository,
  .diffbar-range-menu .is-last-in-range {
    background-color: #261d08 !important;
  }
```

Sorry, but I'll have to leave this for @silverwind to take care of since I'll be away from my computer all day today; I'll take care of it late tonight or tomorrow if not.
