### ISSUE TITLE
Unstyled content: Commits by blocked user notification

### ISSUE THREAD

**Issue by SEAPUNK** [StylishThemes/GitHub-Dark#513]
Repro:

1. Block a user that has committed to an external repo
2. Visit the repo

* **Browser**: Chrome
* **Operating System**: OSX
* **Screenshot**:

![screen shot 2017-07-13 at 2 52 43 pm](https://user-images.githubusercontent.com/4400726/28189505-0dd58444-67db-11e7-983d-f6eca5360591.png)

* **HTML of the section where the issue occurs**:

````html
<div class="Box Box-row--yellow border-black-fade Details js-details-container mb-3 js-transitionable open Details--on" aria-expanded="false" style="background-clip: border-box;">
  <div class="d-flex flex-justify-between p-3">
    <div>
        A user you've blocked has previously contributed to this repository.
    </div>

    <div>
      

      <button type="button" class="btn-link link-gray js-details-target" aria-label="Show or hide blocked contributors" aria-expanded="false" data-initial-state="true">
        <span class="Details-content--shown">Expand<svg aria-hidden="true" class="octicon octicon-chevron-down ml-1" height="16" version="1.1" viewBox="0 0 10 16" width="10"><path fill-rule="evenodd" d="M5 11L0 6l1.5-1.5L5 8.25 8.5 4.5 10 6z"></path></svg></span>
        <span class="Details-content--hidden">Collapse<svg aria-hidden="true" class="octicon octicon-chevron-up ml-1" height="16" version="1.1" viewBox="0 0 10 16" width="10"><path fill-rule="evenodd" d="M10 10l-1.5 1.5L5 7.75 1.5 11.5 0 10l5-5z"></path></svg></span>
      </button>
    </div>
  </div>

  <div class="d-flex px-3 pb-3 text-small Details-content--hidden">
      <a class="d-block mr-3 link-gray-dark" href="/nodejs/node/commits?author=someuseriblocked">
        <img alt="@someuseriblocked" class="avatar mr-1" height="20" src="https://avatars0.githubusercontent.com/u/9999999?v=3&amp;s=40" width="20"><strong>someuseriblocked</strong>
      </a>
  </div>

  <div class="Box-row py-2 text-small border-black-fade Details-content--hidden">
    <a href="/settings/blocked_users">Manage blocked users</a> or <a href="/settings/blocked_users#blocked-contributor-warning">disable this warning</a>.
  </div>
</div>
````

**Comment by Mottie** [comment]
Hi @SEAPUNK!

Thanks for reporting this problem.

@silverwind, I was going to try to fix this by adding this line to the `generate.js` file

```js
  "background-color: #fffbdd": "background-color: #261d08",
```

But when I run the script, it includes CodeMirror selectors *and* the row highlight we discussed in #512:

```css
  /* auto-generated rule for "background-color: #fffbdd" */
  .conflict-background+.CodeMirror-gutter-wrapper .CodeMirror-linenumber,
  .conflict-gutter-marker, .Box-row--yellow, .form-group.warn .warning,
  .flash-warn, .warning, .boxed-group-warning, .blob-code-inner.highlighted,
  .selected-line.blob-code, .RecentBranches,
  .diffbar-range-menu .is-range-selected {
    background-color: #261d08 !important;
  }
```

I'm not sure how you are getting around that. So maybe we need to add the selectors instead?
