### ISSUE TITLE
Sticky headers in pull request file list

### ISSUE THREAD

**Issue by xt0rted** [StylishThemes/GitHub-Dark#531]
It'd be really useful if in the pull request file list the headers could be set to sticky so you'd know what file you were looking at when scrolling.

An example of this can be see in the [Refined GitHub](https://github.com/sindresorhus/refined-github) plugin [here](https://user-images.githubusercontent.com/81981/28682784-78bac340-72fe-11e7-9386-bdbab7703693.gif). The behavior of the sticky headers in this plugin doesn't work fully with GitHub Dark because the PR toolbar is shorter resulting in a gap between the toolbar & file header where you can see the file contents scroll on by.

The new css rule would be along the lines of:

```css
@supports (position: sticky) {
  .file-header {
    position: sticky;
    top: 39px !important; /* puts it below the PR tool bar and !important is required for it to work with Refined GitHub */
    z-index: 1; /* brings it in front of the file content under it */
  }
}
```
