### ISSUE TITLE
.markdown-body code {} dark text on dark background

### ISSUE THREAD

**Issue by baccenfutter** [StylishThemes/GitHub-Dark#548]
Text inside markdown files that is enclosed inside two back-ticks will be rendered as `<code></code>` block when the file is rendered in a GH view. They are not readable in the dark theme as they are dark text on dark background. Or is it just me?

```css
.markdown-body code {
  color: #151f29;
}
```

Browser: Chrome Version 61.0.3163.100 (Official Build) (64-bit)
OS: Gentoo AMD64
