### ISSUE TITLE
2FA QR Code - Almost impossible to read

### ISSUE THREAD

**Issue by wolfgangvc** [StylishThemes/GitHub-Dark#557]
Setting up 2 factor authentication is almost impossible while using GitHub-Dark

* **Browser**: Firefox
* **Operating System**: Ubuntu 16.04
* **Screenshot**: Obscured due to security issues
![image](https://user-images.githubusercontent.com/20362791/32944202-9a2a8412-cb86-11e7-9b58-65260b6f5c8e.png)

The dark theme results in the qr code for 2FA being essentially black on black.

**Suggested fix:**

``` CSS
.qr-code-table{
  background-color: #FFF!important;
}  
.qr-code-table .white{
  background-color: #FFF!important;
}
```
Or similar.
