### ISSUE TITLE
Team conversations

### ISSUE THREAD

**Issue by Mottie** [StylishThemes/GitHub-Dark#576]
I saw this [report in the USO forum](https://forum.userstyles.org/discussion/62404/replies-in-discussion-are-still-white#latest) about a white background in discussions... does anyone know how to reproduce it?

I added a comment to the [GitHub Dark team page](https://github.com/orgs/StylishThemes/teams/github), but from the screenshot, it looks like I need someone else from the @StylishThemes/github team to add a comment.

![](https://camo.githubusercontent.com/740149a5314981e6d264ed4a6529c070fb120bc7/68747470733a2f2f66696c652e66757261692e706c2f323031372d31322d31362d32322d33382d32362e706e67)

**Comment by silverwind** [comment]
Maybe its

````css
.discussion-post .reply-comment .review-comment.is-comment-editing {
 padding:0;
 background:#fafbfc
}
````

I'd add a generator rule, maybe mapping it to `#1c1c1c` or similar.
