### ISSUE TITLE
Deployment statuses aren't styled

### ISSUE THREAD

**Issue by xt0rted** [StylishThemes/GitHub-Dark#589]
* **Browser**: Chrome 64
* **Operating System**: Win10
* **Screenshot**:

![image](https://user-images.githubusercontent.com/831974/36764734-fb171d9c-1bfb-11e8-9a12-dff9a5fdb242.png)

* **HTML of the section where the issue occurs**:

https://github.com/integrations/slack/pull/377

````html
<span class="deployment-status-label is-active">Active</span>
````

These can have the following states/colors:

```css
.deployment-status-label.is-error,
.deployment-status-label.is-failure {
  color: #cb2431;
  text-align: center;
}

.deployment-status-label.is-active {
  color: #28a745;
}

.deployment-status-label.is-pending {
  color: #b08800;
}
```
