### ISSUE TITLE
Popup arrow styled incorrectly when on the right side

### ISSUE THREAD

**Issue by xt0rted** [StylishThemes/GitHub-Dark#605]
* **Browser**: chrome 65
* **Operating System**: Win10
* **Screenshot**:

![image](https://user-images.githubusercontent.com/831974/38443143-9f186ba6-39b8-11e8-81d7-57df881be4cd.png)

* **HTML of the section where the issue occurs**:

````html
<div class="dropdown-menu dropdown-menu-w py-0 text-gray-dark text-left">
  <div class="signed-commit-header TableObject">
    <div class="TableObject-item">
      <svg height="32" class="octicon octicon-verified mr-2" viewBox="0 0 16 16" version="1.1" width="32" aria-hidden="true"><path fill-rule="evenodd" d="M15.67 7.06l-1.08-1.34c-.17-.22-.28-.48-.31-.77l-.19-1.7a1.51 1.51 0 0 0-1.33-1.33l-1.7-.19c-.3-.03-.56-.16-.78-.33L8.94.32c-.55-.44-1.33-.44-1.88 0L5.72 1.4c-.22.17-.48.28-.77.31l-1.7.19c-.7.08-1.25.63-1.33 1.33l-.19 1.7c-.03.3-.16.56-.33.78L.32 7.05c-.44.55-.44 1.33 0 1.88l1.08 1.34c.17.22.28.48.31.77l.19 1.7c.08.7.63 1.25 1.33 1.33l1.7.19c.3.03.56.16.78.33l1.34 1.08c.55.44 1.33.44 1.88 0l1.34-1.08c.22-.17.48-.28.77-.31l1.7-.19c.7-.08 1.25-.63 1.33-1.33l.19-1.7c.03-.3.16-.56.33-.78l1.08-1.34c.44-.55.44-1.33 0-1.88zM6.5 12L3 8.5 4.5 7l2 2 5-5L13 5.55 6.5 12z"></path></svg>
    </div>
    <div class="TableObject-item--primary">
          This commit was created on GitHub.com and signed with a <strong class="signed-commit-verified-label">verified signature</strong> using GitHub’s key.
    </div>
  </div>


  <div class="signed-commit-footer">
      <span class="d-block">GPG key ID: <span class="text-gray">4AEE18F83AFDEB23</span></span>
    <a href="https://help.github.com/articles/signing-commits-with-gpg/">Learn about signing commits</a>
  </div>
</div>
````

```css
.Popover-message:before,
.dropdown-menu:before,
.diffbar-range-menu .in-range:not(.navigation-focus):not(.is-range-selected) {
  border-bottom-color: #343434 !important;
}

.Popover-message--right:before,
.Popover-message--right-top:before,
.Popover-message--right-bottom:before,
.dropdown-menu-w:before {
  border-left-color: #343434 !important;
}
```
