### ISSUE TITLE
10 year celebration page looks really bad

### ISSUE THREAD

**Issue by xt0rted** [StylishThemes/GitHub-Dark#607]
* **Browser**: Chrom 65
* **Operating System**: Win10

https://github.com/ten

**Comment by Mottie** [comment]
Hi @xt0rted!

Thanks! I'll get it fixed... err excluded; too many dark background images to bother.

**Comment by xt0rted** [comment]
I just released my first style on userstyles.org, when you make a change like this do you manually update the site or is that automated?

**Comment by Mottie** [comment]
Manually update :(

**Comment by xt0rted** [comment]
Now I feel bad for reporting all those issues 🙁

**Comment by Mottie** [comment]
Naw... we did ask to have [auto-updates from GitHub](https://github.com/stylish-userstyles/userstyles/issues/50), but nothing ever happened.

**Comment by xt0rted** [comment]
I think this change broke some urls, for instance this page isn't styled now but it was an hour ago https://github.com/dncuug/X.PagedList/blob/master/src/X.PagedList/PagedListExtensions.cs

I think it's because of _.../PagedListEx**TEN**sions.cs_

**Comment by xt0rted** [comment]
Here's another that's broke https://github.com/Azure/azure-functions-durable-extension

**Comment by Mottie** [comment]
DOH

**Comment by Mottie** [comment]
Ugh... well, I think we'll just have to deal with it.

I can invert the darker background images with these *ugly* and inefficient selectors:

```css
[class*="TenYear"] svg, [class*="TenYears"] ~ div svg, svg[class*="TenYear"],
  img[src*="tenyear"] ~ svg {
  filter: invert(100%) !important;
}
```

But there isn't much I can do with the humongous image at the top.

**Comment by Mottie** [comment]
Actually, this is better:

```css
/* ==UserStyle==
@name        github.com/ten
@namespace   StylishThemes
@version     1.0.0
@homepageURL https://github.com/StylishThemes/GitHub-Dark/issues/607
@license     CC-BY-SA-4.0
@author      StylishThemes
==/UserStyle== */
@-moz-document url("https://github.com/ten") {
  svg {
    filter: invert(100%) !important;
  }
  img {
    z-index: 100 !important;
  }
}
```

**Comment by the-j0k3r** [comment]
@Mottie naturally fitting when white images burn retinas.

![10-years](https://user-images.githubusercontent.com/31389848/42033150-ccc2adbc-7ad3-11e8-9561-28c4dbad2148.gif)

```css
  img.col-sm-4, img.TenYears-hero {
	mix-blend-mode: color-burn !important;
  }
```

that handles a github.com when logged off 10 year image in same way also.
