### ISSUE TITLE
Blurple

### ISSUE THREAD

**Issue by Mottie** [StylishThemes/GitHub-Dark#608]
Found this while scanning GitHub's stylesheet... not sure if I've seen it anywhere. @silverwind do you think we need to add it?

```css
.btn-blurple {
	color: #fff;
	background-color: #3b41af;
	background-image: linear-gradient(-180deg, #6570e2 0%, #3b41af 90%)
}

.btn-blurple:focus, .btn-blurple.focus {
	box-shadow: 0 0 0 0.2em rgba(101, 112, 226, 0.4)
}

.btn-blurple:hover, .btn-blurple.hover {
	background-color: #383ea7;
	background-image: linear-gradient(-180deg, #5c68e0 0%, #383ea7 90%);
	background-position: -.5em;
	border-color: rgba(27, 31, 35, 0.5)
}

.btn-blurple:active, .btn-blurple.selected, [open]>.btn-blurple {
	background-color: #3a43bb;
	background-image: none;
	border-color: rgba(27, 31, 35, 0.5);
	box-shadow: inset 0 0.15em 0.3em rgba(27, 31, 35, 0.15)
}

.btn-blurple:disabled, .btn-blurple.disabled {
	color: rgba(255, 255, 255, 0.75);
	background-color: #9da0d7;
	background-image: none;
	border-color: rgba(27, 31, 35, 0.2);
	box-shadow: none
}

.btn-blurple .Counter {
	color: #4350dc;
	background-color: #fff
}
```
