### ISSUE TITLE
Show more button on the new dashboard isn't styled on hover

### ISSUE THREAD

**Issue by xt0rted** [StylishThemes/GitHub-Dark#619]
A new dashboard UI was just released and the `Show more` button on it isn't styled on hover.

* **Browser**: Chrome
* **Operating System**: Win10
* **URL**: https://github.com (must be logged in)
* **Screenshot**:

![image](https://user-images.githubusercontent.com/831974/40203308-db60d86e-59f2-11e8-9f71-2a0814510e79.png)

* **HTML of the section where the issue occurs**:

````html
<button name="button" type="submit" class="Box-row--hover-blue f6 btn-link width-full text-left no-underline link-gray border-top p-2 js-details-target js-show-more-recent-items" aria-expanded="false" data-hydro-click="{&quot;event_type&quot;:&quot;dashboard.click&quot;,&quot;payload&quot;:{&quot;event_context&quot;:&quot;RECENT_ACTIVITY&quot;,&quot;target&quot;:&quot;SEE_MORE&quot;,&quot;dashboard_context&quot;:&quot;user&quot;,&quot;dashboard_version&quot;:1,&quot;user_id&quot;:831974,&quot;client_id&quot;:&quot;362802210.1474734994&quot;,&quot;originating_request_id&quot;:&quot;AC38:6437:464B8D:793498:5AFDEAFF&quot;}}" data-hydro-click-hmac="1e31ac6dfc06d2f00591eed6815f76f198d682c1c11f014ae560e8b08a1d754b" data-ga-click="Dashboard, click, Ajax more recent activity link - context:user">
          Show more
</button>
````

**Comment by Mottie** [comment]
Hi @xt0rted!

I just added it in https://github.com/StylishThemes/GitHub-Dark/commit/6b0747e83d2c86937df4b8c1c3cd3a8ee6b25d17... We'll get a new release out when we're sure there aren't more unstyled elements in the updated news feed - I'm not sure I like it.

**Comment by xt0rted** [comment]
I don't think I've ever actually used this page, but it's easy to flip back to the old style.

```css
@-moz-document url("https://github.com/"), regexp("https://github\.com/orgs/.*/dashboard") {
  .dashboard > .dashboard-sidebar {
    float: right !important;
  }

  .dashboard > .news {
    float: left !important;
  }
}
```
