### ISSUE TITLE
Repo list issue on main page

### ISSUE THREAD

**Issue by Mottie** [StylishThemes/GitHub-Dark#632]
I'm not sure if we should add this to GHD, or create a new repo to correct this GitHub problem...

On the main page, the "your" repo list is setting the overflow ellipsis incorrectly. The following css would fix it. If we add it to GHD, we'd have to remember to remove it once, and if, GitHub fixes the problem.

```css
  /* repo list - main page */
.js-repos-container a.flex-items-center .width-full {
  overflow: hidden !important;
  text-overflow: ellipsis !important;
  white-space: nowrap !important;
}
.js-repos-container a.flex-items-center .css-truncate {
  overflow: visible !important;
  text-overflow: unset !important;
  display: inline !important;
}
```

![](https://user-images.githubusercontent.com/136959/41209917-1313a8f4-6cf4-11e8-880d-e1fe3d48626c.gif)

What do you guys think?
