### ISSUE TITLE
Unread notifications in mobile version

### ISSUE THREAD

**Issue by Ash258** [StylishThemes/GitHub-Dark#641]
* **Browser**: Firefox Developer 61b also Chrome59 (inside electron app)
* **Operating System**: Windows 10 RS4 (17134.112)
* **Screenshot**:
    ![Screenshot](https://i.imgur.com/0ollwT7.png)
* **HTML of the section where the issue occurs**:

```html
<div class="inbox-zero">
  <h3>No unread notifications.</h3>
  <p>Good job!</p>
</div>
```

```css
.inbox-zero {
  background-color: #fff;
  border-top: 1px solid #e1e4e8;
}
```
