### ISSUE TITLE
learn more button: color/hover/focus - some portions part of autogenerate

### ISSUE THREAD

**Issue by the-j0k3r** [StylishThemes/GitHub-Dark#653]
# Please disable that stupid pretty bot. :angry: :innocent: 

* **Browser**: FF 66.0.2
* **Operating System**: Win 10 pro 1709
* **Screenshot**:

![button](https://user-images.githubusercontent.com/31389848/41633402-b446bcb8-7436-11e8-9c1e-6e97fb4d4515.gif)

This has a few things in auto-generated and some are not, just FYI
The button is green as is, and hover/focus/active blue box-shadows and borders come into play, 

page where you can see it e.g. https://github.com/RaitaroH/Stylus-DeepDark/projects

* **HTML of the section where the issue occurs**:

````html
<a href="https://help.github.com/articles/about-project-boards" class="btn btn-primary btn-outline">Learn More</a>
````

```css
.btn-outline {
  color: #0366d6;
  background-color: #fff;
  background-image: none;
}
.btn-outline:focus {
  border-color: #0366d6;
  box-shadow: 0 0 0 0.2em rgba(3, 102, 214, 0.4);
}
.btn-outline:hover,
.btn-outline:active,
.btn-outline.selected,
[open] > .btn-outline {
  color: #fff;
  background-color: #0366d6;
  background-image: none;
  border-color: #0366d6;
}
```
