### ISSUE TITLE
Borders for editor tooltips

### ISSUE THREAD

**Issue by tambry** [StylishThemes/GitHub-Dark#680]
I believe that currently the tooltips are hard to distinguish from the background:
![2018-07-06_14-58-55_chrome](https://user-images.githubusercontent.com/1827708/42377712-253b0a7a-812d-11e8-9b0c-c43df78cea98.png)

Maybe adding a slight border border would help?

HTML section:
````html
<md-task-list tabindex="-1" class="toolbar-item tooltipped tooltipped-n" aria-label="Add a task list" data-ga-click="Markdown Toolbar, click, task list" hotkey="L" role="button">
    <svg class="octicon octicon-tasklist" viewBox="0 0 16 16" version="1.1" width="16" height="16" aria-hidden="true">...</svg>
</md-task-list>
````

**Comment by the-j0k3r** [comment]
Why not just make the tooltips not dark, that way, these tooltips could have more contrast and also more or less match the tooltips that cant be stilled.

**Comment by Mottie** [comment]
We don't style these tooltips, so we need to make sure to include the borders for:

* `tooltipped-n`
* `tooltipped-ne`
* `tooltipped-e`
* `tooltipped-se`
* `tooltipped-s`
* `tooltipped-sw`
* `tooltipped-w`
* `tooltipped-nw`

**Comment by the-j0k3r** [comment]
borders?

**Comment by Mottie** [comment]
The tooltips are added by using `:before` and `:after` on the hovered element.

The `:after` creates the body of the tooltip while the `:before` adds the arrow using the [css border technique](https://css-tricks.com/examples/ShapesOfCSS/).

**Comment by Mottie** [comment]
The white tooltips in the screenshot are the browser default tooltips.

We have a userscript to turn those into GitHub tooltips named "GitHub-Make-Tooltips" from the [GitHub Dark Script repo](https://github.com/StylishThemes/GitHub-Dark-Script#additional-scripts).

**Comment by the-j0k3r** [comment]
Yes, I know, this is why I suggested making these also lighter, and your other script can handle what color all tooltips should be including these.

Or no?

**Comment by Mottie** [comment]
The script only adds the `tooltipped` class. It doesn't do anything with the color.

**Comment by the-j0k3r** [comment]
Sure, but it could. Anyway... I just wanted to make a suggestion to make all tooltips visible and more or less look similar ish.

**Comment by the-j0k3r** [comment]
```css
  .tooltipped-n:after, .tooltipped-ne:after, .tooltipped-e:after,
  .tooltipped-se:after, .tooltipped-s:after, .tooltipped-sw:after,
  .tooltipped-w:after, .tooltipped-nw:after {
    color: #000 !important;
	background: #ccc !important;
  }

 .tooltipped-se:before, .tooltipped-s:before,
 .tooltipped-sw:before, .tooltipped-w:before {
	border-bottom-color: #ccc !important;
  }

  .tooltipped-n:before, .tooltipped-ne:before,
  .tooltipped-e:before, .tooltipped-nw:before {
    border-top-color: #ccc !important;
  }
```

@tambry  that does the following

![tooltips](https://user-images.githubusercontent.com/31389848/42393513-82e13b7e-814e-11e8-83bd-5491bea0ea89.gif)

could be darker/brighter I found that didn't assault my retinas and is just a shade darker than the browsers tooltips so doesnt completely look out of place, But up to you or @Mottie  and @silverwind I dont have a strong opinion on these. :)
