### ISSUE TITLE
.Popover-message--bottom-*:before .Popover-message--top-*:before autogenerated wrong border color.

### ISSUE THREAD

**Issue by the-j0k3r** [StylishThemes/GitHub-Dark#682]
* **Browser**: FF 61.01
* **Operating System**: Winblow 10 pro 1709
* **Screenshot**:

![popover](https://user-images.githubusercontent.com/31389848/42397231-f6fa300c-815c-11e8-985a-d4c06ed40c62.gif)

* **HTML of the section where the issue occurs**:

this fixes those but if autogenerated is fixed no need for PR and thats above my paygrade @silverwind

````css
  .Popover-message--bottom-right:before,
  .Popover-message--bottom-left:before {
	border-top-color: #444 !important;
  }

  .Popover-message:before,
  .Popover-message--top-right:before,
  .Popover-message--top-left:before {
	border-bottom-color: #555 !important;
  }
````
