### ISSUE TITLE
prev/next: next bag is grey should be blue

### ISSUE THREAD

**Issue by the-j0k3r** [StylishThemes/GitHub-Dark#708]
I came across this ages ago then couldnt remember where I seen it, :+1: I stumbled on it  an here <s>we are</s> I am.

* **Browser**: FF 
* **Operating System**:
* **Screenshot**:

![prev-next](https://user-images.githubusercontent.com/31389848/43038836-fb7ac750-8d18-11e8-95c3-f46699835113.gif)

* **HTML of the section where the issue occurs**:

````html
<button type="button" class="btn btn-sm btn-outline BtnGroup-item tooltipped tooltipped-s" aria-label="You are viewing the latest commit" disabled="">
          Next <svg class="octicon octicon-chevron-right" viewBox="0 0 8 16" version="1.1" width="8" height="16" aria-hidden="true"><path fill-rule="evenodd" d="M7.5 8l-5 5L1 11.5 4.75 8 1 4.5 2.5 3l5 5z"></path></svg>
        </button>
````

**Comment by Mottie** [comment]
Is that a disabled button in Refined GitHub?

**Comment by the-j0k3r** [comment]
No, Its unrelated to that, I dont use RGH.

Fix is:
```css
  .full-commit .btn-outline, .full-commit .btn-outline:disabled {
    background: transparent !important;
  }
```
