### ISSUE TITLE
Labels text are now the theme color

### ISSUE THREAD

**Issue by robobenklein** [StylishThemes/GitHub-Dark#714]
* **Browser**: Chrome
* **Operating System**: Ubuntu 18.04
* **Screenshot**:

![image](https://user-images.githubusercontent.com/5423266/43208644-e08ab652-8ff8-11e8-9bb9-426967a5077d.png)

Just happened today.

Script v2.4.7 & CSS v1.20.58

* **HTML of the section where the issue occurs**:

````html
<a class="IssueLabel--big js-label-link d-inline-block label-link text-left width-fit" href="/StylishThemes/GitHub-Dark-Script/labels/bug" style="background-color: #ee2222;color: #000000;">
        <span class="label-name">bug</span>
      </a>
````

```css
element.style {
  background-color: #ee2222;
  color: #000000; // overidden
}
// later on...
.stuff {
  color: #ed2024 !important;
}
```
