### ISSUE TITLE
Make disabled buttons more visible.

### ISSUE THREAD

**Issue by the-j0k3r** [StylishThemes/GitHub-Dark#715]
I was looking for something and came across a disabled button

* **Browser**: FF 61.0.1
* **Operating System**: Win 10
* **Screenshot**:

This has a before and after with code below

![disabled](https://user-images.githubusercontent.com/31389848/43220579-5136eb52-9042-11e8-9048-333710c8add3.gif)

The default has a great deal more contrast

![disabled](https://user-images.githubusercontent.com/31389848/43220611-6189a6fc-9042-11e8-8619-8cab350225db.PNG)

As is
````css
.btn:disabled, .btn:disabled:hover, .btn.disabled, .btn.disabled:hover, button.button:disabled, button.button:disabled:hover, button.button.disabled, button.button.disabled:hover, button.minibutton:disabled, button.minibutton:disabled:hover, button.minibutton.disabled, span.minibutton.disabled, a.minibutton.disabled, button.minibutton.disabled:hover, a.minibutton:disabled:hover, a.minibutton.disabled:hover, span.minibutton:disabled:hover, span.minibutton.disabled:hover, .search-result-group, .gist-quicksearch-result-group {
	background: #222 !important;
	border-color: #282828 !important;
	color: #444 !important;
}
````

Proposed
````css
.btn:disabled, .btn:disabled:hover, .btn.disabled, .btn.disabled:hover, button.button:disabled, button.button:disabled:hover, button.button.disabled, button.button.disabled:hover, button.minibutton:disabled, button.minibutton:disabled:hover, button.minibutton.disabled, span.minibutton.disabled, a.minibutton.disabled, button.minibutton.disabled:hover, a.minibutton:disabled:hover, a.minibutton.disabled:hover, span.minibutton:disabled:hover, span.minibutton.disabled:hover, .search-result-group, .gist-quicksearch-result-group {
	background: #282828 !important;
	border-color: #383838 !important;
	color: #484848 !important;
}
````
