### ISSUE TITLE
First class support for selected issue comments

### ISSUE THREAD

**Issue by xt0rted** [StylishThemes/GitHub-Dark#716]
Today they rolled out first class support for showing the selected comment on an issue/pr. I haven't tested this with Refined GitHub enabled yet.

* **Browser**: chrome
* **Operating System**: win10
* **Link**: https://github.com/StylishThemes/GitHub-Dark/issues/712#issuecomment-407599856
* **Screenshot**:

![image](https://user-images.githubusercontent.com/831974/43278587-865c86a6-90d9-11e8-858a-f974d5f68e25.png)

* **HTML of the section where the issue occurs**:

```html
<div class="unminimized-comment comment previewable-edit js-comment js-task-list-container timeline-comment reorderable-task-lists " data-body-version="51cbf462989e1d79bb5c437eebb066cd" data-unfurl-authenticity-token="...">
    ...
</div>
```

The colors/style they use is the same as focused inputs so this would be the closest out of the box match for it.

```css
.timeline-comment-group:target .timeline-comment {
  border-color: rgb(65, 131, 196) !important;
  box-shadow: inset 0 1px 2px rgba(0, 0, 0, .075), 0 0 2px rgb(65, 131, 196) !important;
}
```
