### ISSUE TITLE
review comment bounding box

### ISSUE THREAD

**Issue by the-j0k3r** [StylishThemes/GitHub-Dark#723]
* **Browser**: FF 61.0.1
* **Operating System**: Win 10 pro
* **Screenshot**:

![capture](https://user-images.githubusercontent.com/31389848/43553814-cddecb42-95e8-11e8-9500-b985f4a5fdb9.PNG)

* **HTML of the section where the issue occurs**:

````html
<div class="edit-comment-hide">
        <p class="comment-form-stale">
          <svg class="octicon octicon-alert" viewBox="0 0 16 16" version="1.1" width="16" height="16" aria-hidden="true"><path fill-rule="evenodd" d="M8.893 1.5c-.183-.31-.52-.5-.887-.5s-.703.19-.886.5L.138 13.499a.98.98 0 0 0 0 1.001c.193.31.53.501.886.501h13.964c.367 0 .704-.19.877-.5a1.03 1.03 0 0 0 .01-1.002L8.893 1.5zm.133 11.497H6.987v-2.003h2.039v2.003zm0-3.004H6.987V5.987h2.039v4.006z"></path></svg> The content you are editing has changed. Please try again.
        </p>
        <div class="Box review-summary mt-3 mb-4">
          <div class="Box-body comment-body markdown-body js-comment-body">
            <p>test 2</p>
          </div>
        </div>
    </div>

<div class="Box review-summary mt-3 mb-4">
          <div class="Box-body comment-body markdown-body js-comment-body">
            <p>test 2</p>
          </div>
        </div>

<div class="Box-body comment-body markdown-body js-comment-body">
            <p>test 2</p>
          </div>
````

This CSS is related but theres another part missing.

```css
.timeline-comment:target .review-summary .comment-body {
	border: 1px solid #2188ff;
}
.timeline-comment:target .review-summary::before {
	filter: drop-shadow(0 -0.28em 0 #c8e1ff);
	border-bottom-color: #2188ff;
}
```
