### ISSUE TITLE
.Popover-message &before &after are white.

### ISSUE THREAD

**Issue by the-j0k3r** [StylishThemes/GitHub-Dark#725]
This was OK after https://github.com/StylishThemes/GitHub-Dark/commit/0c3020425652812333b3b6374ec91a2d453d0da5 but somewhere it broke.

* **Browser**: FF 66.0.1
* **Operating System**: win 10 pro
* **Screenshot**:

![oveflow](https://user-images.githubusercontent.com/31389848/43596729-0ad0cc14-9678-11e8-8c67-b4e9261258f4.gif)

* **HTML of the section where the issue occurs**:

https://github.com/primer/primer/blob/master/modules/primer-popover/lib/popover.scss#L6-L34

fix is below: I have to look at the the generate.js and see if I can do it that way but I dont see how at this time hence the ticket while I investigate. and hope theres some feedback

````css
.Popover-message:after {
    border-bottom-color: #181818 !important;
}
.Popover-message:before   {
    border-bottom-color: #343434 !important;
}

````
