### ISSUE TITLE
Double horizontal divider after merging PR

### ISSUE THREAD

**Issue by xt0rted** [StylishThemes/GitHub-Dark#726]
This looks to be a result of a border being applied to two different elements.

* **Browser**: chrome
* **Operating System**: win10
* **Screenshot**:

![image](https://user-images.githubusercontent.com/831974/43609834-0879f63e-9673-11e8-8663-b63d329fac70.png)

![image](https://user-images.githubusercontent.com/831974/43609794-f178a3b8-9672-11e8-941b-acf973866c45.png)

* **HTML of the section where the issue occurs**:

````html
<div class="closed-banner"></div>
````

```html
<div class="discussion-timeline-actions">
   ...
</div>
```

**Comment by the-j0k3r** [comment]
Not only that but the vertical line keeps running to bottom

![capture](https://user-images.githubusercontent.com/31389848/43619729-32fc46ec-96c7-11e8-805b-835d6e3b1347.PNG)

![capture](https://user-images.githubusercontent.com/31389848/43619753-4bb3bd5a-96c7-11e8-8b91-fb77429b6cfb.PNG)

this area 

https://github.com/StylishThemes/GitHub-Dark/blob/e423bcee8373aa0cb022406a98d06e7e35c4b1d0/github-dark.css#L1733-L1746

if becomes 
```css
  /* discussion timeline tweaks */
  .discussion-timeline-actions, .closed-banner {
    background: transparent !important;
    border-top: transparent !important;
  }
  .new-discussion-timeline .closed-banner {
		background: transparent !important;
		border-top: 3px solid #444 !important;
		border-bottom: #444 !important;
	}
  .discussion-timeline:before {
    margin-top: 2px !important;
    background: #383838 !important;
    height: calc(100% - 250px) !important;
  }
```

fixes both those issues here
