### ISSUE TITLE
Collapsed file list has the wrong border color

### ISSUE THREAD

**Issue by xt0rted** [StylishThemes/GitHub-Dark#739]
Repos you're not a part of now show the file list in a collapsed state (try a repo such as https://github.com/primer/primer). It looks like only the border of the file list has changed with this.

* **Browser**: chrome
* **Operating System**: win10
* **Screenshot**:

![image](https://user-images.githubusercontent.com/831974/45074332-025ab880-b0b1-11e8-9499-08325375abff.png)

* **HTML of the section where the issue occurs**:

````html
<div class="Details details-truncate-file-list js-details-container">
  <div class="file-wrap">
    <!- ... -->
  </div>
  <button class="btn-truncate-file-list Details-content--shown mb-2 py-2 border border-top-0 border-gray-dark text-center text-blue text-bold width-full js-details-target" aria-label="Show all files" aria-expanded="false" data-ga-click="Repository, expand file list" data-hotkey="f">
    <svg class="octicon octicon-file-directory mr-1" viewBox="0 0 14 16" version="1.1" width="14" height="16" aria-hidden="true"><path fill-rule="evenodd" d="M13 4H7V3c0-.66-.31-1-1-1H1c-.55 0-1 .45-1 1v10c0 .55.45 1 1 1h12c.55 0 1-.45 1-1V5c0-.55-.45-1-1-1zM6 4H1V3h5v1z"></path></svg> Show all files
  </button>
</div>
````

Clicking the button adds `Details--on` to the parent container, so the border color needs to be applied to `.file-wrap` and `.details-truncate-file-list.Details--on .file-wrap`

For anyone wanting to remove this entirely you should be able to use this to do it:
```css
.details-truncate-file-list .file-wrap {
  max-height: none;
  margin-bottom: 10px;
  overflow-y: hidden;
  border: 1px solid #484848;
  border-top: 0;
  border-bottom-right-radius: 3px;
  border-bottom-left-radius: 3px;
}

.Details-content--shown {
  display: none !important;
}
```
