### ISSUE TITLE
Activity overview chart is green instead of blue

### ISSUE THREAD

**Issue by xt0rted** [StylishThemes/GitHub-Dark#742]
This is a more recent beta feature you can opt-in to (can see it on [my profile](https://github.com/xt0rted)).
https://blog.github.com/changelog/2018-08-24-profile-activity-overview/

* **Browser**: chrome
* **Operating System**: win10
* **Screenshot**:

![image](https://user-images.githubusercontent.com/831974/45503009-8832cf80-b753-11e8-867e-c99f6312069a.png)

![image](https://user-images.githubusercontent.com/831974/45503026-9680eb80-b753-11e8-9485-1545f35fb14e.png)

Here's my proposed css changes that are based on the commit chart above it.

```css
.activity-overview-axis,
.activity-overview-point {
  stroke: rgb(65, 131, 196) !important;
}
.activity-overview-point {
  fill: #222 !important;
}
.js-highlight-blob {
  stroke: rgb(65, 131, 196) !important;
  fill: rgb(65, 131, 196) !important;
  opacity: 0.25 !important;
}
```
