### ISSUE TITLE
Notification side menu selected text color

### ISSUE THREAD

**Issue by emp-daisy** [StylishThemes/GitHub-Dark#748]
The text color is similar to the background color hence making the text invisible

* **Browser**:
Chrome
* **Operating System**:
OS X
* **Screenshot**:
<img width="1008" alt="screen shot 2018-10-04 at 5 42 49 pm" src="https://user-images.githubusercontent.com/9393444/46489339-0a675e80-c7fd-11e8-9ff0-61707b1779de.png">

* **HTML of the section where the issue occurs**:
````html
<a href="/notifications" class="filter-item selected">
                <span class="count">0</span>
                Unread
              </a>
````

**Comment by Mottie** [comment]
Hi @emp-daisy!

The `.filter-item.selected` class is set to the base-color (set to `#4183C4` by default). Please make sure you've got the most recent style installed.

**Comment by emp-daisy** [comment]
@Mottie 
So with white as the base color.  Text with white background should unreadable?
Maybe an option should be available to change background color along with the base color.

<img width="748" alt="screen shot 2018-10-05 at 11 56 49 am" src="https://user-images.githubusercontent.com/9393444/46531608-c6746800-c895-11e8-9c3d-870ac0ed3c70.png">

**Comment by Mottie** [comment]
The problem is that the customizable base color is used as a background, text and border color throughout the style. We'd need to switch our style to use LESS or Stylus in order to calculate the contrasting text color. Since this is the last style we've continued to support on userstyles.org, we can't do anything dramatic like that since that site doesn't support LESS/Stylus.

You're best/easiest option would be to create a secondary "GitHub-Dark additions" style to target that selector and make the text black. You can start out with this css:

```css
/* ==UserStyle==
@name        GitHub Dark Additions
@namespace   StylishThemes
@version     1.0.0
@description GitHub Dark additions to fix a white base-color setting
@author      Me
==/UserStyle== */

@-moz-document regexp("^https?://((blog|gist|guides|help|raw|resources|status|developer)\\.)?github\\.com/((?!generated_pages/preview).)*$") {
  a.filter-item.selected,
  ul.filter-list .filter-item.selected {
    color: black !important;
  }
}
```

Copy the above block of css. Open the Stylus popup and click on the "Write style for" link. Select all content in the editor that appears, then paste in the above style and save.
