### ISSUE TITLE
Danger buttons have the wrong focus color

### ISSUE THREAD

**Issue by xt0rted** [StylishThemes/GitHub-Dark#751]
* **Browser**: chrome
* **Operating System**: win10
* **URL**: https://github.com/StylishThemes/GitHub-Dark/settings > **Danger Zone** section
* **Screenshot**:

![image](https://user-images.githubusercontent.com/831974/46639933-12920780-cb37-11e8-9206-542cc0d36bb1.png)

![image](https://user-images.githubusercontent.com/831974/46639943-20478d00-cb37-11e8-95ba-d1bc171e7b52.png)

* **HTML of the section where the issue occurs**:

````html
<summary class="btn btn-danger boxed-action" aria-haspopup="dialog">Make private</summary>
````

The missing style looks to be for `.btn-danger:focus` which by default is

```css
.btn-danger:focus {
  box-shadow: 0 0 0 0.2em rgba(203, 36, 49, 0.4);
}
```
