### ISSUE TITLE
Unread issue comments aren't highlighted

### ISSUE THREAD

**Issue by xt0rted** [StylishThemes/GitHub-Dark#769]
I'm not sure if this used to work or not, but when a comment is left on an issue you have open it gets added to the issue and highlighted in yellow until you interact with the page. With GitHub Dark these comments aren't being highlighted.

There's a lot of html for comments so I've copied only the wrapper element below. To simulate this go to any issue with a comment that's not your own. Then find the `div` that best matches the html below and add `unread-item` to the class list. If you also add `js-unread-item` then the comment will un-highlight when you interact with the page.

* **Browser**: chrome
* **Operating System**: win10
* **Url**: https://github.com/StylishThemes/GitHub-Dark/issues/766#issuecomment-435494098
* **Screenshot**:

![image](https://user-images.githubusercontent.com/831974/48292357-02c45680-e448-11e8-98e9-33cd8d6f7e11.png)

![image](https://user-images.githubusercontent.com/831974/48292368-11127280-e448-11e8-9889-1b9bc8bfdb9a.png)

* **HTML of the section where the issue occurs**:

````html
<div class="unminimized-comment editable-comment comment previewable-edit js-comment js-task-list-container timeline-comment reorderable-task-lists" data-body-version="a3f5cee6a7e034cfebdffd2599e874ac" data-unfurl-authenticity-token="...">
</div>
````

```css
.timeline-comment.unread-item {
  border-color: #e5d999 !important;
}

.timeline-comment.unread-item .timeline-comment-header {
  background-color: #fffdef !important;
  border-bottom-color: #e5d999 !important;
}

.timeline-comment.unread-item .timeline-comment-label {
  border-color: #e5d999;
}

.timeline-comment.unread-item .previewable-comment-form .comment-form-head.tabnav {
  background-color: #fffdef;
  border-bottom-color: #e5d999;
  color: #e5d999;
}
```
