### ISSUE TITLE
Disabled create merge commit option has incorrect hover state

### ISSUE THREAD

**Issue by xt0rted** [StylishThemes/GitHub-Dark#791]
You can see this on #790 by expanding the `Squash and merge` button

* **Browser**: chrome
* **Operating System**: win10
* **Screenshot**:

![image](https://user-images.githubusercontent.com/831974/49620942-1ef8dc00-f991-11e8-9dc8-d0b22e4f7feb.png)

* **HTML of the section where the issue occurs**:

````html
<div class="select-menu-item disabled " role="menuitem" data-input-title-value="Merge pull request #790 from StylishThemes/octotree-fixes" data-input-message-value="Various fixes for octotree">
    <svg class="octicon octicon-check select-menu-item-icon" viewBox="0 0 12 16" version="1.1" width="12" height="16" aria-hidden="true">
        <path fill-rule="evenodd" d="M12 5l-8 8-4-4 1.5-1.5L4 10l6.5-6.5L12 5z"></path>
    </svg>
    <input type="radio" name="do" id="do_merge" value="merge" class="js-merge-method" disabled="disabled">
    <div class="select-menu-item-text">
        <span class="select-menu-item-heading js-select-button-text">Create a merge commit</span>
        <span class="description">All commits from this branch will be added to the base branch via a merge commit.</span>
        <span class="unavailable-merge-method">Not enabled for this repository</span>
    </div>
</div>
````

**Comment by silverwind** [comment]
We're missing this style from GH's sheet:

````css
.select-menu-item.navigation-focus.disabled .description, .select-menu-item:hover.disabled .description, .select-menu-item[aria-selected="true"].disabled .description {
    color: hsla(0,0%,100%,.6);
}
````

I think we can just add a generator entry (`tools/generate.js`) for it, mapping to the same color, like this:

````js
"color: hsla(0,0%,100%,.6)": "color: hsla(0,0%,100%,.6)"
````
Running `grunt generate` should then fix this issue.
