### ISSUE TITLE
Review radio buttons not visible

### ISSUE THREAD

**Issue by CDanU** [StylishThemes/GitHub-Dark#796]
Firefox 63.0.3 (64-bit)
script version: 2.4.11 (greasemonkey, Last updated: 12/8/2018 )

![reviewradio](https://user-images.githubusercontent.com/15148226/49688044-bfbfd680-fb0c-11e8-87fd-7e968e9a333d.png)

Css ruleset that is causing this:

```css
select,
input:not(.btn):not(.btn-link):not(.btn-danger),
textarea {
  -moz-appearance: none !important;
  background-color: #181818 !important;
  border-color: #343434 !important;
  color: #ccc !important;
}
```

If the `-moz-appearance: none !important;` rule is disabled I get to see working unstyled radio buttons:
![reviewradio2](https://user-images.githubusercontent.com/15148226/49688091-c5192300-fb04-11e8-9937-c8008302bea7.png)

-------

E: Alternatively injecting the following:

```css
.form-checkbox input {
  height: 15px;
  width: 15px;
}
```

now shows me at least one (kinda ugly) svg image styled radio button once it is selected:
![reviewradio3](https://user-images.githubusercontent.com/15148226/49688215-eb43c080-fb0e-11e8-9d24-467839ee1dd7.png)

**Comment by Mottie** [comment]
Hi @CDanU!

What script are you using? Did you install the userscript from userstyles.org?

We're planning to stop updating userstyles.org because of how they track their users. I would suggest switching to use:

* [GitHub Dark script](https://github.com/StylishThemes/GitHub-Dark-Script) - a userscript that pulls in the style directly from this repository daily.
* [Stylus](https://add0n.com/stylus.html) - a browser extension that updates styles daily based on their release version, then install this style as a [usercss](https://github.com/StylishThemes/GitHub-Dark#installation).

**Comment by CDanU** [comment]
I installed the script via the ` Install GitHub-Dark Script `  link from the main README.md.

**Comment by Mottie** [comment]
Hmm, I'm not seeing the issue... this is a screenshot of the current style in Firefox 65.0a1

![](https://user-images.githubusercontent.com/136959/49688283-2a552000-fad5-11e8-9ebd-5ef82f6c2796.png)

**Comment by Mottie** [comment]
In the GitHub Dark script settings panel ([ref](https://github.com/StylishThemes/GitHub-Dark-Script/wiki#script-setup)), click on the force update style button.

**Comment by CDanU** [comment]
I installed the firefox devel edition (65.0b2 (64-bit)) from the arch repos, installed greasemonkey and the script and I still get the same behaviour.

**Comment by silverwind** [comment]
It appears Firefox is ignoring this rule, but only when loading the style via script:

````css
  input[type="checkbox"], input[type="checkbox"]:focus, input[type="radio"],
  input[type="radio"]:focus, input[type="checkbox"]:hover:active,
  input[type="radio"]:hover:active, input[type="checkbox"]:disabled,
  input[type="checkbox"]:hover:disabled,
  input[type="checkbox"]:hover:active:disabled {
    -webkit-appearance: none !important;
    background-color: #181818 !important;
    border: 1px solid #484848 !important;
    color: #eee !important;
    height: 1em !important;
    width: 1em !important;
  }
````

Maybe  it's deeming one of the selectors invalid? Not sure how to get CSS warnings to show in recent versions of Firefox.
