### ISSUE TITLE
Add background for Issue caption. (#partial-discussion-header)

### ISSUE THREAD

**Issue by Ruffo324** [StylishThemes/GitHub-Dark#797]
Please add the following rule, to hide the white box.

```css
#partial-discussion-header {
  background-color: transparent;
}
```

![image](https://user-images.githubusercontent.com/18107332/49693203-be25fb00-fb6c-11e8-8c58-b3ccbbc91287.png)
