### ISSUE TITLE
why no more userstyles.org

### ISSUE THREAD

**Issue by syniuhin** [StylishThemes/GitHub-Dark#805]
What was wrong with userstyles.org? It was a neat way to install this css and I was pretty sad unable to find it this morning.

**Comment by silverwind** [comment]
See https://github.com/StylishThemes/GitHub-Dark/issues/683. Basically it boiled down to these reasons:

- The site changed owner and the new ones are doing shady business which we do not agree with.
- Their style upload process is partially broken since like a year.
- They do not support the usercss format so styles do not auto-update which is cumbersome to users.

Leaving this issue open for visibility.

**Comment by tzm41** [comment]
NVM I figured it out, basically has to use the css file and manually remove the unsupported `@-moz-document` tags.

> They do not support the usercss format so styles do not auto-update which is cumbersome to users.

Well this seems even more cumbersome for Safari users?

**Comment by owlboy** [comment]
@tzm41 It works fine with [Casandra](https://cascadea.app) as far as I can tell.

**Comment by xt0rted** [comment]
@StylishThemes/github I'm no longer publishing one of my styles to userstyles.org and was going to update what's there with the following as a way to convey the change. Would it be helpful to do something similar for this style?

```css
body::before {
  content: "⚠️ This style is no longer being published to userstyles.org, please go to https://github.com/xt0rted/AppVeyor-Dark to install it as a UserCSS style";
  color: #ddd;
  background-color: #261d08 !important;
  border: 1px solid #542 !important;
  font-weight: 500;
  display: block;
  padding: 15px;
  margin: 20px auto;
  max-width: 62.5rem;
}
```

![image](https://user-images.githubusercontent.com/831974/50919492-f2f9cc00-1410-11e9-9fa6-bca60b153962.png)
