### ISSUE TITLE
Milestone and project menus: tabs have a bottom border when GHD is enabled.

### ISSUE THREAD

**Issue by the-j0k3r** [StylishThemes/GitHub-Dark#814]
* **Browser**: FF64
* **Operating System**: Win 10pro/Ubuntu
* **Screenshot**:

![weird](https://user-images.githubusercontent.com/31389848/50642439-72981e80-0f6b-11e9-943b-37436006353a.gif)

These borders are atm auto generated,needs overriding.

* **HTML of the section where the issue occurs**:

````html
<li class="select-menu-tab">
        <button type="button" role="tab" class="select-menu-tab-nav" aria-selected="true">Open</button>
      </li>

````
````html
<li class="select-menu-tab">
          <button type="button" class="select-menu-tab-nav" role="tab" aria-selected="true">Repository</button>
        </li>

````

**Comment by xt0rted** [comment]
This looks to fix it. `#1c1c1c` is the color of the menu options area while `#181818` is the color of the button. Either should work here but using `#1c1c1c` best matches the default style.

```css
.select-menu-tabs .select-menu-tab-nav[aria-selected=true] {
  border-bottom-color: #1c1c1c !important;
}
```
