### ISSUE TITLE
New style errors

### ISSUE THREAD

**Issue by armano2** [StylishThemes/GitHub-Dark#832]
* **Browser**: Chrome
* **Operating System**: Windows
* **Screenshot**:

- [x] https://github.com/babel/babel/pull/9321#pullrequestreview-191941370
![image](https://user-images.githubusercontent.com/625469/51075994-1f247f80-1693-11e9-9961-cb3de569b90d.png)

- [ ] https://github.com/settings/billing/payment
![image](https://user-images.githubusercontent.com/625469/51077117-17b8a280-16a2-11e9-946d-984f9df10425.png)

**Comment by the-j0k3r** [comment]
For the babel review its something like

```css
  .pull-request-review-body-wrapper .timeline-comment-group .timeline-comment:before {
    border-bottom-color: #555 !important;
  }
	.pull-request-review-body-wrapper .timeline-comment-group .timeline-comment:after {
		border-bottom-color: #222 !important;
	}
	.pull-request-review-body-wrapper .timeline-comment-group .timeline-comment:after,
	.pull-request-review-body-wrapper .timeline-comment-group .timeline-comment:before {
    border-right-color: transparent !important;
  }
```

**Comment by the-j0k3r** [comment]
Fixed the first issue fully in https://github.com/StylishThemes/GitHub-Dark/commit/83ec9d33b40be839681f2b02d301ea66b1743646

However the credit card portion eludes me.

**Comment by Mottie** [comment]
I made this a while back and forgot about it... I think we can just add another section; if people don't like *all* zuora.com iframes being styled, then we'll need to tell them to turn on Stylus' [expose iframes](https://github.com/openstyles/stylus/wiki/Options#advanced) option and then include an html selector in all these definitions:

```css
/* ==UserStyle==
@name           Zuora.com (GitHub)
@namespace      github.com/openstyles/stylus
@version        0.1.0
@description    A new userstyle
@author         Me
==/UserStyle== */

@-moz-document domain("zuora.com") {
  body, .popup, label {
    background: #181818 !important;
    color: #ddd !important;
  }
  input, select {
    background: #111 !important;
    color: #ddd !important;
    border-color: #484848 !important;
  }
}
```

**Comment by Mottie** [comment]
We could also change the about background to `transparent` & add this to GHD to make the background image show through:

```css
iframe[src*="zuora.com"]{
  background: none !important;
}
```

**Comment by the-j0k3r** [comment]
@Mottie that works a treat, but its missing the submit button,let me ad that.

Aside from that your snippet works a treat.

**Comment by armano2** [comment]
there is one more issue with comment @the-j0k3r with this change

![image](https://user-images.githubusercontent.com/625469/51087702-ec43bf80-1756-11e9-80c9-6618890c40b1.png)

**Comment by the-j0k3r** [comment]
@Mottie 

```css
/* ==UserStyle==
@name           Zuora.com (GitHub)
@namespace      github.com/openstyles/stylus
@version        0.1.0
@description    A new userstyle
@author         Me
==/UserStyle== */

@-moz-document domain("zuora.com") {
  body,
  .popup,
  label {
    background: #181818 !important;
    color: #ddd !important;
  }
  input,
  select {
    background: #111 !important;
    color: #ddd !important;
    border-color: #484848 !important;
  }
	.btn-submit {
		background: linear-gradient(#407045, #305530) !important;
    border-color: #083 !important;
	}
	.btn-submit:hover {
		background: linear-gradient(#508055, #407045) !important;
	}
}
```

That fixes button

![parallax](https://user-images.githubusercontent.com/31389848/51087734-607e6300-1757-11e9-8514-6926adc1a1f0.gif)

Please feel free to push into master.

@armano2 I took care of that in https://github.com/StylishThemes/GitHub-Dark/commit/83ec9d33b40be839681f2b02d301ea66b1743646
