### ISSUE TITLE
Image colors inverted inside jupyter notebooks 

### ISSUE THREAD

**Issue by A-Jacobson** [StylishThemes/GitHub-Dark#846]
I just installed these themes through the github dark script. My eyes are thanking me, but it seems that all of the images rendered inside jupyter notebooks have inverted colors.

BROWSER: CHROME
OS: WINDOWS 10
SCREENSHOT:

![jupyternotebook](https://user-images.githubusercontent.com/9411532/52395598-a501d380-2a63-11e9-87fd-cb6789216596.JPG)

HTML:
```html
<div class="output_png output_subarea ">
  <img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAskAAADLCAYAAACcYg7PAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALEgAACxIB0t1+/AAAA...">
</div>
```

**Comment by silverwind** [comment]
Got a link to such a notebook?

**Comment by A-Jacobson** [comment]
sure! here's the one I used to test though it's happening in all of my notebooks with images.

https://github.com/udacity/deep-learning-v2-pytorch/blob/master/cycle-gan/CycleGAN_Solution.ipynb

**Comment by Mottie** [comment]
It looks like Jupyter builds all of its output images the same way. If we don't invert the image, the axes remain black and barely readable.

Maybe we can compromise and remove the alterations on hover? Something like this:

```css
/* ==UserStyle==
@name           GitHub Jupyter Image Invert
@namespace      StylishThemes
@version        1.0.0
@description    Invert Jupyter notebook images on hover
@author         Me
==/UserStyle== */

@-moz-document url-prefix("https://render.githubusercontent.com") {
  .render-shell .output_area .output_png:hover img {
    filter: none !important;
  }
}
```
