### ISSUE TITLE
Some headers are grey in the marketplace

### ISSUE THREAD

**Issue by xt0rted** [StylishThemes/GitHub-Dark#852]
* **Browser**: chrome
* **Operating System**: win10
* **Screenshot**:  ![image](https://user-images.githubusercontent.com/831974/52873357-c8d8af80-311c-11e9-802e-152c95c578c9.png)
* **Link to page with the issue**: https://github.com/marketplace

Right now we're styling each of those four elements, and all of the logo badges on the page. Would it be better to remove the custom styling on them entirely? The page seems ok leaving those alone.

Here's the html for one of them that has the darker text.

```html
<div class="MarketplaceFeature col-3 flex-auto px-2 anim-fade-in">
  
<a class="no-underline MarketplaceFeature-link" data-hydro-click="{&quot;event_type&quot;:&quot;marketplace_listing_click&quot;,&quot;payload&quot;:{&quot;marketplace_listing_id&quot;:25,&quot;location&quot;:&quot;hero_card&quot;,&quot;source_url&quot;:&quot;https://github.com/marketplace&quot;,&quot;destination_url&quot;:&quot;https://github.com/marketplace/codetree&quot;,&quot;client_id&quot;:&quot;790373834.1527194507&quot;,&quot;originating_request_id&quot;:&quot;E331:4D40:7045E1:CEDC02:5C66F73A&quot;,&quot;originating_url&quot;:&quot;https://github.com/marketplace&quot;,&quot;user_id&quot;:831974}}" data-hydro-click-hmac="1535abe415d1fe01102c9b52af67191d93bbae5be06cebb6b1db36e9c720e929" href="/marketplace/codetree">
  <div class="p-4 text-center rounded-1 box-shadow-medium mb-3 js-hero-listing-container bg-white" style="background-image:url('https://marketplace-images.githubusercontent.com/703/2df9c028-e40e-11e7-8058-a9b95ff2a622?auto=webp&amp;format=jpeg&amp;width=600'); background-size: cover; background-position: center top;">
    <div class="CircleBadge CircleBadge--medium CircleBadge--feature mx-auto js-hero-listing-bgcolor" style="background-color: #6FBD3B;"><img class="CircleBadge-icon" alt="Codetree" src="https://avatars3.githubusercontent.com/ml/25?s=106&amp;v=4"></div>
    <h3 class="h2 no-wrap js-hero-listing-name text-gray-dark">Codetree</h3>
  </div>
</a>
  <p class="MarketplaceFeature-text text-white text-center px-3 lh-condensed js-hero-listing-description">Lightweight project management for GitHub issues</p>
</div>
```

**Comment by silverwind** [comment]
Yes, I would appreciate if we remove styles affecting those boxes, given that our styles even overwrite the background, which is quite bad.

**Comment by xt0rted** [comment]
@silverwind is there a way to exclude classes from the generator? The circle badges are all being set with that due to their default background color, and that's overriding the inline styles. I don't think we can fix some of this without being able to tell the generator to not include a given class name in its output.

**Comment by xt0rted** [comment]
Looks like the generator does support this according to https://github.com/StylishThemes/GitHub-Dark/blob/235e2641909437d809be2a94e1ece85739e98441/tools/generate.js#L188-L198

I'll have to play around with that.

**Comment by xt0rted** [comment]
Looks like that did the trick. Had to exclude `.bg-white` too so we could do some other tricks with it. Here's what the marketplace looks like now.

![image](https://user-images.githubusercontent.com/831974/52917243-27399580-32b7-11e9-9d9a-152711386546.png)

The circle badges are also used on https://github.com/settings/installations and in the actions editor which I really need to finish up.

**Account settings**

![image](https://user-images.githubusercontent.com/831974/52917264-6962d700-32b7-11e9-87d7-3e6630a2443c.png)

**Actions**

![image](https://user-images.githubusercontent.com/831974/52917287-adee7280-32b7-11e9-82d2-f6bf3b17628a.png)

**Comment by the-j0k3r** [comment]
LGTM

**Comment by silverwind** [comment]
Maybe add a invert filter to those bright boxes to make them less eye-burning :)

**Comment by xt0rted** [comment]
In the middle of testing my changes they deployed a new marketplace and I had to re-do it all since the changes weren't applicable anymore 😕

One of the key changes they made is how the page's background is styled. It no longer works with our transparent/image based setup. I fixed up the colors so it looks ok but I didn't go beyond that since it didn't seem like a simple change.

**Comment by the-j0k3r** [comment]
I reoped this because some circlebadges are being styled and its just a round bg no icon.

See this URL https://github.com/marketplace?category=project-management

Its being affected by 

https://github.com/StylishThemes/GitHub-Dark/blob/871ec48f0bd301e298bac729ce5363cc2eb5ea10/github-dark.css#L3737-L3743

Easiest would be to remove it, but then only a few maybe affected.

![generic](https://user-images.githubusercontent.com/31389848/55667196-6321bd80-5859-11e9-8d07-5ce88e7a9b26.gif)

**Comment by the-j0k3r** [comment]
I think we should further brighten some of these black icon on dark grey bg to increase legibility without  killing the icon. I could have a go at it. What say ye? ;)

Also I removed an unused circlebadge bg rule in https://github.com/StylishThemes/GitHub-Dark/commit/7628109f8588ba2ed25459f1cf8c7e8c14594675 Setting important in that makes it work thought it really has a mostly global effect, which seems is not desirable.
That was  added in https://github.com/StylishThemes/GitHub-Dark/commit/868e3d79744b7a0bee9d3a934742219f58cb023e

**Comment by xt0rted** [comment]
I removed the dark background in the actions changes because it was interfering with the icons/logos used in the editor and in a number of other spots on the site. After it was added back recently I updated my custom style to include this:
```css
/* Restore background since it's being removed right now */
.CircleBadge[style*="background-color: #ffffff"] {
  background: #fff !important;
}
```

I have a couple similar rules for the marketplace since whatever changes you make to darken the images & logos just results in making something hard to see or read. There's zero benefit to me by having these darkened to I just reset them all to their defaults.

**Comment by nesl247** [comment]
Seems like there's more issues:

![image](https://user-images.githubusercontent.com/1037526/55688604-4617e800-5948-11e9-822f-9c040994580a.png)

As you can see, when browsing https://github.com/explore, some of the app names are in black text and can't be read.

**Comment by xt0rted** [comment]
The background image on those is being removed by the `.bg-gray-light` rule because it's using `background` instead of `background-color`.

This is what I'm using to fix all of these spots right now. The logos in the Popular Topics section can't be adjusted due to the original layout/html but the rest of their content is legible at least.

```css
/* Restore background since it's being removed right now */
.CircleBadge[style*="background-color: #ffffff"] {
  background-color: #fff !important;
}
.CircleBadge[style*="background-color: #ffffff"] img[src*="/ml/3919?s="] {
  filter: none !important;
}
/* Restore bg color on featured images at https://github.com/marketplace */
.MarketplaceFeature-link .bg-white {
  background-color: #fff !important;
}
/* Restore bg on popular apps at https://github.com/explore */
.MarketplaceFeature-link.bg-gray-light {
  background-color: #fafbfc !important;
}
/* Restore text color on images at https://github.com/explore */
.MarketplaceFeature-text.text-white,
.Spotlight-text.text-white h1 {
  color: #fff !important;
}
.MarketplaceFeature-text.text-gray {
  color: #586069 !important;
}
```
