### ISSUE TITLE
Developer alert variants aren't styled

### ISSUE THREAD

**Issue by xt0rted** [StylishThemes/GitHub-Dark#860]
* **Browser**: chrome
* **Operating System**: win10
* **Link to page with the issue**:
  - https://developer.github.com/marketplace/integrating-with-the-github-marketplace-api/testing-github-marketplace-apps/#using-a-development-app-with-a-draft-listing-to-test-changes
  - https://developer.github.com/changes/2019-02-14-draft-pull-requests/
* **Screenshot**:
![image](https://user-images.githubusercontent.com/831974/53305963-8ec28880-3855-11e9-8b3f-611aff15c38b.png)
![image](https://user-images.githubusercontent.com/831974/53305862-65552d00-3854-11e9-9f1c-580b546c65be.png)
* **HTML**:
```html
<div class="alert warning">
  <p>
    Do not make test purchases with an app that is live in GitHub Marketplace.
  </p>
</div>
```
```html
<div class="alert product">
  <p>
    Draft pull requests are available in public repositories with GitHub Free and GitHub Pro, and in public and private repositories with GitHub Team and GitHub Enterprise Cloud. For more information, see <a href="https://help.github.com/articles/github-s-billing-plans">GitHub's billing plans</a> in the GitHub Help documentation.
  </p>
</div>
```

## Warning

We have styles for `.warning` but the defaults from `.alert` are taking precedence. If we add a second selector of `.alert.warning` then they apply correctly.

It looks like this is happening because of the order of the rules. We might be able to fix this by adjusting the generator.

## Product

There's one custom style for this class and it comes from the generator:

```css
/* auto-generated rule for "color: #6f42c1" */
.product {
  color: #8368aa !important;
}
```

I was playing around with that purple and this is what I came up with. Thoughts?

```css
.product {
  color: #bebebe;
  background: #2c2a31; /* #8368aa with a 1% opacity against our default background #222 */
  border-color: #8368aa;
}
```

![image](https://user-images.githubusercontent.com/831974/53306154-9125e200-3857-11e9-96c4-d1a98b0646fc.png)
