### ISSUE TITLE
Weird scrollbar in application repo access list

### ISSUE THREAD

**Issue by xt0rted** [StylishThemes/GitHub-Dark#870]
* **Browser**: chrome
* **Operating System**: win10
* **Link to page with the issue**: https://github.com/:user-or-org/:repo/settings/installations then go to **Configure** and select  a couple repos
* **Screenshot**:

![image](https://user-images.githubusercontent.com/831974/53718650-c6b76600-3e29-11e9-9bd0-5c333e3540c0.png)

This shows up when you have a GitHub Application such as AppVeyor or Travis and you choose to limit it's access on a per repo basis instead of giving it access to all repos on the account.

I have the GitHub version of `StylishThemes/Overlay-Scrollbars` installed which is why the scrollbar is blue, if I turn that off the scrollbar is black just like the box it's in.

This looks to be coming from GitHub's default style but I'm not sure what needs to be fixed in either of our styles.

```css
.integrations-select-repos::-webkit-scrollbar {
  width: 10px;
}

.integrations-select-repos::-webkit-scrollbar-thumb {
  background-color: rgba(0, 0, 0, .5);
  border: 2px solid #fff;
  border-radius: 6px;
  box-shadow: 0 0 1px hsla(0, 0%, 100%, .5);
}

.integrations-select-repos::-webkit-scrollbar-track-piece {
  background: transparent;
}
```

**Comment by Mottie** [comment]
I found this in the css:

```css
.integrations-select-repos::-webkit-scrollbar {
  width: 10px;
}
.integrations-select-repos::-webkit-scrollbar-thumb {
  background-color: rgba(0,0,0,.5);
  border: 2px solid #fff;
  border-radius: 6px;
  box-shadow: 0 0 1px hsla(0,0%,100%,.5)
}
.integrations-select-repos::-webkit-scrollbar-track-piece {
  background: transparent;
}
```
