### ISSUE TITLE
white background in Explore page

### ISSUE THREAD

**Issue by GFwer** [StylishThemes/GitHub-Dark#875]
the element has an inline background style.

* **Browser**:Chrome
* **Operating System**:MacOS
* **Link to page with the issue**:https://github.com/explore
* **Screenshot**:
![image](https://user-images.githubusercontent.com/14303098/54008941-d0332c00-41a3-11e9-8231-ac746de4cbde.png)

**Comment by xt0rted** [comment]
This element has an inline style. Not sure if there's an easier way to fix this but here's my initial attempt.

```css
[style*="background: linear-gradient(#ffffff, #fcfcfc)"] {
  background: none !important;
}
```
