### ISSUE TITLE
Various color issues with the help site header

### ISSUE THREAD

**Issue by xt0rted** [StylishThemes/GitHub-Dark#880]
All of these issues happen on smaller screens, larger seems ok.

* **Browser**: chrome
* **Operating System**: win10
* **Link to page with the issue**: https://help.github.com/en/articles/viewing-your-repositorys-workflows
* **Screenshot**:

Hamburger menu icon is an svg but added via css. Looks like it needs to be inverted.

![image](https://user-images.githubusercontent.com/831974/54278397-9ded4a00-4568-11e9-9b13-91f3f4d89ec3.png)

![image](https://user-images.githubusercontent.com/831974/54278339-78604080-4568-11e9-8745-d13290fdae49.png)

**Comment by the-j0k3r** [comment]
I fixed the header colors etc., they are inline styles https://github.com/StylishThemes/GitHub-Dark/commit/4da8660e12c5a7bb7618a216dc5c5b6ad334a736, cant see any hamburger icon though.

**Comment by xt0rted** [comment]
You have to make your browser narrow enough for it to switch to mobile/tablet mode. I think the breakpoint is `768px` or something like that.

**Comment by silverwind** [comment]
Hamburger is gray on gray, very hard to spot 😉

**Comment by the-j0k3r** [comment]
I cant recreate this, resized browser window nothing, used the dev mobile mode, nothing.

Browser Chrome Version Version 73.0.3683.75 (Official Build) (64-bit)
Also Firefox 65.0.2 (64-bit) both on windows 10 pro 1709/1803

![progress-bar](https://user-images.githubusercontent.com/31389848/54301679-b9377400-45bf-11e9-9d10-836e03ccf2e6.gif)

**Comment by the-j0k3r** [comment]
Ahhhh scratch that.... press hamburger button and bang broken.

**Comment by silverwind** [comment]
Fixed that hamburger for you.

**Comment by the-j0k3r** [comment]
```css
@media (max-width: 767px)
.nav-mobile-dropdown.js-open {
    display: block;
    visibility: visible;
    width: 100%;
    position: absolute;
    top: 0;
    right: 0;
    left: 0;
    z-index: 2;
    background-color: #fafbfc;
    padding: 16px;
    padding-top: 64px;
    box-shadow: 0 1px 15px rgba(27,31,35,0.15);
}
```

thats the rule that makes things white.
