### ISSUE TITLE
Black padding in file content box

### ISSUE THREAD

**Issue by xt0rted** [StylishThemes/GitHub-Dark#892]
This looks like a newer change to the file content but it doesn't play well with our syntax themes.

* **Browser**: chrome
* **Operating System**: win10
* **Syntax theme**: Monokai
* **Link to page with the issue**: https://github.com/StylishThemes/GitHub-Dark/blob/master/defaults.json
* **Screenshot**:

![image](https://user-images.githubusercontent.com/831974/54726472-a0900680-4b49-11e9-9a5a-c8367be944cd.png)

**Comment by the-j0k3r** [comment]
That padding is coming from 

```css
.Box-body {
	border-bottom: 1px solid #e1e4e8;
	padding: 16px;
}
```
