### ISSUE TITLE
Selected tabs have different height

### ISSUE THREAD

**Issue by bfred-it** [StylishThemes/GitHub-Dark#895]
Normal:

![](https://user-images.githubusercontent.com/1402241/54876462-5067bb80-4e4b-11e9-952b-af0230f4c03c.gif)

Wrong:

![](https://user-images.githubusercontent.com/1402241/54876465-5198e880-4e4b-11e9-8445-9074fd1269da.gif)

* **Browser**: Firefox 65
* **Operating System**: macOS 10.14
* **Link to page with the issue**: https://github.com/StylishThemes/GitHub-Dark/issues

**Comment by the-j0k3r** [comment]
clearly missing the top border of 3px, perhaps try with https://github.com/StylishThemes/GitHub-Selected-Tab-Color though the default border should exist just fine.

**Comment by the-j0k3r** [comment]
Actually the issue could be solved by adding.

```css
  body .reponav-item, .pagehead-tabs-item {
    position: static !important;
  }
```
This is part of GitHub Selected Tab Color.

If you dont wish to use GHSTC for time being, try adding this style which also adds the top border.

```css
/* ==UserStyle==
@name           Github Tab Border
@namespace      StylishThemes/GitHub-Dark/#895
@version        1.0.0
@description    Hack around StylishThemes/GitHub-Dark/#895
@author         A lil elf
==/UserStyle== */

@-moz-document domain("github.com") {
  .reponav .reponav-item.selected {
    background-color: #202020 !important;
    border-top: 3px solid #e36209 !important;
    top: 0px !important;
  }
  body .reponav-item, .pagehead-tabs-item {
    position: static !important;
  }
}
```

**Comment by bfred-it** [comment]
My suggestion was to make it work correctly by default, with or without border, without extra CSS

**Comment by the-j0k3r** [comment]
> My suggestion was to make it work correctly by default, with or without border, without extra CSS

This is merely a temporary fix until its done in GHD, which btw Ive updated the style above to fix both your reported issues.

**Comment by the-j0k3r** [comment]
The issue is coming from 

https://github.com/StylishThemes/GitHub-Dark/blob/8f11b697308403aa4ee3eb1fc1b94ef97c9bf93a/github-dark.css#L4601-L4604

**Comment by the-j0k3r** [comment]
Fixed in next release. =)

**Comment by the-j0k3r** [comment]
This issue is now back when using GitHub selected tab color, and the problem is removing the 

```css
  /* reset GitHub Dark shifting tabs up */
  body .reponav-item, .pagehead-tabs-item {
    position: relative !important;
  }
```
has no effect on the tab switching up.
