### ISSUE TITLE
upstream bug: org tabs, orghead shifts up between  Teams/Projects tabs

### ISSUE THREAD

**Issue by the-j0k3r** [StylishThemes/GitHub-Dark#899]
* **Browser**: FF 66.0.2
* **Operating System**: Win 10 pro
* **Link to page with the issue**:https://github.com/orgs/StylishThemes/teams  https://github.com/orgs/StylishThemes/projects
* **Screenshot**:

![generic](https://user-images.githubusercontent.com/31389848/55220583-e1ea7b00-5207-11e9-9ec6-9cbf6e898f62.gif)

Idk what we can do about that in the meanwhile, except close your eyes.

As you can see most of the elements have different heights/padding or whatever and looks awful when switching between tabs.

As stated this is a GH upstream bug.

**Comment by the-j0k3r** [comment]
Something that seems to make this better.

```css
/* ==UserStyle==
@name           github.com - 3/29/2019, 9:56:00 AM
@namespace      github.com/openstyles/stylus
@version        1.0.0
@description    A new userstyle
@author         Me
==/UserStyle== */

@-moz-document domain("github.com") {
	.application-main .mb-3 {
		margin-bottom: 24px !important;
	}
	html:not(X) .pt-lg-3 {
    padding-top: 20px !important;
	}
	form .auto-search-group {
		margin-top: 8px !important;
	}
	.pagehead {
		margin-bottom: 24px !important;
	}
}
```
