### ISSUE TITLE
Unexpected token

### ISSUE THREAD

**Issue by 0xh3LL0** [StylishThemes/GitHub-Dark#901]
* **Browser**: Firefox 66.0.2
* **Operating System**: Win 10 10240
* **Link to page with the issue**: github.com
* **Screenshot**:
![issd](https://user-images.githubusercontent.com/23132217/55269498-b084b480-52c6-11e9-9004-bc484b81abfe.jpg)

**Comment by the-j0k3r** [comment]
Hello @0xh3LL0, and thank you for reaching out with this report.
You can safely ignore this, its CSSlint, because the usercss doesnt conform to the way options/variables are done.

Stylelint says `error | 5642 | : | 3 | Unknown word`

In this case I think its here

https://github.com/StylishThemes/GitHub-Dark/blob/246b26cc35b9db669e56921195e5238fca9a34a9/github-dark.user.css#L5642-L5649

That rule looks unclosed but due to variable and way its implemented all linters complain. Yet nothing is up.

**Comment by silverwind** [comment]
I think we should clean this error up. Maybe with some CSS variables overwritten in the theme file. Something like this:

```css
:root {
  --ghd-code-background: #181818;
  --ghd-code-color: #ccc;
}
.markdown-format pre, .markdown-body pre, .markdown-format .highlight pre,
.markdown-body .highlight pre, #facebox pre, .blob-expanded, .terminal,
.copyable-terminal, #notebook .input_area, .blob-code-context,
.markdown-format code, .api pre, .api code, .hook-delivery-details pre,
.hook-delivery-container pre, .code-list .file-box {
    background: --ghd-code-background !important;
    color: --ghd-code-color !important;
}
```

And override it with a higher specificity selector in the theme:

````css
html:root {
  --ghd-code-background: #345 !important;
  --ghd-code-color: #cde !important;
}
````
Not 100% sure if `html:root` would work, otherwise maybe `:root:root`.
