### ISSUE TITLE
Inconsistent highlight style in search results

### ISSUE THREAD

**Issue by xt0rted** [StylishThemes/GitHub-Dark#906]
* **Browser**: chrome 73
* **Operating System**: win10
* **Link to page with the issue**:
  - Solid style
    - https://github.com/StylishThemes/GitHub-Dark/search?q=bug&type=Code
    - https://github.com/StylishThemes/GitHub-Dark/search?q=bug&type=Issues
    - https://github.com/StylishThemes/GitHub-Dark/search?q=bug&type=Wikis
  - Outline style
    - https://github.com/StylishThemes/GitHub-Dark/search?q=bug&type=Commits
* **Screenshot**:

![image](https://user-images.githubusercontent.com/831974/55593271-32327300-5709-11e9-8332-54791e713623.png) ![image](https://user-images.githubusercontent.com/831974/55593255-2646b100-5709-11e9-9cb7-1b58b8761e4a.png)

**Comment by xt0rted** [comment]
The outline style seems easier to read when it's used on links.

![image](https://user-images.githubusercontent.com/831974/55593449-e633fe00-5709-11e9-82aa-77ce1f122e6f.png) ![image](https://user-images.githubusercontent.com/831974/55593466-fea41880-5709-11e9-9444-2b895806d38b.png)

![image](https://user-images.githubusercontent.com/831974/55593557-46c33b00-570a-11e9-92ac-a03e2fd5b0d6.png) ![image](https://user-images.githubusercontent.com/831974/55593551-3dd26980-570a-11e9-95a8-4ea3b995431d.png)

![image](https://user-images.githubusercontent.com/831974/55593605-6e1a0800-570a-11e9-93fb-05b40015037e.png) ![image](https://user-images.githubusercontent.com/831974/55593631-82f69b80-570a-11e9-8a29-a8223023d2d0.png)

**Comment by the-j0k3r** [comment]
I added the solid style to generator at https://github.com/StylishThemes/GitHub-Dark/commit/f1d5bb608561ae5c5a73151ee99b04d417739026 and removed manual selectors from `#333` background. 

I agree the outline is more readable, lets see whats what on these pages =)

**Comment by the-j0k3r** [comment]
OK.

The outline, original rule is 
```css
commits-list-item em {
    background-color: rgba(255,247,140,.5);
    border-radius: 3px;
    font-style: normal;
    font-weight: 600;
    padding: 3px;
```

Its in this rule atm.

```css
.compare-pr-placeholder, .compare-cutoff, .diff-cutoff, .markdown-body li.added.moved, .repo-private-label, .gist-secret-label, .label-private, .stale-files-tab, .signed-out-comment, .commits-list-item em, .unsupported-browser, .prereceive-feedback, .zhc-banner {
	background: rgba(51, 34, 17, .4) !important;
	border: 1px solid #542 !important;
	color: #ddd !important;
}
```
