### ISSUE TITLE
Payment history status icons aren't colored

### ISSUE THREAD

**Issue by xt0rted** [StylishThemes/GitHub-Dark#908]
* **Browser**: chrome 73
* **Operating System**: win10
* **Link to page with the issue**: https://github.com/account/billing/history
* **Screenshot**:

![image](https://user-images.githubusercontent.com/831974/55914950-6e0c8300-5bb6-11e9-8174-cd545e1df3f1.png) ![image](https://user-images.githubusercontent.com/831974/55914968-7b297200-5bb6-11e9-9303-dfa9bae66ea2.png)

This is happening because of https://github.com/StylishThemes/GitHub-Dark/blob/1063aec8a15ea16f0ce397880ef71a007c96e784/github-dark.css#L4325-L4399

If I remove the `!important` then other text on the site breaks such as the `Beta` label and the repo description at the top of https://github.com/StylishThemes/GitHub-Dark. I'm sure there's other spots too.

How do we want to go about fixing this one?

**Comment by silverwind** [comment]
I can't test this (not paying 😉), but how about removing the matching selector?

**Comment by xt0rted** [comment]
Looks like the offending selector in that rule is `.boxed-group-table td`. Removing it fixes the icons but I'm not sure where else uses that class. Most of the tables are actually divs or lists now and the remaining few aren't using that class.

**Comment by the-j0k3r** [comment]
you could try to exclude these from that selector.

**Comment by xt0rted** [comment]
@the-j0k3r you can't exclude those icons in the selector because they're inheriting their color from the parent element (the `td`). With where that selector is in the list it's pretty darn old so this is probably the last table using it and it's not even needed.

**Comment by xt0rted** [comment]
Long story short I was in an org with "payment issues" which is how I came across those icons. As a result GitHub put a massive banner at the top of every page because I was listed as an owner. The worst part is you can't dismiss the stupid thing.

![image](https://user-images.githubusercontent.com/831974/55929612-7e8b2080-5beb-11e9-9dd3-5a6c758c18b2.png)

If you end up with one of these banners but can't do anything about it then you can hide it with this.

```css
/* ==UserStyle==
@name           GitHub - hide unpaid bill alert
@namespace      github.com/openstyles/stylus
@version        1.0.0
@description    A new userstyle
@author         Me
==/UserStyle== */

@-moz-document domain("github.com") {
    body > div > .flash-warn {
        display: none;
    }
}
```
