### ISSUE TITLE
Hardcoded blue bg in some buttons doesnt match GH default

### ISSUE THREAD

**Issue by the-j0k3r** [StylishThemes/GitHub-Dark#909]
* **Browser**: FF 66.0.3
* **Operating System**: Win 10 Pro
* **Link to page with the issue**: https://help.github.com/en/enterprise/2.16 and https://help.github.com/en and https://github.com/pricing
* **Screenshot**:

![generic](https://user-images.githubusercontent.com/31389848/54808720-5ad65980-4c81-11e9-994a-88fc351b9d5f.gif)

![generic](https://user-images.githubusercontent.com/31389848/55930990-11e04800-5c24-11e9-98f1-f7fce6b3f321.gif)

![generic](https://user-images.githubusercontent.com/31389848/55930936-d776ab00-5c23-11e9-88e5-31ab3d6b1f7f.gif)

These look weird because these types elements have a hardcoded dark blue background that in some cases doesn't exist in default.

It would be nice to match GH default styling on these elements so we dont add styles that dont exist and cause these base-color + hardcoded blue backgrounds weird results when not using blueish colors as base color.

Probably other pages with these buttons.

We dont want these  base-color + hardcoded blue backgrounds weird results, right?

**Comment by silverwind** [comment]
They don't look bad but I suppose we could add that blue to the generator, make it a bit darker possibly and then remove the extra borders around buttons that don't have on in the original style.

**Comment by the-j0k3r** [comment]
The problem is that the borders including hover are base-color and the bg is hardcoded blue, so if you have green as a base-color these buttons look ugly and out of place, they should at least be some dark rgba version of the base-color not some darker blue.

**Comment by the-j0k3r** [comment]
Actually some of these have borders,
```css
.btn-mktg {
	display: inline-block;
	padding: 16px 24px;
	font-size: 14px;
	font-weight: 500;
	color: #fff;
	white-space: nowrap;
	vertical-align: middle;
	cursor: pointer;
	user-select: none;
	background-color: #1074e7;
	border: 1px solid #1074e7;
	border-radius: 3px;
	transition: .2s;
	appearance: none;
}

.btn-outline-mktg {
	color: #1074e7;
	background-color: rgba(255,255,255,0);
	border-color: rgba(16,116,231,0.5);
}

.btn-outline-mktg {
	color: #1074e7;
	background-color: rgba(255,255,255,0);
	border-color: rgba(16,116,231,0.5);
}
```
