### ISSUE TITLE
broken generator colors

### ISSUE THREAD

**Issue by the-j0k3r** [StylishThemes/GitHub-Dark#912]
* **Browser**: FF 66.0.3
* **Operating System**: Wn 10 pro
* **Link to page with the issue**: https://developer.github.com/v3/apps/permissions/#metadata-permissions and downwards
* **Screenshot**:

![generic](https://user-images.githubusercontent.com/31389848/56124256-885bad80-5f76-11e9-9875-90ac2f1b4592.gif)

https://github.com/StylishThemes/GitHub-Dark/blob/885e2e437f9221304212378d9ad93d5ae1ad909b/tools/generate.js#L118

Which generates this.
https://github.com/StylishThemes/GitHub-Dark/blob/885e2e437f9221304212378d9ad93d5ae1ad909b/github-dark.css#L1432-L1437

Rule should take care of the hover and doesnt, and of course were missing the default state color.

I wanted to also add color: `#4183C4` that takes care or regular link, but that also wont work, it wont even touch those elements.

Its on my local dev branch but heres the CSS
```css
  /* auto-generated rule for "color: #4183C4" */
  html[prefix] .site-header-nav .dropdown-menu a, html[prefix] a,
  .render-info .message a {
    color: /*[[base-color]]*/;
  }
```

Its not a huge problem, but it should work and yet not.

**Comment by the-j0k3r** [comment]
Before I forget, manually adding these, the selector would be `html[prefix] a code` but this would have to also have an important added and be right below the autogenerated rule else it will break other things on the side navigation.

**Comment by the-j0k3r** [comment]
Some investigation into this shows me that the issue is coming from GitHub Syntax Theme from the
```css
:root {
  color: var(--ghd-code-color, #ccc)
}
```
I think this issue can only be fixed manually. and here is my proposal.

```css
	/* manually-generated rule for "color: #4183C4" */
	html[prefix] a code {
    color: rgba(/*[[base-color-rgb]]*/, .9) !important;
  }
  /* manually-generated rule for "color: #005b9e" */
  html[prefix] a:active code, html[prefix] a:hover code {
    color: rgba(/*[[base-color-rgb]]*/, 1) !important;
  }
```

I would shunt it around   /* Base link colors */ section.

**Comment by silverwind** [comment]
Didn't read everything but this seems pretty simple to fix: Remove `.api code` manual rule near the end of the style (and test if code boxes on the api side still work after removal).

**Comment by the-j0k3r** [comment]
>Remove `.api code` manual rule near the end of the style (and test if code boxes on the api site still work after removal).

Yes, sadly that doesnt fix this at all. It remains untouched. I also had tried adding `.api:not(a) code` and the similar `html[prefix) .api:not(a) code`

Any more ideas?

**Comment by the-j0k3r** [comment]
I have another fix:

Add this to Jupiter

```css
	html[prefix] body.api li a code {
    color: rgba(/*[[base-color-rgb]]*/, .9) !important;
  }
  /* manually-generated rule for "color: #005b9e" */
  html[prefix] body.api li a:active code, html[prefix] body.api li a:hover code {
    color: rgba(/*[[base-color-rgb]]*/, 1) !important;
  }
```

and also modify `body.api code` to `body.api li:not(a) code` to fix yet another bug also in https://developer.github.com/v3/git/ code color being overwritten.
