### ISSUE TITLE
Some parts of ZenHub are dark.

### ISSUE THREAD

**Issue by jack1142** [StylishThemes/GitHub-Dark#922]
* **Browser**: Vivaldi 2.5.1511.4 with ZenHub extension
* **Operating System**: Windows 10 1803
* **Links to pages with the issue**:
[Issue page](https://github.com/StylishThemes/GitHub-Dark/issues/852)
[ZenHub board](https://github.com/StylishThemes/GitHub-Dark/issues/852#zenhub)
* **Screenshots**:
Pipelines on issue page:
![vivaldi_2019-04-21_15-22-08](https://user-images.githubusercontent.com/6032823/56470729-e2aeaf80-6449-11e9-806e-2c4460389183.png)
ZenHub board page:
![vivaldi_2019-04-21_15-21-29](https://user-images.githubusercontent.com/6032823/56470731-e3474600-6449-11e9-9c89-98cff920ab9e.png)
Creating issue from ZenHub board page:
![vivaldi_2019-04-21_15-24-43](https://user-images.githubusercontent.com/6032823/56470730-e2aeaf80-6449-11e9-8f9d-c53fbcbbe705.png)

Like you can see, some parts of ZenHub aren't completely styled (don't mind the scrollbars, that's some additional style I had loaded)

Currently I use this css as workaround:
```css
.zhc-sidebar-selector-button__heading, .zhc-sidebar-pipeline-selector__label {
    color: #949494 !important;
}

.zhc-sidebar-pipeline-selector__button__header__name {
    color: #afafaf !important;
}

.zhc-sidebar-nav-item__label {
    color: #bebebe !important;
}

.zhc-selection-button__title {
    color: #757575 !important;
}

.zh-issue-event-workspace-name {
    color: #ccc !important;
}
```
