### ISSUE TITLE
Links are white/grey on desktop and the primary color on mobile

### ISSUE THREAD

**Issue by xt0rted** [StylishThemes/GitHub-Dark#925]
The default mobile color is blue for these links, while on desktop it's black/dark grey. Do we want to adjust these to match what's on desktop or do we want to leave them as-is?

I've been wondering why the site looked odd with the dark theme on my phone and it's because of these blue links. With an OLED display they really pop on the dark background which looked off compared to what I'm used to on the desktop.

* **Browser**: kiwi browser or chrome desktop in mobile view
* **Operating System**: android 9/win10
* **Link to page with the issue**: https://github.com/StylishThemes/GitHub-Dark
* **Screenshot**:

![github com_StylishThemes_GitHub-Dark_issues(Pixel 2) (1)](https://user-images.githubusercontent.com/831974/56613133-07d72580-65e4-11e9-94f5-0f7e8e83defb.png)

![github com_StylishThemes_GitHub-Dark_issues(Pixel 2)](https://user-images.githubusercontent.com/831974/56613080-e413df80-65e3-11e9-9ac7-fadb2e530108.png)

**Comment by silverwind** [comment]
Hmm, not sure we should stray that far from the original style. IIRC, the desktop site had these colored issues at some point in time. Guess the mobile style is kind of neglected at GitHub, but may eventually update to match.

**Comment by the-j0k3r** [comment]
On another matter, those issue labels can be fixed with something like.

```css
	[class="page-responsive"] .IssueLabel {
		line-height: 1.5em !important;
		height: 20px !important;
	}
	[class="page-responsive"] .IssueLabel .g-emoji {
		margin-top: -4px !important;
	}
```
