### ISSUE TITLE
label text color

### ISSUE THREAD

**Issue by Mottie** [StylishThemes/GitHub-Dark#93]
Currently, The contrast of text within custom colored labels makes it very difficult to read

Issues page:

>  ![2014-01-19 14_01_14-issues mottie_tablesorter](https://f.cloud.github.com/assets/136959/1950400/c7ba77c4-8144-11e3-9efb-2bbc5ad5f725.png)

Within an issue (our style changes the color to `#aaa`):

> ![2014-01-19 14_14_22-differentiate internal external filter searches issue 471 mottie_tableso](https://f.cloud.github.com/assets/136959/1950424/782c806a-8146-11e3-9009-4b3feb759d20.png)

It looks like github automatically determines the contrast difference between the background color and text and set it like this:

``` css
/* Enhancement label (bright green) */
span.labelstyle-02e10c, .linked-labelstyle-02e10c {
  background-color: #02e10c !important;
  color: #fff !important;
}
/* How to... label (yellow) */
span.labelstyle-d7e102, .linked-labelstyle-d7e102 {
  background-color: #d7e102 !important;
  color: #303300 !important;
}
```

Using `-webkit-filter: invert(100%) !important` inverts all of the colors, but I'd like to keep the original background color.

Maybe just making the text color black would solve this issue in "most" cases:

``` css
.labels .label, ul.filter-list .filter-item {
  color: #000 !important;
}
```

> ![2014-01-19 14_02_34-issues mottie_tablesorter](https://f.cloud.github.com/assets/136959/1950415/c8c818fa-8145-11e3-8165-4171504ae4d8.png)

I wanted to see what the consensus was with this proposal.
