### ISSUE TITLE
GitHub sponsors alerts aren't styled

### ISSUE THREAD

**Issue by xt0rted** [StylishThemes/GitHub-Dark#949]
* **Browser**: chrome 74
* **Operating System**: win10 1903
* **Link to page with the issue**:
  - https://github.com/
  - https://github.com/users/hzoo/sponsorship
  - https://github.com/babel/babel
* **Screenshot**:

![image](https://user-images.githubusercontent.com/831974/58379485-e4502380-7f71-11e9-84ae-218666c04082.png)

![image](https://user-images.githubusercontent.com/831974/58379495-02b61f00-7f72-11e9-8058-13fefadffafc.png)

**Comment by xt0rted** [comment]
These alerts/banners look to be using some inline styles while the pink text on the next screen uses the classes `.text-pink` and `.color-pink-5`.

![image](https://user-images.githubusercontent.com/831974/58379518-64768900-7f72-11e9-8d18-3b32e143ad13.png)

In the `frameworks-####.css` file there's a number of new classes called `.bg-pink`, `.bg-pink-#`, `.color-pink-#`, and `.text-pink`. There's 10 shades going from `0-9` that we need to handle.

**Comment by the-j0k3r** [comment]
Shame we cant have root values in generator

**Comment by silverwind** [comment]
> we cant have root values in generator

What do you mean? `:root`?

**Comment by the-j0k3r** [comment]
> What do you mean? `:root`?

Yes.

**Comment by silverwind** [comment]
@the-j0k3r can you show a example of a `:root` style that you want to cover? I'm sure it can be made to work.

Regarding this issue, I think we can manually target them. I see a inline style with value `background: #ffeef860; border-bottom: 1px solid #f9b3dd;` which whould be hard to cover in the generator.

**Comment by silverwind** [comment]
Fixed the header with the inline style. Does anyone have the HTML of the frontpage box? I unfortunately already dismissed it.

**Comment by xt0rted** [comment]
The main issue here is `#ffeef860`. I'm thinking change the background to `#1a0914` and border to `#572844` which are the originals with `filter: invert(100%) hue-rotate(180deg)` applied.

![image](https://user-images.githubusercontent.com/831974/58579918-023fb180-821a-11e9-9bb6-5b206bc04583.png)

**Comment by silverwind** [comment]
Also, I tried adding those pink shades to the generator, but I decided against keeping them because the number of `mappings` entries currently has quite a bit of impact on the performance of the tool which I'd like to solve first before adding huge numbers of mappings.

For the record, these were the generated rules:

````css
  /* auto-generated rule for "background-color: #ffeef8 !important" */
  .bg-pink-0, body[class="page-responsive"] .bg-pink-0 {
    background-color: #ffeef8 !important;
  }
  /* auto-generated rule for "background-color: #fedbf0 !important" */
  .bg-pink-1, body[class="page-responsive"] .bg-pink-1 {
    background-color: #fedbf0 !important;
  }
  /* auto-generated rule for "background-color: #f9b3dd !important" */
  .bg-pink-2, body[class="page-responsive"] .bg-pink-2 {
    background-color: #f9b3dd !important;
  }
  /* auto-generated rule for "background-color: #f692ce !important" */
  .bg-pink-3, body[class="page-responsive"] .bg-pink-3 {
    background-color: #f692ce !important;
  }
  /* auto-generated rule for "background-color: #ec6cb9 !important" */
  .bg-pink-4, body[class="page-responsive"] .bg-pink-4 {
    background-color: #ec6cb9 !important;
  }
  /* auto-generated rule for "background-color: #ea4aaa !important" */
  .bg-pink, .bg-pink-5, body[class="page-responsive"] .bg-pink,
  body[class="page-responsive"] .bg-pink-5 {
    background-color: #ea4aaa !important;
  }
  /* auto-generated rule for "background-color: #d03592 !important" */
  .bg-pink-6, body[class="page-responsive"] .bg-pink-6 {
    background-color: #d03592 !important;
  }
  /* auto-generated rule for "background-color: #b93a86 !important" */
  .bg-pink-7, body[class="page-responsive"] .bg-pink-7 {
    background-color: #b93a86 !important;
  }
  /* auto-generated rule for "background-color: #99306f !important" */
  .bg-pink-8, body[class="page-responsive"] .bg-pink-8 {
    background-color: #99306f !important;
  }
  /* auto-generated rule for "background-color: #6d224f !important" */
  .bg-pink-9, body[class="page-responsive"] .bg-pink-9 {
    background-color: #6d224f !important;
  }
````
