### ISSUE TITLE
Unreadable background for warning output in jupyter notebook

### ISSUE THREAD

**Issue by Thesharing** [StylishThemes/GitHub-Dark#950]
* **Browser**: Google Chrome
* **Operating System**: Windows 10
* **Link to page with the issue**: https://github.com/huseinzol05/NLP-Models-Tensorflow/blob/master/text-classification/64.transformer-xl.ipynb
* **Screenshot**: 

![Snipaste_2019-05-30_16-23-26](https://user-images.githubusercontent.com/6576831/58619490-99c70200-82f7-11e9-8690-f619ca71ba79.png)

The background of warning output in jupyter notebook is unreadable because the background is
```css
div.output_stderr {
    background: #fdd
}
```

and the foreground color in style `Github Dark (Native)` is:

```css
pre {
    color: #bebebe !important;
}
```

So it would be nice if the background color could be changed into a darker one.

**Comment by the-j0k3r** [comment]
Hi @Thesharing ! Thank you for reaching out to us with this issue report.

At first look it seems we never supported this `div.output_stderr` background in any of our jupyter themes,

Hers s an updated minified twilight theme to handle this.

```css
#notebook div.output_stderr {background: #420e09}#notebook .input_area, body.api pre, :matches(#notebook, body.api) .highlight, :matches(#notebook, body.api) .highlight pre, :matches(#notebook, body.api) .highlight table {background: #141414 !important;color: #ccc !important;}:matches(#notebook, body.api) .highlight .hll, .highlight code .hll {background-color: #ffc !important;}:matches(#notebook, body.api) .highlight .err, .highlight code .err {border: #B22518 !important;}:matches(#notebook, body.api) .highlight .c, .highlight code .c {color: #5f5a60 !important;font-style: italic !important;}:matches(#notebook, body.api) .highlight .g, .highlight code .g {}:matches(#notebook, body.api) .highlight .h, .highlight code .h {}:matches(#notebook, body.api) .highlight .k, .highlight code .k {color: #cda869 !important;}:matches(#notebook, body.api) .highlight .l, .highlight code .l {}:matches(#notebook, body.api) .highlight .m, .highlight code .m {}:matches(#notebook, body.api) .highlight .n, .highlight code .n {}:matches(#notebook, body.api) .highlight .o, .highlight code .o {}:matches(#notebook, body.api) .highlight .p, .highlight code .p {}:matches(#notebook, body.api) .highlight .s, .highlight code .s {}:matches(#notebook, body.api) .highlight .w, .highlight code .w {}:matches(#notebook, body.api) .highlight .x, .highlight code .x {}:matches(#notebook, body.api) .highlight .w, .highlight code .w {color: #141414 !important;}:matches(#notebook, body.api) .highlight .cm, .highlight code .cm {color: #5f5a60 !important;font-style: italic !important;}:matches(#notebook, body.api) .highlight .cp, .highlight code .cp {color: #5f5a60 !important;}:matches(#notebook, body.api) .highlight .c1, .highlight code .c1 {color: #5f5a60 !important;font-style: italic !important;}:matches(#notebook, body.api) .highlight .cs, .highlight code .cs {color: #5f5a60 !important;font-style: italic !important;}:matches(#notebook, body.api) .highlight .gd, .highlight code .gd {background: #420e09 !important;}:matches(#notebook, body.api) .highlight .ge, .highlight code .ge {font-style: italic !important;}:matches(#notebook, body.api) .highlight .gr, .highlight code .gr {background: #b22518 !important;}:matches(#notebook, body.api) .highlight .gh, .highlight code .gh {color: #000080 !important;font-weight: bold !important;}:matches(#notebook, body.api) .highlight .gi, .highlight code .gi {background: #253b22 !important;}:matches(#notebook, body.api) .highlight .go, .highlight code .go {}:matches(#notebook, body.api) .highlight .gp, .highlight code .gp {font-weight: bold !important;}:matches(#notebook, body.api) .highlight .gs, .highlight code .gs {font-weight: bold !important;}:matches(#notebook, body.api) .highlight .gu, .highlight code .gu {color: #800080 !important;font-weight: bold !important;}:matches(#notebook, body.api) .highlight .gt, .highlight code .gt {}:matches(#notebook, body.api) .highlight .kc, .highlight code .kc {}:matches(#notebook, body.api) .highlight .kd, .highlight code .kd {color: #e9df8f !important;}:matches(#notebook, body.api) .highlight .kn, .highlight code .kn {}:matches(#notebook, body.api) .highlight .kp, .highlight code .kp {color: #9b703f !important;}:matches(#notebook, body.api) .highlight .kr, .highlight code .kr {}:matches(#notebook, body.api) .highlight .kt, .highlight code .kt {}:matches(#notebook, body.api) .highlight .na, .highlight code .na {color: #f9ee98 !important;}:matches(#notebook, body.api) .highlight .nb, .highlight code .nb {color: #cda869 !important;}:matches(#notebook, body.api) .highlight .nc, .highlight code .nc {color: #9b859d !important;font-weight: bold !important;}:matches(#notebook, body.api) .highlight .no, .highlight code .no {color: #9b859d !important;}:matches(#notebook, body.api) .highlight .nd, .highlight code .nd {color: #7587a6 !important;}:matches(#notebook, body.api) .highlight .ni, .highlight code .ni {color: #cf6a4C !important;font-weight: bold !important;}:matches(#notebook, body.api) .highlight .nf, .highlight code .nf {color: #9b703f !important;font-weight: bold !important;}:matches(#notebook, body.api) .highlight .nn, .highlight code .nn {color: #9b859d !important;font-weight: bold !important;}:matches(#notebook, body.api) .highlight .nt, .highlight code .nt {color: #cda869 !important;font-weight: bold !important;}:matches(#notebook, body.api) .highlight .nv, .highlight code .nv {color: #7587a6 !important;}:matches(#notebook, body.api) .highlight .ow, .highlight code .ow {color: #a2f !important;font-weight: bold !important;}:matches(#notebook, body.api) .highlight .mf, .highlight code .mf {color: #cf6a4c !important;}:matches(#notebook, body.api) .highlight .mh, .highlight code .mh {color: #cf6a4c !important;}:matches(#notebook, body.api) .highlight .mi, .highlight code .mi {color: #cf6a4c !important;}:matches(#notebook, body.api) .highlight .mo, .highlight code .mo {color: #cf6a4c !important;}:matches(#notebook, body.api) .highlight .sb, .highlight code .sb {color: #8f9d6a !important;}:matches(#notebook, body.api) .highlight .sc, .highlight code .sc {color: #8f9d6a !important;}:matches(#notebook, body.api) .highlight .sd, .highlight code .sd {color: #8f9d6a !important;font-style: italic !important;}:matches(#notebook, body.api) .highlight .s2, .highlight code .s2 {color: #8f9d6a !important;}:matches(#notebook, body.api) .highlight .se, .highlight code .se {color: #f9ee98 !important;font-weight: bold !important;}:matches(#notebook, body.api) .highlight .sh, .highlight code .sh {color: #8f9d6a !important;}:matches(#notebook, body.api) .highlight .si, .highlight code .si {color: #daefa3 !important;font-weight: bold !important;}:matches(#notebook, body.api) .highlight .sx, .highlight code .sx {color: #8f9d6a !important;}:matches(#notebook, body.api) .highlight .sr, .highlight code .sr {color: #e9c062 !important;}:matches(#notebook, body.api) .highlight .s1, .highlight code .s1 {color: #8f9d6a !important;}:matches(#notebook, body.api) .highlight .ss, .highlight code .ss {color: #cf6a4c !important;}:matches(#notebook, body.api) .highlight .bp, .highlight code .bp {color: #0aa !important;}:matches(#notebook, body.api) .highlight .vc, .highlight code .vc {color: #7587a6 !important;}:matches(#notebook, body.api) .highlight .vg, .highlight code .vg {color: #7587a6 !important;}:matches(#notebook, body.api) .highlight .vi, .highlight code .vi {color: #7587a6 !important;}:matches(#notebook, body.api) .highlight .il, .highlight code .il {color: #099 !important;}
```

If none gets to this first, Ill have a go later.
