### ISSUE TITLE
respect notification color icon when using github-refined extension

### ISSUE THREAD

**Issue by ilyam8** [StylishThemes/GitHub-Dark#951]
First of all thanks for the work, `github-dark` is awesome :+1: 

The Issue:
Default notification color is blue. i am using ~`github-redefined`~ [`github-refined`](https://github.com/sindresorhus/refined-github) plugin, it has `mark as unread` feature. And it adds additional notification color. The color is green, it means that you have only marked as unread issues.

`github-dark` doesn't respect the color and changes it to blue. 

* **Browser**:
> Version 74.0.3729.169 (Official Build) Arch Linux (64-bit)

* **Operating System**:
> Linux 4.19.45-1-MANJARO

* **Link to page with the issue**:

* **Screenshot**:

w/o github-dark

![Screenshot_20190531_000232](https://user-images.githubusercontent.com/22274335/58664665-c864cd00-8337-11e9-89e8-d94dcfa09852.png)

___

w/ github-dark
![Screenshot_20190531_000243](https://user-images.githubusercontent.com/22274335/58664679-d3b7f880-8337-11e9-988b-a77f84a17b17.png)

**Comment by the-j0k3r** [comment]
Hello @ilyam8! Thank for reaching out with this report.

Our notification icon uses the custom base-color, its intended.

**Comment by ilyam8** [comment]
So it is wontfix? It is very nice to have different notification colors, it is clear when you have unread messages (blue) or only marked as unread (green).

**Comment by the-j0k3r** [comment]
Well, I wouldn't say its a necessarily a wont fix, GitHub Default also uses blue see below CSS, our default base-color is also a blue base-color. but if you change it to green/other this will also chnage along with links etc.

```css
.notification-indicator .mail-status {
	background-clip: padding-box;
	background-image: linear-gradient(#54a3ff,#006eed);
	border: 2px solid #24292e;
	border-radius: 50%;
	color: #fff;
	display: none;
	height: 14px;
	left: 6px;
	position: absolute;
	top: -6px;
	width: 14px;
	z-index: 2;
}
```

You can however, for GHD and build GHD with this tweak  Its located in 

```css
  /* notification icon */
  .notification-indicator .mail-status {
    background: /*[[base-color]]*/ !important;
    border-color: #1d1d1d !important;
  }
```

Im unsure if we supported yet another GitHub extension what would be done about it, lets ask @silverwind @mottie @xt0rted what their thoughts are on this subject.

My vote though is to keep it as is, because supporting your extension and adding different colors that dont match our styling for same areas seems counter intuitive, that said I wont oppose a majority decision on this.

**Comment by the-j0k3r** [comment]
It occurs to me we could also add a specific custom color choice for this, that way, the color would be the default GHD blue and you could change it to whatever you like, I think that would be the best easiest way to accommodate this rather than adding support for a full extension.

Though if you have real conflicts between the two that means still having to support yet another extension.

**Comment by ilyam8** [comment]
thx @the-j0k3r , i installed modified usercss.

That is how it works with github-refined: 
  - case `if there is at least one unread message`: blue
  - case `zero unread, only marked as unread`: green


https://github.com/sindresorhus/refined-github/pull/683

Back to your usercss. With it i always have `unread mail color`.

**Comment by the-j0k3r** [comment]
We cant actually differentiate afaik between one/more/unread messages with just CSS. That extension is using js.

We have https://github.com/StylishThemes/GitHub-Dark-Script which would probably with some modifications handle that. @silverwind or @Mottie would know what to do there.

**Comment by the-j0k3r** [comment]
```css
/* ==UserStyle==
@name        Refined GH Notification Colors
@namespace   StylishThemes
@version     1.0.0
@license     CC-BY-SA-4.0
@author      StylishThemes
@advanced color base-color "Base color scheme" #4f8cc9
@advanced color notification-base-color "Unread mail color" #4f8cc9
==/UserStyle== */
@-moz-document regexp("^https?://((gist|guides|help|launch-editor|raw|resources|status|developer)\\.)?github\\.com/((?!generated_pages/preview).)*$"), domain("githubusercontent.com"), domain("graphql-explorer.githubapp.com") {
  /* notification icon */
  .refined-github .notification-indicator .mail-status {
    background: /*[[base-color]]*/ !important;
    border-color: #1d1d1d !important;
  }
  .refined-github .notification-indicator[data-ga-click$=":read"] .unread {
    background: /*[[notification-base-color]]*/ !important;
    border-color: #1d1d1d !important;
  }
}
```

@ilyam8 try that style
