### ISSUE TITLE
Code navigation

### ISSUE THREAD

**Issue by xt0rted** [StylishThemes/GitHub-Dark#952]
This is a new beta feature that was just opened up to a group of public repos.
- https://github.blog/changelog/2019-06-11-jump-to-definition-in-public-repositories/
- https://help.github.com/en/articles/navigating-code-on-github

* **Browser**: chrome
* **Operating System**: win10
* **Link to page with the issue**: https://github.com/encode/django-rest-framework/blob/master/rest_framework/fields.py#L67
* **Screenshot**:

![image](https://user-images.githubusercontent.com/831974/59303717-ca4a5c80-8c64-11e9-808f-22bccfe9ca17.png)

![image](https://user-images.githubusercontent.com/831974/59303744-d7ffe200-8c64-11e9-9ae6-0b04970afeef.png)

**Comment by the-j0k3r** [comment]
So this is a fix for syntax themes

```css
.pl-token.active, .pl-token:hover {
	background: #ffea7f;
	cursor: pointer;
}
```

**Comment by silverwind** [comment]
Also should (manually) remove that gradient from info box. No idea why it's there as it's white on white in the original.

**Comment by the-j0k3r** [comment]
I added that box to generator. Im testing the fixes now in all themes should push in 2mins or so.

**Comment by the-j0k3r** [comment]
There is one remaining thing.

![Capture](https://user-images.githubusercontent.com/31389848/59345976-9aa55e00-8d11-11e9-876c-863d6daf2b7b.PNG)

The dot has a inline style, thought targeting it doesnt work here :/

![Capture](https://user-images.githubusercontent.com/31389848/59346417-82820e80-8d12-11e9-8ec3-927aec68dbcc.PNG)

**Comment by silverwind** [comment]
As long as no `!important` style is overriding that green on that dot, we don't have to style it at all.

**Comment by xt0rted** [comment]
That green dot is a status indicator. It has at least two known states right now of complete and pending. Complete is green and pending is yellow (`#d3ac3b`). They can be styled with the following:

```css
.octicon-primitive-dot[style^="color: #28a745"] {
    color: #6cc644 !important;
}

.octicon-primitive-dot[style^="color: #d3ac3b"] {
    color: #cb4 !important;
}
```
