### ISSUE TITLE
New issue write/preview tabs not fully styled in mobile/responsive view

### ISSUE THREAD

**Issue by xt0rted** [StylishThemes/GitHub-Dark#957]
This page is responsive so you can see the issue by changing the size of your browser window or using the responsive view in dev tools. The screenshot below is without the selected tab color style enabled.

* **Browser**: chrome/edge/kiwi browser
* **Operating System**: win10/android 9
* **Link to page with the issue**: https://github.com/StylishThemes/GitHub-Dark/issues/new
* **Screenshot**:

![github com_StylishThemes_GitHub-Dark_issues_new(Pixel 2)](https://user-images.githubusercontent.com/831974/59720315-861f0500-91ec-11e9-85c1-976324718b40.png)

**Comment by the-j0k3r** [comment]
Related to [Mobile tabs need better styling](https://github.com/StylishThemes/GitHub-Dark/issues/924) issue

**Comment by xt0rted** [comment]
This is related but slightly different. This was working [when the page was switching to be responsive](https://github.blog/changelog/2019-05-09-new-features-for-issue-creation-on-mobile/), but recently it broke (in the last week or two I think).

**Comment by the-j0k3r** [comment]
Heres the affected CSS
```css
.tabnav--responsive .tabnav-tab.selected {
	background-color: #fff;
	border-bottom: 0;
}

.tabnav--responsive .tabnav-tab:first-child {
	border-left: 1px solid #e1e4e8;
}

.tabnav--responsive .tabnav-tab {
	background-color: #f6f8fa;
	border: 1px solid #e1e4e8;
	border-left: 0;
	border-radius: 0;
}
```
