### ISSUE TITLE
Author avatars in the network graph are inverted

### ISSUE THREAD

**Issue by AfroThundr3007730** [StylishThemes/GitHub-Dark#961]
Normally I'd post the offending selectors, etc. but the network graph is rendered on a canvas element, and I have no idea how to inspect that (the devtools used to have a canvas tab, but not anymore). Screenshot attached.

* **Browser**: Firefox Nightly 69.0a1 2019-06-24
* **Operating System**: Debian 10 Testing x86_64
* **Link to page with the issue**: Example from the Wikipedia-Dark repo
* **Screenshot**: 

![Screenshot_20190624_185448](https://user-images.githubusercontent.com/7613032/60063706-60629600-96ed-11e9-935e-ea88465b8605.png)

**Comment by Mottie** [comment]
Duplicate of #583. If you have a solution, we'd be happy to implement it.

**Comment by the-j0k3r** [comment]
ATM its this:
`    filter: invert(90%) hue-rotate(180deg) contrast(90%) !important;`

We could do this.

```css
  /* invert network graph; gh-polls (https://github.com/apex/gh-polls) */
  div#network.network > div > canvas, img[alt="FOSSA Status"],
  img[data-canonical-src*="prod/timeseries/"],
  a[href$="vote"] img[data-canonical-src*="/poll/"], #parallax_error_text:not(p),
  img[data-canonical-src*="img.shields.io"][data-canonical-src*="style=social"] {
    filter: invert(90%) hue-rotate(180deg) contrast(120%) !important;
    mix-blend-mode: exclusion;
  }
```

This mix-blend-mode is more granular though it actually doesnt fix the inverted avatars the result is better. Though not sure about the other selectors in that rule how this affects them.
