### ISSUE TITLE
Additional styles for date inputs

### ISSUE THREAD

**Issue by xt0rted** [StylishThemes/GitHub-Dark#962]
It's always bugged me that, in chrome at least, the date inputs on the edit milestone page have an unstyled dropdown arrow on hover. After looking into this more it seems we can style this like so:

```scss
::-webkit-calendar-picker-indicator {
  background-color: #181818;
  color: #c9c9c9; // the arrow
}

::-webkit-calendar-picker-indicator:hover {
  color: #666; // should we also darken it on hover?
}
```

I'm not sure what the exact color is that was used in the select box arrow image, but using the color picker I got `#c9c9c9`. Does anyone know if the value I got is correct?

The calendar popup itself, even when using chrome's dark theme, isn't styled but I don't think there's any way for us to do that with css.

**Before**

![image](https://user-images.githubusercontent.com/831974/61241142-f1d38f80-a710-11e9-8418-b76254962f2e.png)

**After**

![image](https://user-images.githubusercontent.com/831974/61240660-c0a68f80-a70f-11e9-9274-82b0132d97c0.png)
