### ISSUE TITLE
Zenhub issue title and textbox color

### ISSUE THREAD

**Issue by jarhoax** [StylishThemes/GitHub-Dark#968]
* **Browser**: Chrome
* **Operating System**: macOS
* **Link to page with the issue**: -
* **Screenshot**: - 

When creating a new issue via the Zenhub Chrome plugin, the issue title and textarea color is black. This makes it barely readable when entering text.

Adding this to the style file fixes it for now but maybe you can address this in an update.

```css
.zhc-new-issue-body__title-input, .zhc-edit-comment__textarea {
    color: #BEBEBE
}
```

Thank you.

**Comment by the-j0k3r** [comment]
@jarhoax thank you for bringing this issue to our attention.

I think this is now automatically generated so Im guessing next release will do it, if not @silverwind or me will add this up.

**Comment by jarhoax** [comment]
Appreciate.

**Comment by silverwind** [comment]
Can you share the original CSS rules affecting the text?

**Comment by jarhoax** [comment]
Would be happy to share, what exactly are you looking for? There are plenty of rules affecting some `zhc` prefix, e.g.

```css
 /* auto-generated rule for "color: #333 !important" */
  html[prefix] .link-gray-dark, body.zh_logged_in .zhu-color-text {
    color: #bebebe !important;
  }
```

or 

```css
  /* auto-generated rule for "color: #333" */
  .session-authentication .header-logo,
  .session-authentication .auth-form-header, .intgrs-lstng-item-header,
  .listgroup-item.disabled .listgroup-item-title, .billing-plans .name,
  .billing-section .section-content, .lfs-data-icon.dark,
  .milestone-title-link a, .org-name, .reinstate-org-member .reinstate-title,
  .stats-group-stat.no-link:hover .stat-number, .stat-number,
  .org-user-notice-content strong, .manage-memberships-tabs-item:hover,
  .diffstat-summary strong, .clone-url-button > .clone-url-link,
  .clone-url-button.selected > .clone-url-link,
  .clone-url-button.selected > .clone-url-link:hover,
  .oauth-app-info-container dl.keys dd, .protected-branch-pusher,
  .typeahead-result, .hljs, .hljs-keyword, .hljs-selector-tag, .hljs-subst,
  html[prefix] .text-emphasized, html[prefix] .Box-row-link,
  html[prefix] .social-count, html[prefix] .form-control,
  html[prefix] .form-select, html[prefix] p.explain strong,
  html[prefix] .Counter--gray-light, html[prefix] .menu-item .octicon,
  html[prefix] .tabnav-tab.selected,
  html[prefix] .markdown-body span.frame span span,
  html[prefix] .site-header-nav-item:hover,
  html[prefix] .site-header-nav-item.active, html[prefix] .sub-nav h2 a,
  html[prefix] .highlight-module .mega-octicon,
  html[prefix] .octokit-language span, html[prefix] .headlines > li > a,
  html[prefix] .js-current .standalone a,
  html[prefix] .sidebar-module .disable > a, html[prefix] .content .anchor,
  html[prefix] #markdown-toc li a, body[data-render-url] .click-for-more .button,
  body.zh_logged_in .zh-form-control, body.zh_logged_in .zh-form-control-small,
  body.zh_logged_in .zh-issue-event-dark,
  body.zh_logged_in .zh-connect-repository-container a,
  body.zh_logged_in .zh-power .zh-pipeline-options,
  body.zh_logged_in .zh-board-menu-item .btn, body.zh_logged_in .zh-reports .btn,
  body.zh_logged_in .zh-reports .btn:hover,
  body.zh_logged_in .zh-mergetool-pipelines-dialog .zh-mergetool-info,
  body.zh_logged_in .zh-mergetool-pipelines-dialog .zh-miniboard-wrapper .zh-miniboard-pipeline,
  body.zh_logged_in .zh-epic-issue-header strong,
  body.zh_logged_in .zh-epic-issue-header-title,
  body.zh_logged_in .zh-epic-issue-progress-text strong,
  body.zh_logged_in .zh-select-menu-header .zh-select-menu-title,
  body.zh_logged_in .zh-epic-header .zh-pipeline-is,
  body.zh_logged_in .zh-epic-header .zh-pipeline-was,
  body.zh_logged_in .zh-epic-header .zh-estimate-is,
  body.zh_logged_in .zh-epic-header .zh-estimate-was,
  body.zh_logged_in .zh-epic-header .zh-issue,
  body.zh_logged_in .zh-epic-issue-list-item-title-link,
  body.zh_logged_in .zh-epic-creator-issue-list .zh-epic-creator-issue-list-not-in-workspace,
  body.zh_logged_in .zh-epic-form-control,
  body.zh_logged_in .zh-epic-form-control-small, body.zh_logged_in .hljs,
  body.zh_logged_in .hljs-keyword, body.zh_logged_in .hljs-selector-tag,
  body.zh_logged_in .hljs-subst, body.zh_logged_in .zhc-btn,
  body.zh_logged_in .zhu-text-important,
  body.zh_logged_in .zhc-account-settings__section h3,
  body.zh_logged_in .zhc-account-settings__section strong,
  body.zh_logged_in .zhc-organization-admin-item__username,
  body.zh_logged_in .zhc-banner strong,
  body.zh_logged_in .zhc-burndown-chart__stats__detail strong,
  body.zh_logged_in .zhc-choose-organization__title,
  body.zh_logged_in .zhc-choose-organization__section-title,
  body.zh_logged_in .zhc-organization-item__name,
  body.zh_logged_in .zhc-collapsible-control:hover.zhc-collapsible-control--grey:not(.zhc-collapsible-control--border),
  body.zh_logged_in .zhc-control-chart-report__chart_stat .zhc-chart-emphasis,
  body.zh_logged_in .zhc-add-dependency__error-message .zhu-font-bold,
  body.zh_logged_in .zhc-dependency-item-simple__header,
  body.zh_logged_in .zhc-empty-state h1,
  body.zh_logged_in .zhc-epic-pipeline-list--item__title,
  body.zh_logged_in .zhc-error-page__header__title,
  body.zh_logged_in .zhc-error-page__header__description,
  body.zh_logged_in .zhc-integrations-item .zhc-integrations__repo,
  body.zh_logged_in .zhc-integrations-item .zhc-integrations__service,
  body.zh_logged_in .zhc-integrations-item .zhc-integrations__hook:first-child:not(:last-child),
  body.zh_logged_in .zhc-issue-card__issue-title,
  body.zh_logged_in .zhc-issue-card__heading__main,
  body.zh_logged_in .zhc-issue-card__epic-filter,
  body.zh_logged_in .zhc-add-comment__username,
  body.zh_logged_in .zhc-comment__username,
  body.zh_logged_in .zhc-issue-description,
  body.zh_logged_in .zhc-issue-meta__username,
  body.zh_logged_in .zhc-new-issue-body__username,
  body.zh_logged_in .zhc-issue-item__title,
  body.zh_logged_in .zhc-sidebar-assign-yourself--read-only:hover,
  body.zh_logged_in .zhc-sidebar-epic-selector .zhc-sidebar-active-epics a,
  body.zh_logged_in .zhc-sidebar-pipeline-selector__label,
  body.zh_logged_in .zhc-sidebar-active-pipeline__name,
  body.zh_logged_in .zhc-sidebar-pipeline-selector__button,
  body.zh_logged_in .zhc-sidebar-pipeline-selector__button.zhc-sidebar-pipeline-selector__button--disabled:active,
  body.zh_logged_in .zhc-sidebar-pipeline-selector__button.zhc-sidebar-pipeline-selector__button--disabled:focus,
  body.zh_logged_in .zhc-sidebar-pipeline-selector__button.zhc-sidebar-pipeline-selector__button--disabled:hover,
  body.zh_logged_in .zhc-sidebar-pipeline-selector__button.zhc-sidebar-pipeline-selector__button--disabled:active .zhc-sidebar-active-pipeline__name,
  body.zh_logged_in .zhc-sidebar-pipeline-selector__button.zhc-sidebar-pipeline-selector__button--disabled:focus .zhc-sidebar-active-pipeline__name,
  body.zh_logged_in .zhc-sidebar-pipeline-selector__button.zhc-sidebar-pipeline-selector__button--disabled:hover .zhc-sidebar-active-pipeline__name,
  body.zh_logged_in .zhc-sidebar-selector-button,
  body.zh_logged_in .zhc-sidebar-selector-button--no-hover:active .zhc-sidebar-selector-button__heading,
  body.zh_logged_in .zhc-sidebar-selector-button--no-hover:focus .zhc-sidebar-selector-button__heading,
  body.zh_logged_in .zhc-sidebar-selector-button--no-hover:hover .zhc-sidebar-selector-button__heading,
  body.zh_logged_in .zhc-issues-list-item__title a,
  body.zh_logged_in .zhc-issues-list-item__issue_number,
  body.zh_logged_in .zhc-login__content,
  body.zh_logged_in .zhc-manage-plan__renewal-date strong,
  body.zh_logged_in .zhc-merge-repo-finder__header,
  body.zh_logged_in .zhc-merge-repo-finder__header__text,
  body.zh_logged_in .zhc-merge-repo-finder-input__label,
  body.zh_logged_in .zhc-merging-tool-pipeline-card__repo-name,
  body.zh_logged_in .zhc-merging-tool-pipeline-card--all-issues .zhc-merging-tool-pipeline-card__issue-count,
  body.zh_logged_in .zhc-merging-tool-repo-dropdown .zhc-selection-button,
  body.zh_logged_in .zhc-merging-tool-repo-dropdown__repo-name,
  body.zh_logged_in .zhc-milestone-panel__title,
  body.zh_logged_in .zhc-milestone-start-date__date,
  body.zh_logged_in .zhc-multi-action-placeholder__primary-text,
  body.zh_logged_in .zhc-app-notification__title,
  body.zh_logged_in .zhc-notifications-body__header__title,
  body.zh_logged_in .zhc-notifications-manager__item-name,
  body.zh_logged_in .zhc-notifications-manager__header,
  body.zh_logged_in .zhc-pipeline-form__input,
  body.zh_logged_in .zhc-pipeline-form__text-area,
  body.zh_logged_in .zhc-pr-issue-connector__issue__title a,
  body.zh_logged_in .zhc-release-connected-repos-dropdown__repo-item,
  body.zh_logged_in .zhc-release-event__item.zhc-release-event__item--author,
  body.zh_logged_in .zhc-release-event__item.zhc-release-event__item--scope,
  body.zh_logged_in .zhc-release-event__item--date--highlighted,
  body.zh_logged_in .zhc-release-event-link a,
  body.zh_logged_in .zhc-release--no-issues__content h2,
  body.zh_logged_in .zhc-release-report__date .zhc-release-report__date__value,
  body.zh_logged_in .zhc-release-report__date .zhc-due-date,
  body.zh_logged_in .zhc-reports-date-range .zhc-reports-date-range__date-range,
  body.zh_logged_in .zhc-reports-date-range .zhc-dropdown--reports-dates .zhc-selection-button__title .zhc-reports-date-range__date-range,
  body.zh_logged_in .zhc-reports-date-range .DateRangePickerInput .DateInput .DateInput__display-text,
  body.zh_logged_in .zhc-reports-date-range .CalendarMonth__caption,
  body.zh_logged_in .zhc-reports-date-range .DayPicker__week-header,
  body.zh_logged_in .zhc-report-card__title,
  body.zh_logged_in .zhc-report-tabs__nav .zhc-report-tabs__nav__item:hover,
  body.zh_logged_in .zhc-report-tabs__nav .zhc-report-tabs__nav__item--active,
  body.zh_logged_in .zhc-request-license-text,
  body.zh_logged_in .zhc-selection-list__header,
  body.zh_logged_in .zhc-selection-list__header__text,
  body.zh_logged_in .zhc-shortcuts-guide__section h2,
  body.zh_logged_in .zhc-sidebar-nav-item,
  body.zh_logged_in .zhc-sidebar-nav-item__link,
  body.zh_logged_in .zhc-sidebar-nav-item__sub-item:hover,
  body.zh_logged_in .zhc-sidebar-profile__name,
  body.zh_logged_in .zhc-tabs--dropdown .zhc-tabs__nav-item--active,
  body.zh_logged_in .zhc-tabs--dropdown .zhc-tabs__nav-item--active:hover,
  body.zh_logged_in .zhc-timeline-button,
  body.zh_logged_in .zhc-timeline-button[disabled],
  body.zh_logged_in .zhc-timeline-button[disabled]:active,
  body.zh_logged_in .zhc-timeline-button[disabled]:focus,
  body.zh_logged_in .zhc-timeline-button[disabled]:hover,
  body.zh_logged_in .zhc-timeline-button.zhc-timeline-button--variant-text,
  body.zh_logged_in .zhc-timeline-button.zhc-timeline-button--variant-text[disabled],
  body.zh_logged_in .zhc-timeline-button.zhc-timeline-button--variant-text[disabled]:active,
  body.zh_logged_in .zhc-timeline-button.zhc-timeline-button--variant-text[disabled]:focus,
  body.zh_logged_in .zhc-timeline-button.zhc-timeline-button--variant-text[disabled]:hover,
  body.zh_logged_in .zhc-timeline-button.zhc-timeline-button--variant-text:active,
  body.zh_logged_in .zhc-timeline-button.zhc-timeline-button--variant-text:focus,
  body.zh_logged_in .zhc-timeline-button.zhc-timeline-button--variant-text:hover,
  body.zh_logged_in .zhc-tutorial-card__title, body.zh_logged_in .zhc-username,
  body.zh_logged_in .zhc-workspace-switcher-empty__title,
  body.zh_logged_in .zhc-workspace-switcher-item,
  body.zh_logged_in .zhc-workspace-switcher-item__search-terms {
    color: #bebebe;
  }
```

Furthermore, it seems that even more input fields are not respected by the color css, for example `label`, `milestone` pickers etc (`class="zhc-search__input zhc-selection-filter__input"`)

**Comment by silverwind** [comment]
I meant the original rules that set `color` on the affected elements, seen when the userstyle is turned off. If we know the original color, we can remap it to a replacement one.

**Comment by jarhoax** [comment]
@silverwind Sorry for not being present the last days.

To your question: The initial color comes from the default css styling for the `input`, `textarea` tag

```css
input, textarea {
    …
    color: initial;
    …
}


```
