### ISSUE TITLE
When forking a repository, the fork logo is white.

### ISSUE THREAD

**Issue by yousef157** [StylishThemes/GitHub-Dark#976]
* **Browser**: Google Chrome
* **Operating System**: Windows 10 Pro
* **Link to page with the issue**: Fork any repository.
* **Screenshot**: 
![image](https://user-images.githubusercontent.com/48018938/62555585-42f42080-b884-11e9-9388-e307de89a0d7.png)

**Comment by the-j0k3r** [comment]
@yousef157 thanks for opening this issue. Its been a niggling issue but its not easy to catch the selector. Though I managed.

You can try playing around with the filters, I wasnt happy with result

```css
.spinner-forking[src*="spinners/fork.gif"] {
    filter: invert(100%) hue-rotate(180deg) !important;
    mix-blend-mode: exclusion;
  }
```

Ill see if I can make a codepen with the actual gif in order to twek the hack to a better level.

That or someone beats me to it.

Thanks again.
