### ISSUE TITLE
GH Actions Hero White Background

### ISSUE THREAD

**Issue by skmedix** [StylishThemes/GitHub-Dark#977]
* **Browser**: Chrome Stable 76.0.3809.100
* **Operating System**: Win 10
* **Link to page with the issue**: https://github.com/features/actions
* **Screenshot**:

![image](https://user-images.githubusercontent.com/3246162/62777191-09522e00-baad-11e9-94dd-b0501091ee0d.png)

Proposed solution
---
```css
  .actions-hero-bg {
    background-image: none;
  }
```

Result
---
![image](https://user-images.githubusercontent.com/3246162/62777428-ce9cc580-baad-11e9-960a-ad664eafdd76.png)
