### ISSUE TITLE
help.github.com is using highlight.js for syntax highlighting

### ISSUE THREAD

**Issue by xt0rted** [StylishThemes/GitHub-Dark#980]
* **Browser**: chrome 76
* **Operating System**: win10
* **Link to page with the issue**:
  - https://help.github.com/en/articles/configuring-npm-for-use-with-github-package-registry
  - https://help.github.com/en/articles/configuring-nuget-for-use-with-github-package-registry
  - https://help.github.com/en/articles/metadata-syntax-for-github-actions

I'm not sure when this started but [highlight.js](https://highlightjs.org/) is being used on the help site now for syntax highlighting. This looks to be happening on the server side because there's no JS for it running in the browser.

Do we want to add highlight.js themes for `help.github.com` or just revert the colors back to their defaults for the time being?

For now I'm reverting the background & color of these code blocks with the following:

```css
@-moz-document domain("help.github.com") {
  /* Unstyle code blocks until support is added to GHD */
  .markdown-body pre {
    background-color: #f6f8fa !important;
    color: #24292e !important;
  }
  .hljs {
    background: #f8f8f8 !important;
    color: #24292e !important;
  }
}
```

**Comment by silverwind** [comment]
Adding another syntax system (the 4th one now) will be a lot of work unless we find a way to abstract them further (and possibly generate all the themes from code). Maybe just go with a invert+hue-rotate filter on any element with the `.hljs` class as a start.

**Comment by xt0rted** [comment]
None of the highlight.js themes should require manual adjustment so it should be a straight copy into this style. I need to setup something to download these same themes for my vscode extension so maybe what I come up with for that could also be used as a starting point for this.

**Comment by Mottie** [comment]
What about trying:

```css
@-moz-document domain("help.github.com") {
  code.hljs {
    filter: invert(30%) brightness(1.5);
  }
}
```
