### ISSUE TITLE
Issue comment arrows are broken, again

### ISSUE THREAD

**Issue by xt0rted** [StylishThemes/GitHub-Dark#982]
* **Browser**: chrome 76
* **Operating System**: win10
* **Link to page with the issue**: https://github.com/StylishThemes/GitHub-Dark/issues/981
* **Screenshot**:

![image](https://user-images.githubusercontent.com/831974/63060934-9c320480-bec1-11e9-96f6-68c018897fdd.png)

**Comment by xt0rted** [comment]
Looks like this is fixed in 77e15bff3a28bf141e4aadb789e7540823a50eb6.

**Comment by xt0rted** [comment]
Looks like this was only partially fixed in https://github.com/StylishThemes/GitHub-Dark/commit/77e15bff3a28bf141e4aadb789e7540823a50eb6.

![image](https://user-images.githubusercontent.com/831974/63186954-bd166900-c02b-11e9-9a3e-24807b0d3049.png)

The color is coming from this rule via the `filter`.

```css
.review-comment:target .timeline-comment--caret:before,
.timeline-comment-group:target .timeline-comment--caret:before,
.timeline-comment:target .timeline-comment--caret:before {
  border-right-color: #2188ff;
  filter: drop-shadow(-.28em 0 0 #c8e1ff);
}
```
