### ISSUE TITLE
Is there anyway to change the global background color?

### ISSUE THREAD

**Issue by AurevoirXavier** [StylishThemes/GitHub-Dark#985]
It's too dark for me.

**Comment by AfroThundr3007730** [comment]
@AurevoirXavier I answered you [on Gitter](https://gitter.im/StylishThemes/GitHub-Dark?at=5d5c0f4d53490e334d2d95fc), btw.

> You find style settings in the Stylus dropdown menu. 
> ![Gear Icon](https://i.imgur.com/JsaKkZd.png)
> Click the gear icon for the Github-Dark settings, then the background settings are right there.
> ![Background settings](https://i.imgur.com/96fNcKi.png)

**Comment by the-j0k3r** [comment]
I would like to add in addition what was said, with a light texture it may blend the dark bg into a lighter version, just a question of finding/creating the right texture.

Alternative being editing the style and changing colors yourself.

**Comment by silverwind** [comment]
Could set it to the base64 form of a 1x1 background PNG. There's even a generator for pixels like that: http://png-pixel.com/

**Comment by AurevoirXavier** [comment]
@silverwind Thanks.

Actually, there are two background. I want to change both of them.

<img width="934" alt="WX20190821-102339@2x" src="https://user-images.githubusercontent.com/16152305/63397625-c45bbf00-c3fd-11e9-9a10-4b0502a79013.png">

**Comment by Mottie** [comment]
You'll need to add a [companion style](https://github.com/openstyles/stylus/wiki/Writing-styles#making-a-companion-style). Try starting with this style:

```css
/* ==UserStyle==
@name           github.com extra styling
@namespace      Me
@version        1.0.0
@description    Custom styling for GitHub
@author         Me
==/UserStyle== */
@-moz-document domain("github.com") {
  body .timeline-comment, body .input-contrast {
    background-color: #333 !important;
  }
}
```
