### ISSUE TITLE
Unstyled hamburger menu background on smaller viewports

### ISSUE THREAD

**Issue by AfroThundr3007730** [StylishThemes/GitHub-Dark#990]
Open https://github.com/ while logged out, and you'll see the hamburger menu has a transparent background. Note that the hamburger only appears on smaller viewports.

![image](https://user-images.githubusercontent.com/7613032/64202530-e551f480-ce80-11e9-8267-832c79c9ba77.png)

**Comment by xt0rted** [comment]
@silverwind this is happening because the generator isn't handling the `@media` query in the main style sheet. The original style is:

```css
.page-responsive .HeaderMenu--logged-out {
    background-color: #fff;
    box-shadow: 0 10px 50px rgba(27,31,35,.15);
    overflow: auto;
    width: 300px;
    z-index: 100
}

@media (min-width: 1012px) {
    .page-responsive .HeaderMenu--logged-out {
        background-color:transparent;
        box-shadow: none;
        overflow: visible;
        width: auto
    }
}
```

This has come up a few times, was anything ever done to try and handle media queries?
